### ISSUE TITLE
Consolidate meetings

### ISSUE THREAD

**Issue by kpk47** [slsa-framework/slsa#1036]
We currently have two regular meetings: a weekly SLSA Specification meeting and a monthly SLSA Community meeting. Roughly the same group of people attend each, so we should consolidate. I propose that we merge the two into a weekly SLSA meeting that combines the scope of the two meetings.

**Comment by kpk47** [comment]
This meeting has been removed from the OpenSSF Community Calendar. We will be consolidating with the Monday SIG meetings.

**Comment by MarkLodato** [comment]
This is still present on https://slsa.dev/community and the [community meeting notes](https://docs.google.com/document/d/1JbJZxeZOWE7rxT24iEozX35LIUl_Yoqd-DeSm6309GA/edit#heading=h.gjdgxs). Could you please update those as well?

And also update https://slsa.dev/notes to keep the link but just mark it deprecated.

**Comment by kpk47** [comment]
I just pushed an update to the community page and announced the change on slsa-discuss@ (https://groups.google.com/g/slsa-discussion/c/sCo4flBxBT8).
