### ISSUE TITLE
Clarify the 'merger' identity in source track

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1074]
There is an actor who "clicked the merge button", but this may or may not be the identity of the actor that authenticated to push the changes. 

For example, I may click the merge button to add a PR to a GitHub Merge Queue, but the Merge Queue's service principal is the identity who eventually pushes the ref update of the main branch.
This is because merge-queue-like systems contain the contents of multiple contributors and change sets.

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588368932_

**Comment by TomHennen** [comment]
Please see [the original comment](https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588368932) and [this discussion](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0#heading=h.axo9tq8hv5k4)

**Comment by zachariahcox** [comment]
We can continue to discuss this, but probably it will just be "whatever contract is supported by the SCP". 
If the SCP uses a bot to merge changes, it might be a bot, or else it might be the user who clicks the button. Both can be fine.
