### ISSUE TITLE
Source control platforms also provide identity

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1075]
Source control platforms will typically provide an identity model too. 
That identity is what would typically be used to build out "authentic contributions."
Source control platforms will also provide timestamps for activities.

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588328403_

**Comment by TomHennen** [comment]
The gist of the issue is ensuring the 'source control platform' definition is complete and includes the identity services they provide.

See also [this discussion](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0#heading=h.m6lfwq24yfqx)

**Comment by zachariahcox** [comment]
this was addressed in #1097
