### ISSUE TITLE
VCS and SCP concerns are mixed or too prescriptive

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1076]
This section may be mixing concerns between the VCS and the source control platform (SCP). 

Git commit metadata is forgeable from the perspective of the SCP. 
The SCP typically provides an identity / authz layer which is separate from the git content it manages, and it maintains its own timestamps for when activities happened from its perspective. EG: a commit may claim it was authored last year, but all the SCP knows for sure is that it was uploaded last week. 

Authentic contributions will typically be built in terms of the SCP's identity and timestamp models, not the VCS's.

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588404016_

**Comment by TomHennen** [comment]
See also [this discussion](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0#heading=h.try8gk97dhej)

**Comment by zachariahcox** [comment]
this idea has been refined to focus more on ensuring that the issuer's claims are things about which they can make authoritative statements. 

IE: git can make claims about content and trees, but not timestamps (there is no verifiable way to do this).
The SCP (or the host of the git service) can make timestamp claims from its own perspective. When was a request received, etc.

**Comment by zachariahcox** [comment]
Marking "closed" for now! Please feel free to reopen if you feel we didn't address this topic fully 👍
