### ISSUE TITLE
Clarify that self-hosted SCPs are allowed

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1077]
> host their source on a source control platform

Would this include self-hosted versions of SCPs?

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588416704_

**Comment by zachariahcox** [comment]
I think that draft pr implies that "self-hosted" source platforms are fine as long as they are modern source control systems.

**Comment by zachariahcox** [comment]
this was addressed by 1097
