### ISSUE TITLE
Create guidance for consumers on how to evaluate the source platform

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1078]
@joshuagl notes that in SLSA v1 we provide guidance to consumers on how to evaluate build platforms https://slsa.dev/spec/v1.0/verifying-systems.

We should do something similar for source.

**Comment by zachariahcox** [comment]
This will be related to the general SLSA guidance of trust the platforms, verify the outputs.

**Comment by zachariahcox** [comment]
closing this one -- the doc is drafted. 
Due to the duplicative nature of some of the content, I think we should harden the source-requirements doc, then copy out the summaries to verifying-source.md.
