### ISSUE TITLE
Clarify what must be retained during source migrations

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1079]
verified timestamps are provided by the SCP, so when I migrate the source to a new SCP, I think this means that the org must keep the original repo around to keep the "true" timestamps. 
Or else, we may be saying that SCPs must provide a way to export the verified timestamps somehow. We should consider making that clearer here, and I'm not sure which way is better! I'm not sure SCPs would import timestamps like that.

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588428303_

**Comment by TomHennen** [comment]
See also [this discussion](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0#heading=h.dx5sa2w43yoq)

**Comment by zachariahcox** [comment]
I think we are strongly leaning towards attestations being "from the perspective of a specific authority."

Migrating a repo between two servers will be inherently lossy. 
If a repo moves from github to gitlab, gitlab will not trust the timestamps issued by github, but github might still verify an attestation it issued in the past. 

It is not clear if gh would continue to _host_ attestation for repos that have been taken down (almost certainly it would not under normal circumstances), but the signed attestations can be downloaded and migrated (and served) if desired by the new host.

**Comment by zachariahcox** [comment]
I propose we add: 

"SCPs are not required to export any information during repo migration. All provenance attestations are issued from the perspective of the SCP and are based on knowledge that may or may not be publicly available."

**Comment by zachariahcox** [comment]
we have removed most of this related text from the source-requirements doc. marking closed for now.
