### ISSUE TITLE
Clarify Robot Approval

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1080]
Should a robot approval count or must it always be human?

_Originally posted by @zachariahcox in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1588429935_

**Comment by TomHennen** [comment]
See also [this discussion](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0#heading=h.7507driiqsl5)

**Comment by joshuagl** [comment]
we've had various discussions about robots in the past, linking here to the ones preserved in GitHub:

- https://github.com/slsa-framework/slsa/issues/287
- https://github.com/slsa-framework/slsa/issues/196
- https://github.com/slsa-framework/slsa/issues/234
- https://github.com/slsa-framework/slsa/issues/298

**Comment by zachariahcox** [comment]
based on the work here https://github.com/slsa-framework/slsa/pull/1097, I think the proposal is this: 

SLSA Source track is about producing trustworthy attestations and should require only the absolute minimum policies required to do so. 
To that end, SLSA will require strongly authenticated actors at higher levels but makes no further requirements. 

It is up to future policy writers to decide if robot approvals are allowed or not for a specific context.

**Comment by zachariahcox** [comment]
I believe this topic is covered by https://github.com/slsa-framework/slsa/issues/196

The working theory is that SLSA source track is primarily concerned with the trustworthy generation of provenance attestations.
The implied meaning of the contents of those attestations (and whether or not combinations of rules qualify a revision for various grades) is opinionated and up to the issuer of the vSA.

Marking "closed" for now. Please reopen if you feel that this topic has not been addressed fully! Thanks!
