### ISSUE TITLE
what is the process for getting added to a role in slsa-framework/slsa?

### ISSUE THREAD

**Issue by zachariahcox** [slsa-framework/slsa#1085]
For organizing work on the source-track, I have been sending @TomHennen lots of issues to label. 

To help remove friction here, I think it would make sense to assign me to the [Triage role](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#repository-roles-for-organizations) in this repo. 

What is the right process to petition for this? Thanks!

**Comment by TomHennen** [comment]
FWIW I'd support this.

**Comment by joshuagl** [comment]
We discussed this in the slsa spec meeting today and @arewm, @mlieberman85, @lehors and myself all agreed we should grant Zac the triage role. I just sent the invite. Thanks for all your contributions Zac, enjoy the reduction in admin work Tom.
