### ISSUE TITLE
Create SLSA Draft specification

### ISSUE THREAD

**Issue by arewm** [slsa-framework/slsa#1086]
As discussed in the community call on July 1st, we should create a dedicated draft specification directory. We have been using the 1.1 specification as a scratchpad for work that we don't want to release yet. 

In order to increase visibility of ongoing work, we should make this content public on the website in a form that indicates that it is _not_ a specification.

Proposal: 
* Rename the `v1.1` specification to `draft`. 
* Clearly indicate that the draft directory is not specification. It is work that we are keeping track of. The content for the next releases will likely come from the draft directory.
* Make the draft directory visible on slsa.dev

**Comment by lehors** [comment]
Yes, this matches what I had in mind. I'm in favor.

**Comment by marcelamelara** [comment]
Looks like this issue can be closed?
