### ISSUE TITLE
The leveling conundrum

### ISSUE THREAD

**Issue by AdamZWu** [slsa-framework/slsa#109]
When a set of levels (e.g. SLSA) are freshly defined / developed, we could enjoy some nice properties, such as the requirements of each level on different components are carefully aligned so that the security (i.e. difficulty to attack) of each component on the same level are balanced.

But after the levels are published and adopted, we could discover new attacks on certain previously uncovered aspects of some components with varying difficulties. And a low-bar attack would wreck havoc on the existing levels:
- To defend the attack, we need to add new requirements on affected components;
- The problem is *where* do we add them:
    - If we add to existing level definitions, we have a problem of "run-away target" - customers working towards qualifying a level finding their goal post is moving further;
    - If we create a higher level and add to there, the problem is that this effectively squashes previous levels from the security value point of view. Because the attackers always will aim at the easiest target, if we only start to defend a low-bar attack at level X, then many if not all the previous X-1 levels wouldn't make much difference.
        - "We have 5 levels of escort services for your money, with increasing protection coverage, but for level 1~4 someone wearing a blue hat with pink slippers can take anything, which level would you choose?"

**Comment by AdamZWu** [comment]
Inspired by [dependency confusion attack](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610), where confused artifact fetching and unverified dependencies allow unprivileged attacker to inject arbitrary logic into build artifacts.

**Comment by MarkLodato** [comment]
In #40 we discussed versioning the levels for this purpose, e.g. "SLSA 3 (2021-04-29)". At the time we decided to not explicitly version **yet** to indicate that the levels are subject to change. Once they're more final, we'll add a date.

**Comment by AdamZWu** [comment]
Ah great, that would solve the problem!
