### ISSUE TITLE
Proposing new org members for tooling

### ISSUE THREAD

**Issue by haydentherapper** [slsa-framework/slsa#1101]
I’d like to propose myself as an org member so that I can be added as a maintainer on the tooling repos to assist with reviews and development.

Supported by current tooling maintainers @ramonpetgrave64 @laurentsimon 

Can an org owner add me as a member? The tooling maintainers will take care of adding me to the correct teams.

**Comment by haydentherapper** [comment]
We would also like to add @loosebazooka as well.

**Comment by ramonpetgrave64** [comment]
@haydentherapper the rapper has been very helpful reviewing PRs for slsa-verifier, and quick to help resolve a critical issue this year with slsa-github-generator.

 - https://github.com/slsa-framework/slsa-verifier/pulls?q=reviewed-by%3Ahaydentherapper+
 - https://github.com/slsa-framework/slsa-github-generator/pulls?q=is%3Apr+author%3Ahaydentherapper+

**Comment by TomHennen** [comment]
I went ahead and invited @haydentherapper to be a slsa-framework org _member_.

@loosebazooka is already a member.

**Comment by TomHennen** [comment]
I'll close but:

1. Reopen if that didn't work.
2. Reopen if you think they shouldn't be members.
