### ISSUE TITLE
Getting Triage access to this repo

### ISSUE THREAD

**Issue by marcelamelara** [slsa-framework/slsa#1108]
As a workstream shepherd and contributor, I used to be able to add/remove tags, assign issues/PRs and review related PRs, but that access seems to have been revoked recently. If you could please grant me Triage access, I should be able to perform all of those tasks again. I will consider becoming a Maintainer through the existing process.

Thanks!

CC @TomHennen

**Comment by TomHennen** [comment]
Gave you triage access.  Everything working now?

**Comment by marcelamelara** [comment]
Yes, thank you! Everything's working now.
