### ISSUE TITLE
Clarify the goals / use-cases for each level

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#111]
Issues like #100 show us that we need to clarify what _specific_ things we expect users to get out of each level. Without this, we don't have a clear reason to add or remove a requirement at any particular level.

Example use cases for SLSA 1:

* Inventory all of the source and build systems used across a large organization.
* Prevent project maintainers from making mistakes in the release process, such as building from unsubmitted code.
* Adopt all the expected workflow changes now, as required by higher SLSA levels, while waiting for implementation (and security) to follow. For example, "enforcing" code review on all code changes, even though it can be bypassed by faking the provenance.

**Comment by TomHennen** [comment]
Hey @brunodom @david-a-wheeler @joshuagl @marklodato @mlieberman85 @trishankatdatadog @zakgreant

If you have time can you take a look at @msuozzo's doc above and see if generally does what you're looking for?  If so a PR could be put together to formalize this take, and if not we can take another stab at it.

(Might be worth discussing at Wednesday's meeting)

**Comment by trishankatdatadog** [comment]
@msuozzo @TomHennen are scenarios in the doc supposed to be the use cases @MarkLodato was describing above?

**Comment by brunodom** [comment]
@msuozzo @TomHennen just thinking out loud: In enterprise, there's a lot of code produced by the System Integrators that may develop software components of a major application/service. So we should somehow include the levels 3rd party organizations being part of the supply chain and how to assess the downstream.

**Comment by MarkLodato** [comment]
Sorry for the delay in reviewing. Overall LGTM! I added some comments, but once those get resovled, we should merge it into the site. (We'll have to figure out how to organize as we add more pages.)

> are scenarios in the doc supposed to be the use cases @MarkLodato was describing above?

Yes

**Comment by zakgreant** [comment]
Sorry for the late review. I find that the document clarifies the goals and use cases for each level. I've given a detailed review and made minor suggestions for clarity.

**Comment by joshuagl** [comment]
Apologies, I provided feedback in a couple of meetings where this came up but did not do so in a durable way. I like the document and agree we should merge it into the site.

Nice work @msuozzo !

**Comment by MarkLodato** [comment]
I tried to address for v1.0 in #502. Please take a look. Unless I hear otherwise, I will consider that PR to fix this issue.
