### ISSUE TITLE
Set up Developer Certificate of Origin

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#112]
We should add a CONTRIBUTING.md file listing https://developercertificate.org/ and require a Signed-Off-By line ([example](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work)), as required by OpenSSF.

See also #75 which would also go in CONTRIBUTING.md.

**Comment by joshuagl** [comment]
We can also add a GitHub Check for DCO on contributions, like this one https://probot.github.io/apps/dco/

**Comment by joshuagl** [comment]
I took a stab at this in #117
