### ISSUE TITLE
What does "exist in the present context" mean?

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1138]
> What does "exist in the present context" mean?

_Originally posted by @marcelamelara in https://github.com/slsa-framework/slsa/pull/1094#discussion_r1722360178_

@zachariahcox
>  for git repos, a revision is just a tree id in a big database.
Preventing trees from existing can only happen at push receive time and causes a ton of developer friction.
> 
> Especially when teams rely on pull requests, the "reachable from this ref" security boundary is the most practical. It models whether a commit / tree id is included in a specific subset. That subset has certain properties. I think that's what we're saying by context here, but it might need some additional definition here!

**Comment by zachariahcox** [comment]
I think we're proposing a new definition: 

"Revision context": a named subset of revisions. Inclusion in the subset can be governed by policy.

**Comment by TomHennen** [comment]
To be honest, a lot of that went over my head. :p

I was going to suggest just removing "in its present context", but I think what you're after is protecting the association of refs with the revision.  _That_ makes me think this is related to the `source_branches` field in the VSA.

So maybe "A source attestation contains information about how a specific revision was created and how it came to have any branches, tags, or other refs associated with it."

WDYT?
