### ISSUE TITLE
Be more explicit code review?

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1140]
> This requirement isn't very clear. Is this alluding to code review?

_Originally posted by @marcelamelara in https://github.com/slsa-framework/slsa/pull/1094#discussion_r1722382821_

**Comment by TomHennen** [comment]
FYI @zachariahcox 

FWIW I think requiring code review at Level 3 wasn't the intent?  We'd talked about having a separate tag that indicates if revisions are subject to code review.

**Comment by zachariahcox** [comment]
the text at the time was: "The change management tool MUST be able to authoritatively state that each new revision reachable from the protected branch represents only the **changes reviewed** via the process."

I think we can fix this by sticking with the "change management" phrase everywhere. 
EG: 

"changes reviewed" -> "changes managed"
