### ISSUE TITLE
SSDF is no longer "Forthcoming"

### ISSUE THREAD

**Issue by Callek** [slsa-framework/slsa#1155]
just caught this in the about page:
>  A way to measure your efforts toward compliance with forthcoming Executive Order standards in the [Secure Software Development Framework (SSDF)](https://csrc.nist.gov/Projects/ssdf)

That looks like its no longer "Forthcoming" (since ~2022) -- but I haven't personally dived too deep into SSDF specifically

This is currently the case both in the 1.1 RC and the working draft version

**Comment by lehors** [comment]
Indeed. Thanks!
