### ISSUE TITLE
Source 'systems' need strong auth too, not just change management tools

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1199]
In [this PR comment](https://github.com/slsa-framework/slsa/pull/1194/files#r1802054524) @zachariahcox says

> I think the platform [system] would also need strong auth too at l3, right?

And I think that's right.  Filing this issue to fix.

**Comment by TomHennen** [comment]
In fact I think the _text_ for strong auth under 'change management tool' probably needs updating too.

**Comment by TomHennen** [comment]
Actually, maybe we just move it entirely.  I think listing it with the change management tool might be redundant.

**Comment by zachariahcox** [comment]
apropos [this comment](https://github.com/slsa-framework/slsa/issues/1010#issuecomment-2406437487)

I think the change management tool and the data storage tooling are allowed to be different identities. 
For mega platforms like githublabops, they could be the same, but if they are not the same (ie, the PR tool is totally separate from the git tool) we'd have some baseline auth concerns. 

Actually those auth concerns are probably the same for all tools in the slsa system, VCS, PR, Build, Distribution, Hardware platform. Maybe we can separate it all out.
