### ISSUE TITLE
'verifiying-artifacts' needs to be updated to match new threat diagram

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1233]
verifying-artifacts.md mentions and links to the various threats.  These are now out of date with the new threat diagram.

In addition, the 'check expectations' threat mentions it addresses threat 'c' when really it can be used to address a number of them.

**Comment by lehors** [comment]
Are you sure you're looking at [the Draft version of verifying-artifacts.md](https://slsa.dev/spec/draft/verifying-artifacts)?
When I look at it, I don't see what you're reporting. Instead I see the updated diagram and a reference to threat "D" in '[Step 2: Check expectations](https://slsa.dev/spec/draft/verifying-artifacts#step-2-check-expectations)'.

**Comment by TomHennen** [comment]
Apparently I was not. :(

Sorry for the noise!
