### ISSUE TITLE
Add the BuildEnv track to the future directions page

### ISSUE THREAD

**Issue by marcelamelara** [slsa-framework/slsa#1255]
Upcoming tracks are usually described in the [Future Directions](https://slsa.dev/spec/v1.0/future-directions) page of the SLSA spec. We should currently add the BuildEnv track there as well!

Originally discussed in https://github.com/slsa-framework/slsa/pull/1251#discussion_r1872280544

**Comment by marcelamelara** [comment]
@TomHennen Thoughts on which version of the spec this should be done in? I'm thinking the v1.1 RC makes sense so that this update is included in the upcoming release.

**Comment by TomHennen** [comment]
> @TomHennen Thoughts on which version of the spec this should be done in? I'm thinking the v1.1 RC makes sense so that this update is included in the upcoming release.

In 'draft'.  AIUI the general plan is to just copy everything from draft as needed when making changes.

**Comment by marcelamelara** [comment]
>the general plan is to just copy everything from draft as needed when making changes.

Ah, so any additional changes we may want to pull into v1.1 will be pulled into another RC?

**Comment by lehors** [comment]
> > the general plan is to just copy everything from draft as needed when making changes.
> 
> Ah, so any additional changes we may want to pull into v1.1 will be pulled into another RC?

Yes.
