### ISSUE TITLE
Source integrity isn't

### ISSUE THREAD

**Issue by david-a-wheeler** [slsa-framework/slsa#13]
The "Source integrity" criterion doesn't require source integrity at all, it only requires transport integrity from its distribution point to receipt. It doesn't, in particular, require any kind of digital signature verification. I agree that the *criterion* belongs here, I just think its name is misleading.

Rename it to "Source transport integrity" or something like that.

**Comment by MarkLodato** [comment]
Dropped source integrity in #55.
