### ISSUE TITLE
slsa.dev/provenance doesn't have any examples of 'git' materials

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#143]
Our provenance documentation doesn't have any examples of source actually coming from source control systems.  That seems odd since it's the primary expected usage.

I think we should have some examples that shows something like this:

```json5
...
    "materials": [{
      "uri": "git+https://github.com/slsa-framework/slsa.git",
      "digest": {"sha1": "abc..."}
    }]
...
```

Questions:

* Should we include branch in the URI?  Builders often (but not always!) have the branch.
* Is there anything else important that's missing?

**Comment by trishankatdatadog** [comment]
We should also include examples of files themselves being listed, besides the Merkle tree root of the repo

**Comment by TomHennen** [comment]
Do you mean the individual files that were used from the repo or do you mean files that were used that weren't fetched from source control?

**Comment by trishankatdatadog** [comment]
> Do you mean the individual files that were used from the repo or do you mean files that were used that weren't fetched from source control?

individual files used from the repo :)

this will be useful for cases where in-toto clients might want to easily verify that the source files passing thru the system were legit. with a git tree hash, that's impossible w/o pulling the source, but not impossible.

**Comment by TomHennen** [comment]
Oh, so I think for in-toto use cases we'd recommend [in-toto link predicate](https://github.com/in-toto/attestation/blob/main/spec/predicates/link.md).  That could be [bundled](https://github.com/in-toto/attestation/blob/main/spec/bundle.md) with the SLSA provenance (and any other attestaitons).

**Comment by joshuagl** [comment]
Resolved by https://github.com/slsa-framework/slsa/pull/147
