### ISSUE TITLE
Is a 'personified' SLSA a dip or a dancer?

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#145]
When representing SLSA as a personified actor (e.g. in slides) should it be a salsa dancer or a bowl of salsa?

Maybe SLSA can be either as best suits the situation.

**Comment by TomHennen** [comment]
Alternate suggestion: SLSA personified should be the OpenSSF Goose in some form or another: https://openssf.org/

**Comment by msuozzo** [comment]
Goose dancing? Goose eating salsa?

**Comment by trishankatdatadog** [comment]
> Alternate suggestion: SLSA personified should be the OpenSSF Goose in some form or another: https://openssf.org/

Why should SLSA be specific to the OpenSSF tho?

**Comment by trishankatdatadog** [comment]
My vote is for a colourful bowl of salsa

**Comment by TomHennen** [comment]
I think it's technically within the OpenSSF, but it doesn't matter to me.

**Comment by trishankatdatadog** [comment]
> I think it's technically within the OpenSSF, but it doesn't matter to me.

A good with the colours of salsa might be the best way forward w/o favouring dancers or nachos.

**Comment by 06kellyjac** [comment]
The goose could hold salsa instead of it's shield, or the shield could have salsa on it

**Comment by catherinemoresco** [comment]
Hi all, I'm a coworker of @TomHennen --I'd like to humbly propose the below dancing goose for your consideration 

(Attachment is a png, but it's done in svg so it's infinitely scalable)

![openssf-colorcopy-final-2 (1)](https://user-images.githubusercontent.com/6500934/131511658-a2af8e81-61b9-4ece-b520-cf99ef2fbfd9.png)

**Comment by kimsterv** [comment]
This is amazing. How about a version with heels? 👠

**Comment by joshuagl** [comment]
That's awesome @catherinemoresco!

**Comment by joshuagl** [comment]
I think we may have resolved this with #150 ?

**Comment by TomHennen** [comment]
Yeah, I think so.  Thanks again @catherinemoresco

**Comment by catherinemoresco** [comment]
Happy to help! :)

**Comment by Starefossen** [comment]
@catherinemoresco love the logo 😍 What is the license? Can I print it on a t-shirt?
