### ISSUE TITLE
Tag a initial/draft/non-final release of SLSA

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#155]
This will help other projects start planning and targeting their use of the initial levels of SLSA.  The tag could/should indicate that there may still be changes, while still allowing implementors to indicate what is is they actually do "e.g. we support SLSA 0.1"

Note that #19 proposes using dates to communicate versions.  I'm not exactly sure how we use dates _and_ indicate the tentative nature of the spec.  Any suggestions?

Are there any blockers to tagging this now?

Thoughts: @brunodom @david-a-wheeler @joshuagl @marklodato @mlieberman85 @trishankatdatadog @zakgreant ?

**Comment by inferno-chromium** [comment]
I do like the point releases, 0.1 clearly indicates that it has hit the first milestone and ready for trial. A date is very random, it does not tell the state in any way (is it stable, is it first or second or fifth version?). We can even do both, like 0.1 tag and date tag, but the point version seems more important for adoption. Others - thoughts ?

**Comment by mlieberman85** [comment]
Versioning is out of my wheelhouse. I do agree with sentiment though, we want to both convey progress as far as versions of the framework while also being able to easily tie it back to a date.

**Comment by TomHennen** [comment]
Thoughts about: "v0.1 - 2021-09-15" ?

**Comment by msuozzo** [comment]
what about `v0.1.20210915`. At least it's semver (ish) then.

**Comment by trishankatdatadog** [comment]
> Thoughts about: "v0.1 - 2021-09-15" ?

I like Tom's proposal the best, with no spaces in between.

**Comment by msuozzo** [comment]
> > Thoughts about: "v0.1 - 2021-09-15" ?
> 
> I like Tom's proposal the best, with no spaces in between.

Without the spaces, it's both visibly difficult to parse _and_ non-compliant with established versioning schemes.

**Comment by inferno-chromium** [comment]
> > > Thoughts about: "v0.1 - 2021-09-15" ?
> > 
> > 
> > I like Tom's proposal the best, with no spaces in between.
> 
> Without the spaces, it's both visibly difficult to parse _and_ non-compliant with established versioning schemes.

+1. i like "v0.1 - 2021-09-15"

**Comment by joshuagl** [comment]
Based on the discussion in the call yesterday I think we want:
- an indication that this is an early release (prerelease or draft status features prominently)
- a version identifier – a static identifier so that folks can be certain they are referring to the same thing
- an indication of timeliness – how new/old is this thing

Do we want the version to tell the full story here, or could we annotate the documents (requirements) themselves to help, i.e.
* A version number displayed prominently in the requirements along with an easy mechanism to find prior versions
* Last edited date (perhaps automatically stamped during the hugo build?) displayed prominently on the requirements
* A notice that this is still an early/draft/provisional version that we can remove once ready

**Comment by inferno-chromium** [comment]
> Based on the discussion in the call yesterday I think we want:
> 
> * an indication that this is an early release (prerelease or draft status features prominently)
> * a version identifier – a static identifier so that folks can be certain they are referring to the same thing
> * an indication of timeliness – how new/old is this thing
> 
> Do we want the version to tell the full story here, or could we annotate the documents (requirements) themselves to help, i.e.
> 
> * A version number displayed prominently in the requirements along with an easy mechanism to find prior versions
> * Last edited date (perhaps automatically stamped during the hugo build?) displayed prominently on the requirements
> * A notice that this is still an early/draft/provisional version that we can remove once ready

Yes i think we can do both, we can tag the release with version-date string and add that in requirements section as well or atleast link to a stable version in requirements section

**Comment by msuozzo** [comment]
I think @joshuagl is suggesting we not use the date string in the version identifier and instead represent it in other ways (e.g. last updated header, etc.)

**Comment by MarkLodato** [comment]
Suggestion: "v0.1 (2021-09-15)". The version number is just "0.1" ([SemVer2](https://semver.org)), but we write it with the date in parentheses for ease of understanding. The git tag would just be "v0.1".

Alternatively we could put the date in the "build metadata" of the SemVer2, i.e. "v0.1+2021-09-15", but to me that's much harder to read.

**Comment by inferno-chromium** [comment]
> Suggestion: "v0.1 (2021-09-15)". The version number is just "0.1" ([SemVer2](https://semver.org)), but we write it with the date in parentheses for ease of understanding. The git tag would just be "v0.1".

LGTM

> 
> Alternatively we could put the date in the "build metadata" of the SemVer2, i.e. "v0.1+2021-09-15", but to me that's much harder to read.

**Comment by joshuagl** [comment]
> Suggestion: "v0.1 (2021-09-15)". The version number is just "0.1" (SemVer2), but we write it with the date in parentheses for ease of understanding. The git tag would just be "v0.1".

LGTM too

**Comment by inferno-chromium** [comment]
Done! Congrats everyone 

https://github.com/slsa-framework/slsa/releases/tag/v0.1
