### ISSUE TITLE
`scripted build` requirement seems to imply config-as-code

### ISSUE THREAD

**Issue by msuozzo** [slsa-framework/slsa#157]
I think there needed to be some wording tweaks to `Scripted Build` included in #141. The current wording is as follows:

> All build steps were fully defined in some sort of "build script". The only manual command, if any, was to invoke the build script.

This builder requirement has tick marks at all levels (i.e. it applies at L1-4).

#141 removed the requirement that a committed build script be used at L1-2 so, to my mind, the "manual command" bit no longer applies to all levels.

Given that this requirement is in the builder section, I see this requirement as trying to convey "build completeness" i.e. all steps that logically produce the output artifact are captured in the provenance. I think that sort of requirement is really valuable and is even more so now that L1-2 permits users to populate commands externally to source: We want those builds fully expressed in the recorded metadata.

To resolve this conflict, I think we can do one or more of the following:

* Remove the sentence that talks about limiting manual commands.
* Clarify or de-emphasize `script` to ensure the wording can apply to a recorded series of commands (e.g. L1) as easily as it can to a submitted script (L3+)
* Rephrase the requirement to `Build Completeness` (or `Script Completeness` or something less clunky)

**Comment by TomHennen** [comment]
My suggestion: _remove_ the 'scripted build' requirement.

**Comment by msuozzo** [comment]
That's certainly an option. But unless "build completeness" is represented somewhere else in the ladder, it might be nice to have a dedicated line item to convey.

**Comment by 06kellyjac** [comment]
If 'scripted build' is no longer a requirement of L1 then all L1 has is 'Provenance - Available'

I feel like this conversation has started somewhere else already but I can't remember where

**Comment by MarkLodato** [comment]
"Scripted build" has been removed as per #498, this issue is no longer relevant.
