### ISSUE TITLE
Proposal: Rephrase "config-as-code"

### ISSUE THREAD

**Issue by msuozzo** [slsa-framework/slsa#158]
This is definitely a nit but, rereading the ladder with fresh eyes, "config" in "config as code" feels a bit off from what the requirement is suggesting. This requirement is in the "build" section so the wording implies "build config as code." This might be interpreted as "the build's infrastructure and worker config needs to be in e.g. terraform" while the intent is more "build definition as code".

Looking around for alternatives, I see Jenkins seems to subscribe to ["Pipeline-as-code"](https://www.jenkins.io/doc/book/pipeline-as-code/) which I'm lukewarm on. Something simpler like "Build-as-code" or "Version-controlled Build" might be friendlier.

I think the change could be especially valuable in other sections of the ladder that need to reference this requirement since, when not given context, "config as code" is even more ambiguous.

I'm fine with the status quo but just thought a change could make things more friendly to new users.

**Comment by TomHennen** [comment]
Clarifying sounds fine to me.  Do you want to send a PR to make that clarification?

**Comment by msuozzo** [comment]
Fixed by #160
