### ISSUE TITLE
VSA v1: Indicating SLSA versions for policy evaluation

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#168]
For the purpose of automatic artefact verification and policies to evaluate SLSA attestations, do we need to care about the version of SLSA which is implemented? 

It has been suggested that we should not significantly alter SLSA levels once a release has been made, so perhaps SLSA level 1 is always equivalent enough that a policy engine does not need to distinguish between SLSA v0.1 level 1 and SLSA 1.2 level 1 – if that's the case, we should capture that decision and enforce it during PR reviews.

**Comment by MarkLodato** [comment]
I think tooling should indicate (or allow users to choose?) which version of the SLSA framework is being used. Maybe down the road the levels will be stable enough that it won't be an issue, but for now I think that there's still enough in flux that versioning is useful.

**Comment by joshuagl** [comment]
When to tackle this depends on making a decision whether to include https://github.com/slsa-framework/slsa/issues/46 in 1.0

**Comment by kpk47** [comment]
@joshuagl Does this still need to be included in 1.0, or is it covered by the requirement that package ecosystems place expectations on each package?

**Comment by joshuagl** [comment]
Great question. I think Mark's statement still holds, that tools probably should declare the version of the verification logic they are implementing. But I don't think we need to address this for 1.0, it's more likely to be a useful recommendation post 1.0.

**Comment by kpk47** [comment]
policy_level also needs to change.
