### ISSUE TITLE
Merging tekton-provenance and slsa-provenance predicate formats

### ISSUE THREAD

**Issue by priyawadhwa** [slsa-framework/slsa#176]
I'm opening a tracking issue where we can keep track of progress on this and consolidate opinions. Some things to consider:
- [x] https://github.com/slsa-framework/slsa/issues/175
- [x] https://github.com/slsa-framework/slsa/issues/177
- [x] https://github.com/slsa-framework/slsa/issues/178
- [ ] https://github.com/tektoncd/chains/issues/249 in Chains

Feel free to add anything I forgot! 

cc @loosebazooka @MarkLodato @inferno-chromium @bobcatwilson @TomHennen @msuozzo

**Comment by dlorenc** [comment]
The other biggest one IMO is the definedInMaterial pointer. This is covered in bad API design smells, and seems hard to actually use correctly.

I'd strongly prefer the recipe URI approach used in Tekton Chains. The system can refer directly to where it fetched the recipe at a URI. That may or may not be in a material.

**Comment by trishankatdatadog** [comment]
Seems fine to me.

**Comment by trishankatdatadog** [comment]
> * Separate materials from steps

Agree with the rest, but hold on, why separate materials from steps? Don't you want to associate materials/input and products/output with each step? Or am I misunderstanding what you mean here?

**Comment by joshuagl** [comment]
@dlorenc or @priyawadhwa could you link to/paste an example of a populated Tekton predicate? Might make this easier to think about.

**Comment by inferno-chromium** [comment]
Yes i agree, lets file sub-bugs and we can update c#0 to account for it. Thank you everyone for the productive discussion.

**Comment by dlorenc** [comment]
From the feedback we're receiving it seems like there's not really appetite to merge the changes from the Tekton format back in here. I agree it would be nice to have one format, but the goals might be different enough that it's better to just have multiple. 

Since adoption is still so early on both, I'll suggest we just wait until things mature and we have a better idea of how these are actually used end to end before making any changes.

**Comment by inferno-chromium** [comment]
> From the feedback we're receiving it seems like there's not really appetite to merge the changes from the Tekton format back in here. I agree it would be nice to have one format, but the goals might be different enough that it's better to just have multiple.
> 
> Since adoption is still so early on both, I'll suggest we just wait until things mature and we have a better idea of how these are actually used end to end before making any changes.

I do agree with your sentiment, but please note that SLSA steering committee has not made their decision on this, so we will give the benefit of doubt and resolve any conflicts with discussions in SLSA biweekly. I also think there should be multiple formats allowed, but what we say here is SLSA provenance format should be simplest and easiest to the use for the community for easy uptake.

**Comment by dlorenc** [comment]
> but what we say here is SLSA provenance format should be simplest and easiest to the use for the community for easy uptake.

Big +1!

I think the best way to do this is to iterate quickly, prototype, see what works, see what people actually want to use these payloads for and how they use them.

I don't think this is the type of thing that can be designed in a committee or a vacuum without first getting a lot more data and adoption. Arguing over the names of fields is missing the forest for the trees.

My focus in the Tekton predicate is on making it the most useful format for Tekton users, for whatever use cases they have. That means getting it in the hands of users.

**Comment by mattmoor** [comment]
Just to echo the sentiment about experimentation.  I was actually surprised to find that SLSA had already defined its own predicate type when I was first going through this because it’s very existence will preclude some amount of experimentation in the community.

**Comment by dlorenc** [comment]
> Just to echo the sentiment about experimentation. I was actually surprised to find that SLSA had already defined its own predicate type when I was first going through this because it’s very existence will preclude some amount of experimentation in the community.

I think the history here was actually in line with this sentiment, the "SLSA" format was initially defined in the in-toto attestation repo: https://github.com/in-toto/attestation. The in-toto attestation model is designed to support many predicate types, so we decided to move it from there to help make it clear that this wasn't the only supported in-toto predicate format.

It seems to have just moved the problem down a level though :)
