### ISSUE TITLE
Provenance: Consider simplifying `definedInMaterial`

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#178]
_[Forked from Issue #176]_

There has been some confusion about `definedInMaterial`, so it's worth considering whether there is a better design.

While we're at it, we may also want to address the issue that some builds may have recipe defined in more than one material.

### Current design: `definedInMaterial` index

Currently, all of the input artifacts are listed in `materials`, and `recipe.definedInMaterial` identifies which of these contained the recipe definition.

Benefits:

- Verifiers can handle all input artifacts identically. No need to special-casing the recipe (though they still can if they want to.)
- Reduce duplication in case a single artifact is both a recipe and a build input, such as in the case of GitHub Actions.

Drawbacks:

- More complex to read and write. Multiple implementers have already been confused by this, which highlights the need to improve.
- Only a single material (index) can be used.
- Index 0 means something different than null/undefined, which is undesirable since it's common for null and 0 to mean the same thing.
- Index can be out of range.

### Alternative 1: `definedInMaterial` URI

Make `definedInMaterial` a URI instead of an index. The semantics would be the same, except that you match by `materials[*].uri == recipe.definedInMaterial` instead of `materials[recipe.definedInMaterial]`.

Compared to current design:

- Pro: URI is more intuitive than index.
- Pro: Empty string can now mean the same as null/undefined.
- Con: If two materials have the same URI, the semantics are undefined. So we'd need to add a restriction that the recipe has to point to a unique URI. I love this particular restriction because there could be some edge case where you do want to have two URIs.
- Con: (minor) Validating and matching is slightly more difficult, since it's not just a simple array bounds check.

### Alternative 2: `recipe.definedIn` artifact reference

Instead of referring to a material, embed the artifact reference within `recipe`. That is, `"definedIn": {"url": "...", "digest": {..}}` (property name TBD). The value would be the same format as `materials`. If the same material is used as both an input to the build and defining the recipe, it gets listed in both locations.

Compared to current design:

- Pro: Makes `recipe` easier to understand and less prone to mistakes. (I think?)
- Pro: Removes possibility of using an out-of-bound index.
- Con: Duplication between `recipe` and `materials` in the common case.
- Con: Not always clear what is a `material` and what is a `recipe`. (Though we kind of have that situation now.)

### Other options?

Any other ideas? Opinions?

**Comment by dlorenc** [comment]
Also linking up to a lot of past discussion on this: https://github.com/in-toto/attestation/issues/43

**Comment by MarkLodato** [comment]
In case you want to use the digest instead of the URI. Consider the case where the policy requires the recipe URI to be `github.com/foo/bar`, but the builder built from a `internal.mirror/bar` (or didn't know the URI at all). In this case, the policy engine would join the provenance attestation to another [source attestation](https://github.com/in-toto/attestation/issues/47), where the provenance's recipe digest == source attestation's subject.
