### ISSUE TITLE
Decide versioning strategy

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#19]
We need to decide on a strategy for how to version the SLSA standards. We are not likely to get everything right on the first try. Plus, we need to break up the problem and make incremental progress before everything is figured out.

Questions:

1. Will we use make versioning explicit? Something like "SLSA N, revision X"? I can't think of another option, but I'd love to hear ideas.
2. Assuming we have an explicit version, how do we call it? "SLSA N, revision X"? Date? "Draft"? "Alpha"? Something else?
3. We likely will have initial revisions that are under specified. Should the name be different for those to indicate that they are partial? "Interim"? "Provisional"?
4. What criteria should we use for giving something a version? Periodic cadence? "When it's ready"? "ASAP"?

**Comment by MarkLodato** [comment]
Proposal: "Provisional SLSA 3, draft 1"

We can then differentiate between "you MUST do this to meet provisional SLSA 3" vs "we expect there to be a requirement around this but it's not in the provisional draft yet".

And I suggest giving an initial version ASAP - that is, as soon as we have the source, builder, policy, etc. requirements written. That way we can start building on it.

**Comment by TomHennen** [comment]
"Provisional SLSA 3, draft 2021-04"  SGTM

**Comment by MarkLodato** [comment]
Sounds good. Then I'll work toward adding something like that to the doc and update PR #17 to use that convention.

**Comment by MarkLodato** [comment]
Suggestion from @david-a-wheeler: SLSA 3 (2021-04-09). (With or without the "provisional"). The date makes it obvious it is a version.

**Comment by dlorenc** [comment]
I'll suggest we can handle this one later - we don't need a versioning strategy until we're comfortable with the actual criteria and are intending to signal that people should rely on it.

**Comment by MarkLodato** [comment]
Isn't this a very simple thing to do? Just slap a date on the doc. That makes it much easier for people to refer to it.

**Comment by MarkLodato** [comment]
Sent #40 to add a date. After that, I agree that we can defer this to the "make SLSA easy to understand" milestone.

**Comment by MarkLodato** [comment]
With the latest commit, I think this is likely in a good enough state.
