### ISSUE TITLE
Should SLSA recommend artifact signing?

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#191]
SLSA does not current require signed artefacts, in part because an attestation is a generalised detached signature which allows for richer policy decisions than a boolean signed/not signed.

However, where supported signed artefacts provide value. There are also cases where the artefact itself being signed is required (i.e. when delivered through various OS application stores).

**Comment by jchestershopify** [comment]
As an aspiration, yes, but the value of signatures varies a lot according to the implementation.  I'm not sure how deep down the rabbit hole we'd need to go (eg, is a signature by a self-signed cert really worth that much?).

**Comment by joshuagl** [comment]
Absolutely. I think it's aspirational in a similar way to Build Reproducibility, hence the suggestion to make this a recommendation (O).

Build Reproducibility is recommended/aspirational because it's hard (and probably not always possible, at least not given finite resources).

Signing is recommended/aspirational because different publishing platforms support it to differing degrees and, ultimately, we'd like users to be making rich policy decisions based on attestations rather than a simple signed/not signed check.

Where it makes sense, signing provides value and should be recommended. However, is the list of caveats around "where it makes sense" to large to warrant the effort?

**Comment by jchestershopify** [comment]
> However, is the list of caveats around "where it makes sense" to large to warrant the effort?

The unhappy answer is: it depends. The water level for signatures is fairly low in most cases -- either non-existent, or fiddly and difficult. At best we can say "recommended" and periodically re-survey the field if new signing mechanisms emerge (as has happened for container images).

But we still need to think about what the minimum acceptable properties would be. Extending my earlier example: I think self-signed certs make authenticity a pleasant fiction, but if I reject their use then every scheme relying on PGP goes fwooshing out the window.

**Comment by trishankatdatadog** [comment]
@jchestershopify this is what Joshua and I are working on, and plan to address in our document.

Agreed that there are different levels of signatures and utility, ranging from (in rough/disputable order of increasing security):
* No signatures
* PGP/GPG
* Blockchains/transparent logs
* X.509
* SPIFFE/SPIRE
* TUF

Some of these options can even be mixed and matched. We plan to discuss these options, and allow users to decide what they want to do.

**Comment by marcofranssen** [comment]
> @jchestershopify this is what Joshua and I are working on, and plan to address in our document.
> 
> Agreed that there are different levels of signatures and utility, ranging from (in rough/disputable order of increasing security):
> 
> * No signatures
> * PGP/GPG
> * Blockchains/transparent logs
> * X.509
> * SPIFFE/SPIRE
> * TUF
> 
> Some of these options can even be mixed and matched. We plan to discuss these options, and allow users to decide what they want to do.

We have been working on a tool that allows to pull secrets or use Hashicorp Vault transit engine without the need for an initial secret utilizing Spiffe IDs.

https://github.com/philips-labs/spiffe-vault

It is a commandline utility that can also be used as a library inside your own Go code.

**Comment by trishankatdatadog** [comment]
> We have been working on a tool that allows to pull secrets or use Hashicorp Vault transit engine without the need for an initial secret utilizing Spiffe IDs.

I think SPIFFE/SPIRE, Vault, KMS, and other key _management_ systems should be separated from this discussion, because while they give you a way to _sign_ things, there is (almost always) no key _distribution_ system, which is needed to _verify_ arbitrary artifacts.

**Comment by mlieberman85** [comment]
For me, the thing I like about signed artifacts is around figuring out what identities performed what. Perhaps the tools performing the actions could provide the SLSA attestations that they did a thing and that would be the equivalent of a "signature" in this case. I just think we need to maybe broaden the attestations to include more than just attesting to "2 person code review" or similar but have the build tool attest that the artifact it built pulled the code from the github with the 2 person code review. Something like that.

**Comment by trishankatdatadog** [comment]
> For me, the thing I like about signed artifacts is around figuring out what identities performed what. Perhaps the tools performing the actions could provide the SLSA attestations that they did a thing and that would be the equivalent of a "signature" in this case. I just think we need to maybe broaden the attestations to include more than just attesting to "2 person code review" or similar but have the build tool attest that the artifact it built pulled the code from the github with the 2 person code review. Something like that.

This should be possible with the current SLSA in-toto attestations. You simply [match](https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.md#433-artifact-rules) whether the subjects/outputs of your developers match the materials/inputs to your source code repository (or, alternatively, whether the subjects/outputs of your source code repository match the materials/inputs to your builder). For example, just listing the Merkle tree root of a git repo should do.

**Comment by jchestershopify** [comment]
> For me, the thing I like about signed artifacts is around figuring out what identities performed what.

I see signatures as doing two things: providing authenticity and proving integrity. The latter can be achieved in other ways, such as publishing digests through some trusted alternative channel. But the former is the most interesting one to me.

**Comment by mlieberman85** [comment]
I agree. 

 For legacy use cases a lot of people are still signing. We might recommend that people do use attestations with an explicit "authenticity" claim but you can use signatures as an implicit attestation about authenticity until you have the right SLSA attestations?

**Comment by mlieberman85** [comment]
Maybe I misunderstood or misstated. I thought we were saying signing an artifact directly, e.g. just having a signature, broadly defined, is not as good as just having like an in-toto style attestation where the materials the attestation points to is just the artifact and the claim is "I built this thing"

**Comment by trishankatdatadog** [comment]
> Maybe I misunderstood or misstated. I thought we were saying signing an artifact directly, e.g. just having a signature, broadly defined, is not as good as just having like an in-toto style attestation where the materials the attestation points to is just the artifact and the claim is "I built this thing"

Depends on your threat model. We are trying to say that, depending on your threat model, you need both: yes, in-toto attestations are nice, but they are not as useful as they could be w/o signing these attestations (which covers artifacts, which means you are indirectly signing for them).

**Comment by adityasaky** [comment]
> However, where supported signed artefacts provide value

This may be a silly question, but can we discuss the value (apart from required situations like OS repositories) they provide that signed attestations recording the artifacts in question don't?

**Comment by joshuagl** [comment]
Good summary, it matches my understanding too. Thanks.

Recommending signing feels out of the scope of SLSA. On the requirements around signing keys specifically, perhaps we should move that to a separate issue and close this one (to improve the signal to noise ration on clarifications).

We do not want to implicitly require signing through our requirement that any secrets involved in providing authenticity and integrity of provenance metadata are only accessible to the build service and not user-defined build steps.

**Comment by trishankatdatadog** [comment]
> Recommending signing feels out of the scope of SLSA. On the requirements around signing keys specifically, perhaps we should move that to a separate issue and close this one (to improve the signal to noise ration on clarifications).

Let's get back to that issue on specifying which signing keys for which functionaries!

**Comment by joshuagl** [comment]
Closing this issue as the discussion resolved that we do not want to recommend generic artifact signing.
