### ISSUE TITLE
Link to "Operation SLSA: Episode 1"

### ISSUE THREAD

**Issue by david-a-wheeler** [slsa-framework/slsa#192]
Add links to ["Operation SLSA: Episode 1"](https://www.youtube.com/watch?v=S_MXbt0p_pg) in slsa.dev and the GitHub SLSA README.

**Comment by axelsimon** [comment]
#199 is a quick fix to the link in the README. It doesn't close this issue however, as we still need to put it on the website.

**Comment by devmoran** [comment]
Thanks @axelsimon but don't worry, we're making space for this as part of IF's redesign and we'll get it in

**Comment by joshuagl** [comment]
Operation SLSA episodes 1 & 2 are linked to from https://slsa.dev/community
