### ISSUE TITLE
Split Source and Built Artifact ("Package"?) requirements

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#21]
We have already defined SLSA to be non-transitive, such that the SLSA rating of built artifact does not depend on the ratings of its dependencies. But currently it does depend on its sources' ratings, which is odd because we don't have a strong definition of source vs dependency.

I propose that we fully split, such that each resource always has its own rating. Then we could split the requirements, one set for sources and one set for built artifacts. This would make things like two-person control more clear. For example, a GitHub repo that is owned by a single person may only be SLSA 2 (no two-party control), yet its built packages are all SLSA 3 because it uses an approved builder with provenance and reproducibility.

By the way, perhaps we should call the output of a build a "Package." That term fits the most common usage, and it is arguably correct for all examples. (Thanks @david-a-wheeler for the suggestion.)

**Comment by TomHennen** [comment]
What would policies look like if we made this change?

As it stands today people could easily create a policy that targets L3 which indicates that package (name sounds good BTW) was built from _direct_ sources that met these requirements.

If we split them would users have two settings?  I feel like that would make things harder to reason about.

Regarding dependencies that _aren't_ sources I had been thinking that perhaps package managers (Artifactory, etc...) could be accredited much like source control systems.  We could 'overlook' (for now) that there's not too party review.  A good long term solution would be to require the package managers to do some sort of admission control check (perhaps checking SLSA policies?) to get to L3.  (The policies it checks wouldn't necessarily need to be any particular level, I think it might be sufficient to say that it checks them.  Level requirements would be limited to whatever we decide for chained verification).

**Comment by MarkLodato** [comment]
I don't think there would be any change to policy content. All that would change would be implementation. Using the [example policy](https://github.com/slsa-framework/slsa#deployment-policies) from the proposal:

```yaml
scope: "pkg:docker/curlimages/curl"
slsa_level: 3
allow:
  builder: "github_actions"
  source: "https://github.com/curl/curl-docker"
```

That policy would remain unchanged, but the implementation would stop checking properties of the curl-docker repo when computing the `slsa_level: 3` check.

My thinking is that we'll need some [aggregate security measure](https://github.com/slsa-framework/slsa#composition-of-slsa-levels) to cover non-source dependencies anyway, so let's simplify the model. In other words, SLSA is a building block, not the final solution.

To get the current behavior in the new model, we could have something like:

```yaml
require_sources_to_meet_slsa_level: true
```

**Comment by TomHennen** [comment]
I'm not sure I'm a fan of that approach.  I'm currently thinking it makes it harder for people to understand what they're getting with SLSA 3.

As things currently stand one of the things your getting (one of the big benefits!) is 2-party review of the source code.

**Comment by MarkLodato** [comment]
But is the current SLSA 3 really giving that to people? Let's take Debian packages as an example. The "source" is not the actual upstream source, but instead the Debian git repo where they maintain patches and the build script. Thus, the current SLSA 3 only talks about two-party review on the Debian patches, but not on the code itself.

Perhaps that means we shouldn't be exposing SLSA directly and instead should work on the aggregate measure, using SLSA under the hood? (Or alternatively, call the non-transitive thing something else and call the aggregate measure SLSA?)

**Comment by MarkLodato** [comment]
Discussed with @TomHennen offline. We haven't come to consensus yet, but a few points we discussed:

- One of the main utilities of this proposal is to allow packages to reach SLSA 3 without requiring two-party code review (#4). An alternative solution would be to just drop that requirement from SLSA 3, while leaving the rest intact. Given @david-a-wheeler's wisdom that very few open source projects could ever reach two-party review for all commits, that is probably a good idea either way.
- The proposal might make SLSA even more confusing / weak. Although it doesn't cover dependencies, the security level of the build script has outsize importance on the security of the build and thus the package. Therefore, it makes sense to treat it specially in the model.

**Comment by joshuagl** [comment]
> One of the main utilities of this proposal is to allow packages to reach SLSA 3 without requiring two-party code review (#4). An alternative solution would be to just drop that requirement from SLSA 3, while leaving the rest intact.

This seems like the right path forwards. 

Intuitively, it feels like an artefact should be able to have a different SLSA level than the source code from which it was produced, however it seems counterintuitive that the package/artefact would have a higher SLSA level than the source code from which it was produced.

> By the way, perhaps we should call the output of a build a "Package." That term fits the most common usage, and it is arguably correct for all examples. (Thanks @david-a-wheeler for the suggestion.)

I don't think you will be able to pick a term that works for everyone, not all built outputs are packages (i.e. the cacert.pem file from the motivating example). Better to have a clear definition for each term, particularly as multiple entities are thinking about the same problem space and evolving their own terms that are often inconsistent with other groups. FWIW artefact gets my vote, not package.

**Comment by david-a-wheeler** [comment]
I prefer "package". No matter what, though, I agree that the *most* important issue is to clearly define terms (and that's challenging to do ). I think it's often necessary to give examples of common cases as part of those definitions. Examples often make clear what's otherwise so abstract that people have a hard time understanding it.

**Comment by MarkLodato** [comment]
I tried this in #50 but all reviewers said it hurt clarity. So I'll mark this as closed, will not fix.
