### ISSUE TITLE
Merge slsa-controls into this repo?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#23]
Currently https://github.com/slsa-framework/slsa-controls is a separate repo. Does that actually make sense? Should we just merge it here and add it as a subdirectory? That might make it easier for people to keep track of everything SLSA.

Any opinions one way or the other?

**Comment by dlorenc** [comment]
This got merged right?

**Comment by MarkLodato** [comment]
No, not yet finished:

* [ ] Update links to point to the new one, e.g. in-toto/attestations.
* [ ] Add redirects for all the pages in the old repo.
* [ ] Archive the old repo.

**Comment by dlorenc** [comment]
I see one issue that was closed: https://github.com/slsa-framework/slsa-controls/issues/3

I'm not sure we can really add redirects, does it actually matter? If a repo is "moved" you get automatic redirects, but I don't think we can do that for individual pages. Either way, it's early enough that I think we can just add a message at the top of the readme explaining where things were moved, fix incoming links that we know about, hit archive and call it a day. That repo doesn't have much attention yet anyway.

**Comment by MarkLodato** [comment]
Ah, yes, right about issues. I agree it's not a lot of work. Just needs to get done.

**Comment by MarkLodato** [comment]
Done.
