### ISSUE TITLE
Content help: '/Get started/Reaching Level 1/[Steps?]'

### ISSUE THREAD

**Issue by stevenif** [slsa-framework/slsa#242]
Hey all, politely requesting some guidance for new content we've got going into the Get started page.

There, we've got this section tailored for developers looking to jump straight in. So there's steps outlined, the requirements they'll need to take care of to achieve Level 1. It's aimed at being as low a barrier to entry as possible, as straightforward and actionable as possible. 

As per the screenshots below, we've broken out 'steps' from two central ideas, that:

1. you (developer) need to be building with a builder that generates provenance, and 
2. you need to make the provenance available to... 

And that ellipsis is where I'm stuck! 

Could we get a sense check on this content, what qualifies here? We've gone with something quite general and it's part vague instruction ("Decide where you'll store"), part value ("good for you and your users' workflows"), but if there's more specific, direct language we can use for this step, we'll get it in.

And if there's anything else glaring in the steps, if they seem accurate to point a developer to Level 1?

Thanks!
(looping in @devmoran @MarkLodato too)

![image](https://user-images.githubusercontent.com/87805086/145060367-f9549921-32d8-498e-b3b6-7a91e9892d80.png)

```
### Overview
This guide will help you achieve Level 1 and should take less than a couple of hours for an individual project. By following the steps, you'll soon be compliant with these SLSA requirements:
- Producing provenance data
- Automating your builds

### Steps
1. Read the Level 1 build and provenance requirements [link]
2. Choose a compliant version control system (if needed)
3. Choose a scripted build tool (if needed)
4. Create your provenance using the in-toto format (the Tools listed below can help)
5. Decide where you'll store the signed provenance so you and your users can easily build it into workflows
6. You're Level 1! Add the SLSA Level 1 badge to your readme
 
### Tools
- GitHub Actions provenance generator [link]
- Azure DevOps provenance generator [link]
- Cosign for storing signed provenance [link]

```

**Comment by david-a-wheeler** [comment]
Instead of "Tools" can you say "Potential Tools"?

It's important that we separate the SLSA requirements from possible ways to meet the requirements. There's no requirement to use GitHub actions - or GitHub! - to meet the SLSA requirements.

**Comment by stevenif** [comment]
@david-a-wheeler perhaps a good solution for making that super clear - and giving it full focus and explanation - is if I rewrote the final line of the Overview intro for this entire module? So something like:

`This guide will help you achieve Level 1 and should take less than a couple of hours for an individual project. [By following the steps, you'll soon be compliant with these SLSA requirements:]`

`This guide will help you achieve Level 1 and should take less than a couple of hours for an individual project. The tools listed are optional resources for demonstration and context-specific guidance:`

(where instead of "platform-specific guidance", "context" = the most appropriate word to cover platforms and everything else that might be added here in the future?)

**Comment by david-a-wheeler** [comment]
@stevenif - sounds great!

**Comment by MarkLodato** [comment]
My suggestion is to simplify the instructions to something like:

1. If you do not already use a build service or CI/CD, we recommend you set one up. This is not strictly required but it makes the following steps easier and is needed for higher levels. Consider using a service that is supported in the next step.
2. Generate [provenance](https://slsa.dev/provenance) during your build. The following tools might be useful. If your build service is not listed here, consider creating a plugin to generate provenance.
    - github actions demo (SLSA 1)
    - Azure pipelines demo (SLSA 1)
    - [Google Cloud Build](https://cloud.google.com/build/docs/securing-builds/use-provenance-and-binary-authorization) (SLSA 2)
    - ...etc...
3. Make the provenance available for your customers. We do not yet have a standard convention for this, but we expect to develop one over time as SLSA becomes more popular and we get more experience.

**Comment by devmoran** [comment]
Great, we'll roll with this for the release and can iterate from there. Thanks everyone.
