### ISSUE TITLE
Provenance: remove or clarify duplication between `configSource` and `materials`

### ISSUE THREAD

**Issue by AdamZWu** [slsa-framework/slsa#246]
In SLSA provenance v0.2 specification, there two separate places for build material references:
1. build entry point in `invocation.configSource`;
2. build materials in `materials`.

The examples presents the top-level source repo in both places, i.e. two identical copies of "uri" and "digest" tuples. However, some may find this duplication undesirable, as it could lead to inconsistencies.

Alternatively, could we adopt a no-duplication presentation, i.e. top-level source only appear in `invocation.configSource`, not again in `materials`? The downside is that the `materials` list won't contain *all* build materials.

Please clarify. Thanks~

**Comment by MarkLodato** [comment]
What do you think about the current design? There is still some duplication, but not the digest. Example: https://github.com/slsa-framework/slsa/blob/main/docs/github-actions-workflow/examples/v1-rc1/example.json

```json
            "externalParameters": {
                "workflow": {
                    "ref": "refs/heads/main",
                    "repository": "https://github.com/octocat/hello-world",
                    "path": ".github/workflow/release.yml"
                }
            },
            "resolvedDependencies": [
                {
                    "uri": "git+https://github.com/octocat/hello-world@refs/heads/main",
                    "digest": { "sha1": "c27d339ee6075c1f744c5d4b200f7901aad2c369" }
                }
            ]
```

**Comment by MarkLodato** [comment]
Yes, that is correct.

**Comment by AdamZWu** [comment]
Cool, I am happy with the change in SLSA v1.0. Feel free to close this thread~
