### ISSUE TITLE
Consider using Netlify for hosting

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#266]
To make pull requests easier to review, I think we should consider setting up [Netlify](https://netlify.com).

* At a minimum, we can use a free personal account to enable automatic pull request previews. It's a really nice feature. For example, see https://github.com/MarkLodato/slsa/pull/14 (https://deploy-preview-14--marklodato-slsa.netlify.app/). This requires granting the Netlify app write permission to issues and PRs (but not commit access) so I'd like approval from @slsa-framework/slsa-steering-committee before doing this.

* We can also consider switching our hosting to Netlify instead of GitHub pages. This would have some fairly minor benefits, mostly making [redirects](https://docs.netlify.com/routing/redirects/) easier and allowing other templating engines (or custom Jekyll plugins) without a custom GitHub Actions setup. The cost would be to reconfigure our DNS. Not sure it's worth the effort.

* Finally, we could apply for a free [open source plan](https://www.netlify.com/legal/open-source-policy) if we put a Netlify blub on the homepage or footer.

Personally, I think we should start by enabling the PR previews and see if that's sufficient. I'd be the only admin since we don't have a paid (or open source) plan, but that is probably good enough for preview purposes.

Thoughts?

----

Tasks:

* [x] Configure building of slsa.dev on Netlify (https://slsa.netlify.app)
* [x] Transfer ownership to a Team under the [Netlify Open-Source plan](https://www.netlify.com/legal/open-source-policy)
  * [x] Add “This site is powered by Netlify”, and include a link back to the Netlify home page, or use a [premade badge](https://www.netlify.com/press/#badges).
  * [x] Fill out the [form](https://opensource-form.netlify.com/).
  * [x] Configure the new team (https://app.netlify.com/teams/slsa)
  * [x] Transfer ownership of slsa.netlify.app to the new team
  * [x] Set up access control for project maintainers and OpenSSF admins
* [x] Point slsa.dev domain to Netlify
  * [x] Any prerequisites?
    * Looks like switching is not seamless due to the delay in provisioning Let's Encrypt certificates. Need to figure out how to not drop traffic.
  * [x] Ask David A. Wheeler to ask LF to update the [DNS settings](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/) once it's ready.
* [ ] Set up warnings and playbooks
  * [x] Write documentation for how to maintain the site
  * [ ] Ensure that warnings get sent to an appropriate mailing list in the case of reaching the free plan limits
  * [x] Write playbooks for how to respond in case we hit the free plan limits: who to contact, how to respond, etc.

**Comment by trishankatdatadog** [comment]
> Thoughts?

Love Netlify, we use it for https://github.com/theupdateframework/theupdateframework.io

**Comment by MarkLodato** [comment]
Since I have one +1 and no objections, I'm going to set it up to use my personal starter account for now. If we like it, we can consider going further and perhaps getting an open source license.

**Comment by MarkLodato** [comment]
OK, it's set up. See https://slsa.netlify.app.

There is one bug: the "View source on GitHub" link is broken due to https://github.com/jekyll/github-metadata/issues/208: Netlify doesn't set a git remote in the clone for some reason, so the github-metadata plugin doesn't know what branch (`main`) and path (`/docs`) were used. Netlify does, so I think we can work around this through some netlify config, e.g. passing in parameters to the build, but for now it's good enough. Another solution would be to hard-code the link, but I'd prefer not to do that to allow previews of PRs/forks to work correctly.

**Comment by MarkLodato** [comment]
Since there is no objection, one +1 from @trishankatdatadog, and front-page breakage caused by GitHub Pages (#311), I'm going to proceed with this change. I'll update the top comment with tasks.

**Comment by jorydotcom** [comment]
Hello! Yes, feel free to assign. I will put this on my task list for next week! ty!

**Comment by MarkLodato** [comment]
Friendly ping. Is the plan to use an existing OpenSSF Netlify account, or to apply for a new SLSA one under the open source program?

**Comment by MarkLodato** [comment]
OpenSSF does not have an account. I will apply for an open source plan once #447 is submitted.

**Comment by MarkLodato** [comment]
One issue with Netlify is that there is no cap on billing. If we exceed a build time or bandwidth limit, we're on the hook for charges. There are stories of people having to pay in the case of DDoS attacks (bandwidth) or malicious PRs (build minutes).

From my research and testing, here are the four main options:

- [Netlify](https://www.netlify.com/): Best overall, but has this billing risk
- [Cloudflare Pages](https://pages.cloudflare.com/): Pretty good has server-side analytics (bonus), but lacks PR previews (which we use extensively) and general polish.
- [Vercel](https://vercel.com/): Lacks teams on the free plan, which is a deal breaker.
- GitHub Actions + GitHub Pages: We set up GitHub Actions to build and push to the gh-pages branch. Lacks PR previews and is generally much more work to maintain.

We could continue to use Netlify for PR previews but switch to Cloudflare Pages for hosting. I don't love that option because then we have two setups to maintain and they can get out of sync.

Overall I still recommend sticking with Netlify, and I confirmed with Brian from OpenSSF that this is an OK path. In order for us to do this, we need to have clear documentation on the setup, warnings for reaching quota, and playbooks for how to respond to these quota issues. I'll add these tasks to the top post.

**Comment by MarkLodato** [comment]
The site is currently broken on the "production" Netlify deployment (https://slsa.netlify.app) but not deploy previews (https://deploy-preview-426--slsa.netlify.app/). It also works fine when built locally and on GitHub Pages (https://slsa.dev).

Thankfully, Netlify made it easy to narrow down the culprit:

* 413688d: [works](https://62e13a4100827000090ca0aa--slsa.netlify.app/)
* 71bf46d: [failed to build](https://app.netlify.com/sites/slsa/deploys/62e13a63315b450009eed585)
* cbd777d: built but [broken](https://62e148e5d6347e0008b48158--slsa.netlify.app/)

Note that the bad pages are using a site baseurl of "/pages/slsa-framework/slsa/" instead of "/".

From the commit, I guessed that it was the netlify.toml file. Removing the file [fixed](https://62e962f428e78400082b7a85--marklodato-slsa.netlify.app/) the build (on my fork). Further debugging showed that the issue was the "context" section in the file. Removing just that section also fixed the build. I'll send out a commit to address.

**Comment by MarkLodato** [comment]
Update: The switch is now in progress. Amanda Martin at OpenSSF just filed the ticket. Requested changes:
- `slsa.dev ALIAS apex-loadbalancer.netlify.com`
- `www.slsa.dev CNAME slsa.netlify.app`

I don't know when the switch will happen, so we'll have to be aware in case there is an issue.

One potential change is that because we are using LF's DNS servers instead of Netlify DNS, it won't use the geo CDN thing. We'll have to see if this is a problem in practice or not.

**Comment by MarkLodato** [comment]
Change is now live! There was sadly some temporary downtime due to a chicken-and-egg SSL certificate problem (need to change DNS settings *before* let's encrypt will issue a cert...) but now it seems to be working.

Remaining work is to document the new setup and clean up the old GitHub Pages configs.
