### ISSUE TITLE
Does SLSA compete or complement with Open SSF ("https://github.com/ossf")? there seem to be some overlap

### ISSUE THREAD

**Issue by nathanawmk** [slsa-framework/slsa#272]
Does SLSA compete or complement with Open SSF ("https://github.com/ossf")? there seem to be some overlap between both projects.

**Comment by dlorenc** [comment]
SLSA is part of the OpenSSF! You can see the exact details on the README here: https://github.com/slsa-framework/slsa#joining-the-working-group
