### ISSUE TITLE
Relationship between resources and artifacts

### ISSUE THREAD

**Issue by stepro** [slsa-framework/slsa#31]
(Upfront disclosure: I'm an engineer at Microsoft who is starting to look into supply chain security and I'm reaching out with some of my personal thoughts and opinions; I am not representing Microsoft as a whole).

Resources as friendly, non-content-based identifiers are assumed mutable. This tells me that what artifact a resource links to could change over time. Furthermore, I assume there may be multiple resources that point to the same artifact. For instance, the alpine image on Docker Hub currently has tags 3.13.5, 3.13, 3 and latest that all point to the same underlying image sha.

In the curlimages/curl example provided it looks like the build information (and thus attestation) is tied to the artifact via the resource, but if the resource changes which artifact it points to, the attestation would no longer be valid.

Would it make sense for builds to link directly to artifacts and pull resources out to the side as independent, friendly identifiers of artifacts (that can be updated over time)? Or was this the intent and I'm reading too much into what the implied model is from the diagram?

I appreciate the great work done here so far!

**Comment by MarkLodato** [comment]
Thanks, Stephen! Your understanding is correct. I agree that the diagram should be updated. To clarify, you are only suggesting an update to the diagram but not to the actual content / concept?

**Comment by stepro** [comment]
The concepts and separation of artifact and resource make sense to me. Clarity in the diagram would be great to indicate the relationship from a build goes straight to the artifact, with the resource independently pointing to the artifact. It might be as simple as switching from this:

```
artifact
   ||
resource
   ||
 build
```

To this (directed arrows might help as well):

```
resource
   ||
   vv
artifact
   ^^
   ||
 build
```

Additionally, depending on how specific you want to be, the 1-* relationship between artifact and resource could be called out more explicitly in the content, perhaps with some examples like "curlimages/curl:latest" and "curlimages/curl:7.72.0" both currently point to the same immutable image layer.

With this clarification, looking back at the initial definitions of "resource" and "artifact", it technically means the resource is no longer what's being protected; the artifact, i.e. the actual content, is where the supply chain is, and one or more resources may reference the artifact, solely representing the means for consumers to get at the artifact. Would this tweaking of the initial definitions make sense as well?

I'd be happy to open a PR with suggested changes we can iterate on - let me know if that sounds good to you!

**Comment by MarkLodato** [comment]
Yup, that was my thought as well. PR is welcome!

Unfortunately the diagram is in Lucid Charts because I couldn't find a decent text-based diagram tool. If you'd like to edit it, email me (lodato@google.com) and I'll share it with you.

See also #6.

**Comment by MarkLodato** [comment]
We decided to remove the notion of "resource" from SLSA altogether. I'm working on an update now.

**Comment by stepro** [comment]
Sounds good. I got distracted by other things so didn't spend a lot of time working on an update of my own. Interested to see where things are landing. Feel free to close out this issue if it no longer applies.

**Comment by MarkLodato** [comment]
I'll use this issue to remove the word "resource." :-)
