### ISSUE TITLE
Bug: event-stream link 

### ISSUE THREAD

**Issue by sergiomarotco** [slsa-framework/slsa#314]
Link [event-stream](https://schneider.dev/blog/event-stream-vulnerability-explained/) in text is wrong.
[event-stream](https://schneider.dev/blog/event-stream-vulnerability-explained/): Attacker added an innocuous dependency and then later updated the dependency to add malicious behavior. The update did not match the code submitted to GitHub (i.e. attack F).

The Host is not resolvable.

**Comment by joshuagl** [comment]
Thank you for reporting! It looks like that site has gone down and is unlikely to come back. We could point to an archived [copy on the WayBackMachine](https://web.archive.org/web/20210909051737/https://schneider.dev/blog/event-stream-vulnerability-explained/). Or update the link to point to either the [npm report on the incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) or some other analysis [such as Snyk's](https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor/).
