### ISSUE TITLE
Document software attestations model and rationale somewhere more official

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#323]
The SLSA [software attestations](https://github.com/slsa-framework/slsa/blob/main/controls/attestations.md) document is referenced by the [provenance format](https://slsa.dev/provenance/v0.2) specification (and in future the VSA format specification #285), but is not part of the official documentation (not rendered as part of slsa.dev).

We should officially document SLSA Software Attestations as part of slsa.dev

_Originally posted by @joshuagl in https://github.com/slsa-framework/slsa/pull/285#discussion_r809073960_

**Comment by TomHennen** [comment]
Do you have any thoughts about where to link to it from slsa.dev?  #285 provides the content but doesn't actually set up any links either.

Maybe turn the top-level 'Provenance' thing into 'Attestations' and then link to all three from a menu there?
