### ISSUE TITLE
Backdoor in node-ipc?

### ISSUE THREAD

**Issue by sergiomarotco** [slsa-framework/slsa#325]
Check https://github.com/vuejs/vue-cli/issues/7054

looks like a very exciting investigation, might the links to the list of threats for your project come in handy?

**Comment by sergiomarotco** [comment]
https://github.com/search?q=Y291bnRyeV9uYW1l%22%2C+%22base64%22&type=issues

**Comment by trishankatdatadog** [comment]
Is this political noise?

**Comment by 06kellyjac** [comment]
It's essentially malware that rewrites files on people's machines and it's introduced via dependencies

`@vue/cli` -> `@vue/cli-ui` -> `node-ipc` -> `peacenotwar`

![image](https://user-images.githubusercontent.com/9866621/158664939-67c040fc-acf1-4fa3-8629-841ce99afed2.png)

I think this is better moved to #222

**Comment by msuozzo** [comment]
@trishankatdatadog what do you mean? this seems like a good example of supply chain compromise (specifically resulting from not locking dependencies) that we can publicize as a rationale for SLSA's requirements.

**Comment by trishankatdatadog** [comment]
> @trishankatdatadog what do you mean? this seems like a good example of supply chain compromise (specifically resulting from not locking dependencies) that we can publicize as a rationale for SLSA's requirements.

That issue had no clear summary whatsoever from a quick glance. I'd rather focus on adding one line about this in #222 and calling it a day. Otherwise this issue/repo risks turning into a political discourse.

**Comment by msuozzo** [comment]
Nothing in this thread would lend me to believe that this would involve a political discussion. Neither the introductory post nor the linked thread. A substantial number of the other supply chain attacks have also involved geopolitical conflict yet we still design systems to make things more secure.

**Comment by trishankatdatadog** [comment]
> Neither the introductory post nor the linked thread.

Have you fully read the linked thread?

I'm not opposed to mentioning the incident without going into who supports/opposes the war.

**Comment by nm17** [comment]
@trishankatdatadog More detailed breakdown of it here: https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c

**Comment by 06kellyjac** [comment]
snyk has a good breakdown now too: https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

@sergiomarotco when you get a moment can you add a link related to this to #222 and close this issue

**Comment by sergiomarotco** [comment]
i add, check please

**Comment by 06kellyjac** [comment]
yep, that's great thanks. I can't close issues so if you or someone else could that'd be great
