### ISSUE TITLE
Require specific provenance format?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#33]
Right now SLSA does not require the provenance to be in a particular format. The intention is that some companies (like Google) may may have a purely internal SLSA implementation that is not interoperable. We want that to still be called "SLSA 3" even if it can't be checked outside.

That said, we want the format to be interoperable. Maybe we say that it needs to be a particular format within a closed ecosystem, and within the "internet" ecosystem we require in-toto attestations?

Might as well lump PKI into this.

**Comment by MarkLodato** [comment]
Reason for doing this: generating multiple types for multiple consumers would be a mess. A single format is very valuable to the ecosystem.

**Comment by MarkLodato** [comment]
Related question: Are there requirements about visibility, or is it OK for it to be hidden from everyone but the producer and consumer platforms? For example, if <cloud company> implements a vertically integrated solution that hides provenance from the customer but otherwise prevents supply chain integrity attacks, does it meet SLSA?

**Comment by dlorenc** [comment]
I don't think we should really "pick" formats in SLSA at this level. We could link to a few well-known and commonly used ones for cases like this.

**Comment by MarkLodato** [comment]
We now recommend in-toto but do not require it.
https://github.com/slsa-framework/slsa/blob/main/build-requirements.md#available
