### ISSUE TITLE
0.2: Replace "non-falsifiable" with a more accurate term

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#332]
The term [non-falsifiable](https://en.wikipedia.org/wiki/Falsifiability) is used incorrectly in the SLSA requirements. "Falsifiable" means that a theory can be proved false though some test, which is actually a good thing. What we actually mean is "non-forgeable," though perhaps there is an even better term. Any suggestions? (Note: This is also somewhat related to #261.)

I suggest that we wait until v0.2 to change the term, since doing so will break existing references.

**Comment by MarkLodato** [comment]
Once it's decided to change, we could add a note to v0.1 noting this misuse of the term.

**Comment by david-a-wheeler** [comment]
The scientific meaning of falsifiable is "capable of being disproved through experiment". The meaning intended here is "incapable of being undetectably false", which is a plausible meaning of the word but isn't what will come to mind to many.

Perhaps "non-forgeable" or "verifiable" are better terms?
