### ISSUE TITLE
Unclear how SLSA would help with the SolarWinds attack

### ISSUE THREAD

**Issue by Hixie** [slsa-framework/slsa#34]
The SLSA document says:

> * Attack any of the systems involved in the supply chain, as in the SolarWinds attack.
>
> SLSA intends to cover all of these threats.

It's not clear to me how the proposed model would help in cases like the SolarWinds attack. For example, suppose an open source project uses Travis CI to build their binaries, and Travis CI's infrastructure is infiltrated in a manner similar to the SUNBURST hack: how would the open source project detect it? Short of having actual verified reproducible builds using a different CI, we could never trust that the binaries built by this open source project are correct, could we? (The SLSA document says "SLSA does not require verified reproducible builds directly".)

But even if we did have two CI systems building the code of this open source project, say both Travis CI and Cirrus CI, what would stop an attacker from compromising both? Surely then even verified reproducible builds wouldn't help?

**Comment by MarkLodato** [comment]
Totally agree that the doc does not make it clear, and we intend to better explain this. What follows is a hasty blurb.

The thinking is that we trust a small number of hardened **platforms** to avoid having to trust thousands of individual projects/users. It is very hard and expensive to lock down a build system sufficiently to protect against nation-state actors, and few organizations have the resources, skill, and priorities to do so. I won't comment on the security of Travis CI or Cirrus CI, but my biased view is large organizations like Google (my employer) are sufficiently resourced to protect against these threats. Thus, it's much harder to attack Google Cloud Build than it is to attack a random open source project.

Verified reproducible builds are another possibility. You can theoretically assemble a more secure "platform" out of several less secure pieces. What is stopping an attacker from compromising both is cost and risk of detection. If the N individual builders are independent, then the attacker has to perform N attacks and then coordinate among them. If they screw up and they do not properly compromise all, then they risk detection.

I know that's not a perfect answer, but hopefully it's a start.

**Comment by Hixie** [comment]
That makes sense (and is similar to what @david-a-wheeler suggested in #5). Thanks.

**Comment by MarkLodato** [comment]
Agreed. I just filed #42 to document this more generally. I'll mark this one as a duplicate.
