### ISSUE TITLE
Is the event-stream attack style in scope of SLSA?

### ISSUE THREAD

**Issue by Hixie** [slsa-framework/slsa#35]
It's tempting to think the attacks like the event-stream incident could be avoided by requiring all one's dependencies to be SLSA3-compliant, but I wonder if it is the intent of the SLSA document to make that claim.

The event-stream incident happened because the previous maintainers handed over control to a new team. As it happens, there was only one maintainer in the first group and only one in the second group, but it seems like it would be reasonable to imagine a situation where event-stream had two maintainers (as would be required to be SLSA3-compliant), both of which would be happy to hand over the reigns to a new team, which could easily consist of two collaborators. In this situation, wouldn't the same attack as affected event-stream users still work?

The downstream users of the package, when rolling their dependency, would do their due diligence, see that there was a new team in place, verify that they are still operating as a SLSA3-compliant team, and miss that the team's values have changed.

**Comment by joshuagl** [comment]
My understanding is that event-stream like attacks are outside of the scope of the SLSA, but definitely interested in hearing the author's thoughts.

**Comment by MarkLodato** [comment]
It depends on what you mean by the [event-stream attack](https://schneider.dev/blog/event-stream-vulnerability-explained/).

If you mean malicious changes to source code, which includes adding a malicious dependency, then the only protection from SLSA is the two-person review of SLSA 3. As you stated, this is far from perfect, and SLSA probably wouldn't help.

However, it sounds like event-stream NPM include malicious code that was not present in the upstream repo. That is **precisely** the attack that SLSA is intending to protect against.

**Comment by Hixie** [comment]
I mostly meant the way event-stream's erstwhile maintainer handed off the project to a hostile maintainer, but you're right that there were other, more SLSA-relevant, aspects of that attack.

It would be useful for the SLSA docs to be more explicit about the kinds of attacks that are considered out-of-scope, so that potential adopters (who aren't security experts themselves and are using SLSA as a proxy for expertise) could have a better understanding of what other problems to consider. For example, if a dependency turning hostile is explicitly not in scope, then a potential SLSA-adopter may consider regularly auditing dependencies or using dependencies with more safeguards against that problem. If it's out of scope but not explicitly listed then we may not think of such things. :-)

**Comment by MarkLodato** [comment]
Agreed. I just filed #42 to document this more generally. I'll mark this one as a duplicate.
