### ISSUE TITLE
Define "trusted control plane"

### ISSUE THREAD

**Issue by bobcatfish** [slsa-framework/slsa#367]
Another phrase which occurs a few times [in the SLSA requirements](https://slsa.dev/spec/v0.1/requirements) but is not clearly defined (or I haven't found the definition!) is **trusted control plane**.

It would be very useful to have this clearly defined in [the SLSA terminology](https://slsa.dev/spec/v0.1/terminology), especially how it could apply to different systems, for example this phrase would likely mean something different for GitHub Actions which is hosted and has complete control over the control plane vs. for something like Tekton where the trusted control plane depends on how Tekton is configured and also may include components such as [Tasks](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md)

(More context available in [SLSA + Tekton: Case Study](https://docs.google.com/document/d/12yYP0M_zz5Tc9ftGnLwhDZ_tdZBq4mEod70ngWtHmLs/edit#) - particularly [the section around what trusted control plane could mean for Tekton](https://docs.google.com/document/d/12yYP0M_zz5Tc9ftGnLwhDZ_tdZBq4mEod70ngWtHmLs/edit#bookmark=id.jiiws37hhbri) - the doc is visible to anyone in mailing list slsa-discussion@googlegroups.com ).

**Comment by marcelamelara** [comment]
+1 to resolving this for v1.0.

**Comment by kpk47** [comment]
This may have been addressed by https://github.com/slsa-framework/slsa/pull/568.

**Comment by MarkLodato** [comment]
This can be further clarified because requirements.md says "trusted control plane" without linking to a definition. Simple solution is to link to the corresponding page in verifying build systems.
