### ISSUE TITLE
Are SLSA levels self-assessed ?

### ISSUE THREAD

**Issue by sbs2001** [slsa-framework/slsa#371]
SLSA noob here, so maybe it's a stupid question.

From reading the docs I didn't see a tool which could help with determining the SLSA level of some project. So I want to know whether folks just compare their project state with SLSA spec and determine their SLSA level.

**Comment by tmsteen** [comment]
I am not sure there is a tool that would provide enough coverage to provide an automated assessment in a broad sense. That being said, the requirements are much more detailed that you see from frameworks like the NIST CSF of CIS Controls. 

Another option is to have an external entity attest to the alignment against SLSA requirements is self-assessment is not rigorous enough.

**Comment by nris-jingu** [comment]
You may see the compliance matrix by DevOps tool vender. It seem to help self-assesment.

https://about.gitlab.com/solutions/supply-chain/

I think that it's difficult to assess automatically.

**Comment by mlieberman85** [comment]
Sorry, this issue appears to have fallen through the cracks there. So currently SLSA is self assessed, however there is nothing to stop a third party audit firm  or tooling to do the assessment for you. It's up to the consumer though to validate those certification. e.g. if audit person X says that your automated assessment done via tool Y is suitable for SLSA 3 builder certification then the end user would validate those identities and the attestations being made.

@krol3 Chain-bench is great and definitely one of the tools we've been using to hit some of the CIS stuff for another OpenSSF tool Frsca which should be SLSA compliant and also an implementation of the CNCF's secure software factory ref arch. It would be cool though to also include SLSA requirements in the chain-bench benchmarking tool as well.

**Comment by krol3** [comment]
@mlieberman85 I opened an issue, please add your comments about this topic. https://github.com/aquasecurity/chain-bench/issues/63
