### ISSUE TITLE
VSA: should reference input attestations

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#387]
The Verification Summary Attestation should list the input attestations that it used as inputs to the decision. This gives us traceability and repeatability of the process.

I'm thinking something like:

```json
 "inputAttestations": [
    {
      "uri": "...(optional)...",
      "digest": { "sha256": "abcd1234..." }
    }
  ]
```

@TomHennen thoughts?

**Comment by TomHennen** [comment]
I think we'd need a compelling use case.

Some thoughts

1. It will make the VSA larger and some verifications might involve a lot of attestations.  I suspect we'll have storage limitations in some places where attestations are stored so this could be an issue.
2. Would it be a list of all the attestations _presented_ to the verifier or just all the attestations the verifier _used_ to make it's determination.
3. I wonder if this would add any significant latency to the verification itself?  The verifier will have to hash all the attestations they include in this list which could be non-negligible.

**Comment by joshuagl** [comment]
In the proprietary software case, the attestations would (should) still exist and therefore can be referenced in the VSA, even if they are not shared with the VSA consumer. Listing them even when not available is valuable for internal producers and consumers of the VSA at the VSA producing organisation and in the oft imagined scenario of third party auditors verifying claims.

**Comment by MarkLodato** [comment]
I was thinking this would be an optional (but recommended?) field. In cases where it's valuable, you can record it. In cases where it's undesirable, it's OK to omit.

**Comment by joshuagl** [comment]
Optional but recommended seems reasonable. I do think we should recommend inclusion.

**Comment by AdamZWu** [comment]
What is "inputAttestations[].uri" for? Who provides it?

If a policy verifier implementation does not fetch attestations (i.e. the callers are responsible for supplying all necessary attestations), I guess the caller is also responsible for providing the URIs for the attestations? I think that could create a tiny trust-escalation channel -- user-provided data (the URIs) without verification gets signed into a SLSA attestation produced by a trusted service.

The VSA already contains resource URI of the artifact. Could combining with the "digest" of the input attestation be sufficient for the purpose of locating the attestation?

**Comment by TomHennen** [comment]
Yeah, I think @AdamZWu makes a good point. It's very difficult to know what URI would actually be used and in many cases if we had a URI it could expose sensitive information that the VSA producer was hoping to protect.

I think auditing could likely be handled better by logging the data used to produce the VSA in some internal database (perhaps a transparency log).  Then all the data is readily available for those that actually need it, but doesn't increase the size of the VSA, doesn't expose potentially sensitive data, and doesn't introduce API complications (how to provide URIs for the attestations that were used).

**Comment by MarkLodato** [comment]
I don't know of a use case for `uri`. I'd slightly lean towards keeping it (but optional) to mirror the format of `materials` in Provenance, but I don't feel strongly.

If it's stored externally, how do we know that the logs actually apply to the VSA? Wouldn't we need to include some sort of hash in the signed VSA?

**Comment by TomHennen** [comment]
I talked some with @AdamZWu and I think we're both fine with this proposal as long as `inputAttestations` is optional.

@joshuagl WDYT about us including this in 0.2 and then taking it out of draft?

**Comment by joshuagl** [comment]
> @joshuagl WDYT about us including this in 0.2 and then taking it out of draft?

Works for me. There has been some discussion of VSA in recent spec meetings and I think the `inputAttestations` field is well motivated by those.
