### ISSUE TITLE
"Identifies entry point" provenance requirement appears redundant

### ISSUE THREAD

**Issue by eliaslevy** [slsa-framework/slsa#388]
PR #141 introduced a *Identifies build instructions* requirement at L1+ that states:

> If build-as-code is used, this SHOULD be the source repo and entry point of the build config

Meanwhile, the *Identifies entry point* requirement, which applies at L3+, states:

> The provenance identifies the “entry point” of the build definition (see build-as-code) used to drive the build including what source repo the configuration was read from.

The later is just a refinement of the former. The redundancy is somewhat confusing. It may be clearer if *Identifies entry point* were folded into *Identifies build instructions*, stating that for L3+ the build instructions must be identified using the build-as-code source report and entry point.

**Comment by shaunmlowry** [comment]
+1 on resolving for 1.0, even if the resolution is "this is fine as is"

**Comment by MarkLodato** [comment]
I'm going to mark this as fixed, since now there is no mention of "entry point" in the spec. Please reopen if this did not address the concern.
