### ISSUE TITLE
Provenance: more guidance and examples on customising and extending SLSA provenance in adoptions

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#396]
The spec is extensible by default, both by having several fields which are "arbitrary JSON object with a schema defined by `buildType`." (invocation.parameters, invocation.environment and buildConfig), and through the [parsing rules](https://slsa.dev/provenance/v0.2#parsing-rules) explicitly defining how to add extension fields:
> Producers MAY add extension fields using field names that are URIs.

It would be useful to adopters to provide some more guidance/examples around:
* how and where to include `buildType` specific fields
* How, and under what circumstances, to add extension fields
* publishing `buildType` specific schema

**Comment by joshuagl** [comment]
For examples, listing/linking to adoptions – public examples of systems that can generate SLSA provenance – might be a useful start?

Some I know of:
* Tekton via the Chains project: https://github.com/tektoncd/chains/blob/main/docs/intoto.md
* slsa-github-generator: https://github.com/slsa-framework/slsa-github-generator/blob/main/PROVENANCE_FORMAT.md

**Comment by MarkLodato** [comment]
@joshuagl Do you think anything more is needed here, given the v1.0 draft?

**Comment by joshuagl** [comment]
I don't think any more is required at this time. Provenance v1.0 has a good level of design rationale and guidance.
