### ISSUE TITLE
Dependency maintenance updates

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa#406]
As part of the development we're doing in https://github.com/slsa-framework/slsa-verifier and https://github.com/slsa-framework/slsa-github-generator, we need to keep our dependencies up to date.
We currently use dependabot, but it has some limitations. For example, we cannot update dependencies "in batch" and we need to LGTM each PR individually. This is time consuming.

There is an alternative: install https://github.com/apps/forking-renovate, which support "batched PRs", and only requires read permissions. I would like to install it on https://github.com/slsa-framework/slsa-verifier and https://github.com/slsa-framework/slsa-github-generator.

Installation can only be done by an owner of the slsa org. Can someone help?

**Comment by inferno-chromium** [comment]
Forking renovate is renovatebot with restricted perms (read only, no write). I know this is used actively in several orgs i know. I am fine with this. What do other @slsa-framework/slsa-steering-committee think ? Individual repos under slsa org can still choose whichever deps update solution they like (we recommend both of these in Scorecards), but for rapidly changing ones like slsa generator/verifier, renovate could be a better option.
