### ISSUE TITLE
Add threat model, in/out-of-scope attacks, and real-world examples

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#42]
Right now it is not clear what attacks SLSA prevents. Example issues: #34, #35.

Tasks:

* [x] Add a threat model diagram and list of attacks.
* [x] Explain what attacks are mitigated (and to what extent) at each level.
* [x] Explain what other threats remain that SLSA does not address.
* [x] Add real-world examples like SolarWinds, event-stream, Great Suspender, and CodeCov, along with how those attacks could have been mitigated with SLSA.

**Status update, 2021-11-15:** https://slsa.dev/threats exists but still has several TODOs. I'll leave this issue open as a reminder to finish it.

**Comment by MarkLodato** [comment]
Note: I gave a draft explanation in https://github.com/slsa-framework/slsa/issues/34#issuecomment-853363638 about how this would mitigate attacks like SUNBURST.

**Comment by joshuagl** [comment]
Looks like the threat model diagram and example of mitigated attacks was done for the blog post here https://security.googleblog.com/2021/06/introducing-slsa-end-to-end-framework.html 

It would be good to get these added to the repo here.

**Comment by MarkLodato** [comment]
The main page now has the list of example attacks from the blog post.

Next step is to add an exhaustive list of attacks. I started a draft in #92, but I'm not sure if it's helpful. Any feedback would be appreciated.

**Comment by joshuagl** [comment]
> The main page now has the list of example attacks from the blog post.

💯 
 
> Next step is to add an exhaustive list of attacks. I started a draft in #92, but I'm not sure if it's helpful. Any feedback would be appreciated.

I think that for many the real-world examples are most useful for conveying the value of SLSA.
If we do add the detailed threat model, it should be a separate document, like the detailed requirements. 

However, I too am not sure how helpful the detailed threat model is. We already have mitigations proposed in form of the requirements. The levels indicate priority for implementing said mitigations.

**Comment by MarkLodato** [comment]
**Status update, 2021-11-15:** https://slsa.dev/threats exists but still has several TODOs. I'll leave this issue open as a reminder to finish it.
