### ISSUE TITLE
Consider removing "optional" requirements

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#423]
Feedback received from a customer: the "optional" requirements add confusion because it's not clear how to use them. If they are optional, why are they listed as requirements at all? And why are they listed as optional for some levels but not all?

For v1.0, I think we should consider whether they continue to make sense in the spec. If the intent is to nudge or recommend things, perhaps there's a more clear way to do it?

**Comment by marcelamelara** [comment]
I assume by optional requirements, you mean the ones labeled with "O" on this page? https://slsa.dev/spec/v0.1/requirements

Source requirements aside, there are two optional requirements "Reproducible" (Build reqs), which only applies to L4, and "Includes Metadata" (Provenance reqs), which is indeed rather vague. 

I'm inclined to recommend removing the Includes Metadata requirement from 1.0 entirely. The stated intent currently is "The provenance includes metadata to aid debugging and investigations." which seems orthogonal to SLSA's main goal of enabling trust decisions. And, any effort to define requirements around including additional metadata would likely end up replacing this general "Includes Metadata" requirement in any case.

**Comment by shaunmlowry** [comment]
+1 on resolving for 1.0.  If they're optional at a given level, we should just push them up a level and make them mandatory, even if that means having a level 5 :)

**Comment by marcelamelara** [comment]
@shaunmlowry Good point. For optional requirements that apply to a specific level, I think it makes sense to bump them up to the next level. As an aside, I can think of other build requirements in addition to "Reproducible" (e.g., run your builder on attested hardware) that would fit into a L5.

The "Includes Metadata" common requirement, specifically, is currently optional in all L1-4, so if we want to pin it to a specific level for 1.0, the meaning of this requirement needs to be made more precise.

**Comment by MarkLodato** [comment]
Let's decide this for v1.0. Suggestion for the two optional build requirements:

- Reproducible: Move this to the list of "possible future requirements" that will house the existing SLSA 4 requirements (since v1.0 will not define a Build L4.) The purpose of this "optional" requirement was more to guide readers that that is an ideal future state, and I think that will serve this purpose.
- Includes Metadata: Remove it from the requirements and instead:
  - In the provenance spec, have more clear guidance on how to progressively implement, which fields are more important and map to what level, etc. (Related: #425). Here we can recommend but not require this extra metadata.
  - In the Build requirements, suggest using SLSA provenance unless there is a reason to do so otherwise, and recommend using the same fields.

**Comment by joshuagl** [comment]
Great discussion and suggestions, I like the suggestions for 1.0.

**Comment by MarkLodato** [comment]
I believe this is now addressed.
