### ISSUE TITLE
Provenance v1.0

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#460]
This issue is for tracking and building consensus on what will go in the next version of the provenance spec, tentatively called v1.0.

### Current proposal

[Schema changes](https://github.com/slsa-framework/slsa/issues?q=is%3Aopen+is%3Aissue+label%3Aspec-change+label%3Aprovenance):

- #349
- #246 
- #401
- #319 

[Documentation changes](https://github.com/slsa-framework/slsa/issues?q=is%3Aopen+is%3Aissue+label%3Aclarification+label%3Aprovenance+):

- #353 
- #350
- #397 
- #396 

Meta:

- #459

There is also a [milestone](https://github.com/slsa-framework/slsa/milestone/3), but it's not as useful because it does not show prioritization.

### Discussion

I initially populated the list with every every issue tagged as [provenance](https://github.com/slsa-framework/slsa/issues?q=is%3Aopen+is%3Aissue+label%3Aprovenance).

If you have any opinions on adding more things or removing some things, please comment on this thread.

**Comment by laurentsimon** [comment]
Do we want the provenance to have a URL to download the source code? AFAIK, a git history rewrite makes it hard to recover the source code for a particular commit. Wdut?

**Comment by laurentsimon** [comment]
Another thing worth discussing is the material section for all dependencies. Would it be acceptable to allow a sha256 of a corresponding SBOM generated by the untrusted build steps?

It provides different guarantees (it's forgeable), but would quickly allow the 2 standard to co-exist.

**Comment by laurentsimon** [comment]
A better option may be to use the SBOM as an additional subject, since it's an output of a build.

**Comment by MarkLodato** [comment]
Closing this as a duplicate of the #497
