### ISSUE TITLE
SLSA provenance generator for Jenkins

### ISSUE THREAD

**Issue by HyuckjunChoi** [slsa-framework/slsa#461]
As long as I know, even though a provenance can be generated by using CI/CD like Github-Actions and Gitlab CI, It seems there is no reference or best practice for Jenkins CI yet.

I also checked @MarkLodato's comment regarding several ways to generate provenance.(https://github.com/slsa-framework/slsa/issues/185#issuecomment-946733812)

So we, Samsung Research Security Team are creating the Jenkins plugin and a guide to generate the provenance with it.

I think our work would help the people who are starting and applying the SLSA to the Jenkins.

**Comment by HyuckjunChoi** [comment]
@mlieberman85, Yes, it is an open source. We just finished a draft version. Now we are working on testing a generator and creating a how-to guide.

And we are looking for a proper repository to contribute.
I think it would be better to create a repository in "github.com/slsa-framework" like the Azure DevOps SLSA provenance generator(https://github.com/slsa-framework/azure-devops-demo) to collaborate with others and to get reviews.
We would like to collaborate with people who are interested in the Jenkins SLSA provenance generator too.

Could you let me know the person who is charge of manage repositoires if you know?

**Comment by mlieberman85** [comment]
@HyuckjunChoi We chatted about this on Slack, but you have now created the plugin and would like to contribute it directly to SLSA. Can you link the plugin here in this issue?

@MarkLodato @joshuagl - what would the process be for deciding on whether or not to take in the Jenkins plugin directly into SLSA org?

**Comment by HyuckjunChoi** [comment]
@mlieberman85 Sure, this is the SLSA provenance generator for Jenkins. https://github.com/Samsung/slsa-jenkins-generator

**Comment by inferno-chromium** [comment]
@HyuckjunChoi @mlieberman85 - It will be great to add Jenkins support for SLSA generator/verifier. Process-wise, should just would need reviews from steering committee and other SLSA generator folks.

@asraa @laurentsimon @ianlewis - can help with reviews/validating integration.

**Comment by MarkLodato** [comment]
> @MarkLodato @joshuagl - what would the process be for deciding on whether or not to take in the Jenkins plugin directly into SLSA org?

I think if we have sufficient votes of @slsa-framework/slsa-steering-committee that would work. I'm OK with this.

**Comment by joshuagl** [comment]
I filed https://github.com/slsa-framework/governance/issues/17 to define and document a process and expectations.

**Comment by SaiJyothiGudibandi** [comment]
Is this going to be supported by SLSA? If yes, may I know the ETA?

**Comment by SaiJyothiGudibandi** [comment]
I tried that, but not working for me.
1. keypath/credential ID is not supported. Getting not found, even the credential or key is there in the provided path.
2. I am trying to push link metadata to the Rekor server or workspace as a provenance file.

**Comment by laurentsimon** [comment]
Thanks for reaching out. We're not super familiar with Jenkins ourselves. However we'd be willing to collaborate and help with design / code reviews / etc.

@HyuckjunChoi who wrote https://github.com/slsa-framework/slsa/issues/461 may have some ideas.

**Comment by SaiJyothiGudibandi** [comment]
@inferno-chromium

**Comment by inferno-chromium** [comment]
Sorry i have been slow on issues lately, but i am super excited to see https://github.com/slsa-framework/slsa-jenkins-generator

**Comment by joshuagl** [comment]
https://github.com/slsa-framework/slsa-jenkins-generator has been donated to the OpenSSF by Samsung and moved into the salsa-framework organisation. I think we are good to close this issue?

**Comment by inferno-chromium** [comment]
@HyuckjunChoi - can you write a short community blog on https://slsa.dev/blog about this new feature, how to use it and any potential projects that started using it ?

**Comment by HyuckjunChoi** [comment]
@inferno-chromium Thanks for your suggestion. I can write a blog on https://slsa.dev/blog about this feature and I think it is a good opportunity to announce the slsa-jenkins-generator.

**Comment by inferno-chromium** [comment]
> @inferno-chromium Thanks for your suggestion. I can write a blog on https://slsa.dev/blog about this feature and I think it is a good opportunity to announce the slsa-jenkins-generator.

Yes that would be great. It could be good to give some insights on future work / current limitations. Do you have any plans to achieve higher SLSA level compliance (non-falsifiable provenance ?) in Jenkins (via plugins or something).

**Comment by HyuckjunChoi** [comment]
> > @inferno-chromium Thanks for your suggestion. I can write a blog on https://slsa.dev/blog about this feature and I think it is a good opportunity to announce the slsa-jenkins-generator.
> 
> Yes that would be great. It could be good to give some insights on future work / current limitations. Do you have any plans to achieve higher SLSA level compliance (non-falsifiable provenance ?) in Jenkins (via plugins or something).

Yes I agree with you. Currently we are developing the jenkins plugin that would help jenkins users more easily generate provenance and we are also planning to develop the generator meets higher SLSA level requirements.
I think it would be better to include these plans on a blog.

**Comment by HyuckjunChoi** [comment]
@inferno-chromium I would appreciate it if you could let me know where I can upload a draft blog post. I think it is here, right? https://github.com/slsa-framework/slsa/tree/main/docs/_posts

**Comment by ianlewis** [comment]
@HyuckjunChoi That's the right place. You should be able to write the post for a future date and generate it with `jekyll --unpublished --future`

**Comment by HyuckjunChoi** [comment]
@ianlewis Thank you for your help.
