### ISSUE TITLE
[Specification SIG] Clarify/refine SLSA source requirements

### ISSUE THREAD

**Issue by marcelamelara** [slsa-framework/slsa#463]
As we work to clarify the intent and requirements for SLSA 1-3, several folks have suggested to revisit how source requirements are treated.

One suggestion is to more clearly separate the source requirements from the build requirements, possibly even defining separate source-specific SLSA tiers on top of a core set of SLSA requirements. The main reasoning behind this is that source management and build are not necessarily handled by the same entity, meaning that builders do not have insight into/control over the source management of a package they are building. A clearer separation may also help in identifying additional or more fine-grained source management requirements.

The goal of this issue to capture a set of recommended source requirements.

cc @melba-lopez @MarkLodato

**Comment by melba-lopez** [comment]
These are just a few items I think of when I think of source integrity and the system the houses code.  I don't think we need to duplicate what these frameworks state, but it is something to consider when designing for what SLSA requirements should be.  


 https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-218.pdf

![image](https://user-images.githubusercontent.com/101211710/183794584-dbb68d0f-e1a6-4e67-8f57-21d26afb7aca.png)
 
![image](https://user-images.githubusercontent.com/101211710/183795013-8d0a98d4-9bba-4c3c-b607-b5484eae2798.png)

![image](https://user-images.githubusercontent.com/101211710/183795504-3eac490b-e368-42d0-9341-396b2ff3d5d7.png)

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-161r1.pdf
![image](https://user-images.githubusercontent.com/101211710/183797158-6fdba26d-dd89-4cc7-946b-19149667be73.png)

![image](https://user-images.githubusercontent.com/101211710/183797437-a683c733-aa06-4dda-8d6a-6e5162704354.png)

![image](https://user-images.githubusercontent.com/101211710/183797894-a63e95e5-f1fb-42f5-b4fb-3f8deb29fea4.png)

**Comment by melba-lopez** [comment]
Here is what I've been working on.  This is currently still draft, but wanted to share with the team progress so far

![SW Supply Chain Security Brainstorming (16)](https://user-images.githubusercontent.com/101211710/185934960-c1f46920-7ddc-4d1a-81a6-5ccf52c6a68c.png)

@MarkLodato @marcelamelara @joshuagl   **(the case for separation of source vs build)**

**Comment by marcelamelara** [comment]
@melba-lopez These figures are really helpful, thank you for putting them together! I think they distill some of the major use cases for separating source repo integrity from build integrity. I have a couple questions.

Where do dependency sources fit into these figures? I'm thinking of two scenarios. 
(1) The builder pulls dependencies from npm at build time, and these dependencies might or might not include their own SLSA attestations.
(2) A git source repo includes one or more git submodules, some first- or third-party repos, each with different visibility settings.  
Given these scenarios, should integrity info about these dependencies, in both cases, be considered part of build or source integrity info? I think in the first scenario, including dependency info in the build integrity attestation makes sense. I'm a bit less clear about what the right thing to do is in scenario 2, where you have nested source repos that are built from source together with the parent source to produce a single artifact. What integrity info, if any could/should the parent source repo provide in scenario 2 about the submodules?

A few other clarifying questions: 
- For all the boxes that say "Trusted", who are those components trusted by?
- Should the deployment tools be attested as part of the source integrity? I would guess that deployment tools might be used in several different components of the the supply chain, including a builder. Do you have a specific use case in mind for including deployment tools under the source category?

**Comment by melba-lopez** [comment]
per hybrid meeting @camaleon2016 suggesting Jonathan meadows (from citi) to help with the oss/proprietary model that may answer some of these questions.  Awaiting diagram.

**Comment by marcelamelara** [comment]
Based on the Hybrid OSS/Proprietary meetings today and last month, two points have emerged out of these discussions: 
(1) developing the source management/repo SLSA requirements is necessary but warrants more time and careful consideration to get right, and 
(2) ensuring that the SLSA build requirements cover Hybrid OSS/Proprietary build workflows is a separate effort and should be prioritized for 1.0. 

@melba-lopez @MarkLodato Given this split and the focus on Build Levels for 1.0, do we think it would make sense to defer refining source management requirements until after 1.0?

**Comment by MarkLodato** [comment]
Agreed.

**Comment by shaunmlowry** [comment]
+1 on deferring this

**Comment by marcelamelara** [comment]
Per the Specification SIG meeting today, how should we mark this issue? Can we create a post-1.0 tag?

**Comment by MarkLodato** [comment]
Thanks @marcelamelara. I just moved it to a new "SLSA spec v1.1+" milestone and removed the maybe-1.0 tag.

**Comment by TomHennen** [comment]
So I think we can now close this bug?  We've removed source requirements from the build track, we're working on a separate source track.  I think the decision has been made?

**Comment by zachariahcox** [comment]
agree! marking closed for now.
