### ISSUE TITLE
Define provenance guarantees stronger than just top-level config but short of fully hermetic

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#466]
In [v0.1](https://slsa.dev/spec/v0.1/requirements), the jump between the provenance guarantees of SLSA 3 and SLSA 4 is very large:

- SLSA 3: only identifies the top-level build config (#465)
- SLSA 4: fully identifies all build inputs, i.e. "hermetic"

From #464, we discussed the value of defining something in between. @laurentsimon suggested the terms "first-stage" vs "second-stage" builder, and that thread has a bit more discussion about the idea. I can also see adding an intermediate level for this.

As a first step, we need to agree on a precise technical definition of what this difference would be. The reason for the two definitions in v0.1 is because those are two reasonable controls for a builder: record the location of the top-level config, and guarantee to some extent all build inputs. If we had some intermediate state, what would it be? How would a builder enforce that?

**Comment by MarkLodato** [comment]
From @kommendorkapten in https://github.com/slsa-framework/slsa/issues/464#issuecomment-1214692292:

> > What specific SLSA 3 requirement would that fail to meet, and why would using [generator_generic_slsa3.yml](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/generator_generic_slsa3.yml) make a difference?
> 
> I think the first-stage and second-stage builder is a great analogy to use here. For a first-stage/X.509 builder _any_ workflow/build definition that is "_verifiably derived from text file definitions stored in a version control system_" can be used. A SLSA level 3 attestation for these kinds of builders must bare-minimum (x509 cert + artifact digest), as I understand.
> 
> With a second stage builder, we can get richer attestations, as the provenance generation can be isolated from the source code repository, so we can now put more data into it without violating the "non-falsifiable" requirement.
> 
> While they are both SLSA level 3, the discussion boils down to the usability of them, and how to define policies. As policies most likely will be very different for e.g. a vendor, OSS and the enterprise use-case. I guess it would be hard to tighten up the language in the SLSA spec to accommodate the need for all? Would it be worth extending the spec on policies in SLSA (an appendix or similar), and talk more about how different builders may operate and so provide more guidelines for the downstream verifiers? And maybe talk more about different builders and what they actually attest to?

**Comment by joshuagl** [comment]
Ideologically, this feels related to #230

**Comment by joshuagl** [comment]
There's an intermediate between top-level config at SLSA L3 and hermetic at L4 captured in the [SLSA v1.0 proposal](https://github.com/slsa-framework/slsa-proposals/pull/7/files).

> we may want to decompose into Pinned (list of all build-time transitive dependencies is checked in to version control, including a cryptographic hash of each dependency that is verified before building) and Dependencies complete (builder guarantees that controls were in place to prevent use of build-time dependencies not listed in the provenance.)

**Comment by MarkLodato** [comment]
> Ideologically, this feels related to #230

Agreed. Let's mark this as a dupe.
