### ISSUE TITLE
Recommend use of jsonl files as out of band distribution mechanism for SLSA attestations?

### ISSUE THREAD

**Issue by mlieberman85** [slsa-framework/slsa#475]
The [generic SLSA github generator](https://github.com/slsa-framework/slsa-github-generator) uses jsonl files to distribute the SLSA attestations for arbitrary content. Does it make sense to recommend it as the pattern for file based distribution? With the OCI changes we now have a good model for how it should be distributed via OCI, there's different bundle formats being developed for NPM and other packages. I think the jsonl stuff is good generically, especially for stuff that doesn't natively support it.

@ianlewis Thoughts?

**Comment by joshuagl** [comment]
I expect that for many readers the suite of interrelated specs we recommend for implementing the attestation model is quite fuzzy and that it would be useful to provide more detail on how they all fit together. 

To the point of this issue, the in-toto attestation spec does specify using JSON Lines to store multiple attestations https://github.com/in-toto/attestation/blob/main/spec/bundle.md

We could flesh out the recommended suite section of the attestation model page?

Cc @TomHennen

**Comment by ianlewis** [comment]
I agree with @joshuagl. The specific format for jsonl is chosen primarily as a way to distribute multiple DSSE formatted attestations and the doc that @joshuagl linked to is probably the right place for it.

SLSA itself could potentially have a number of ways to attach and distribute a signature so I'm not sure that SLSA itself really cares about jsonl. That said it's pretty opaque how these formats fit together so more detail on that might be helpful somewhere.

**Comment by TomHennen** [comment]
I definitely like the idea of recommending the use of jsonl (but I'm biased).

@joshuagl you mean [this section](https://slsa.dev/attestation-model#recommended-suite)?  It already recommends JSON Lines.

Perhaps you're suggesting we should have some sort of diagram that shows how attestations are created throughout the process and how they move throughout the development->user pipeline?

I also agree with @ianlewis that jsonl isn't right for every case (as with OCI where there's already a solution).

**Comment by ianlewis** [comment]
I hadn't seen the [software attestation model doc](https://slsa.dev/attestation-model) that @TomHennen linked before and I think it addresses the original question that @mlieberman85 suggested. The set of recommended formats is good though I think these could potentially be mentioned in the other sections of the doc where they are most relevant. That might give readers a better idea about how the formats are used and where.

**Comment by mlieberman85** [comment]
Yeah, I hadn't seen that either that it's already recommended on the site.

@TomHennen the idea here would be to recommend a format + maybe a process like the diagram you're describing so folks know ways to distribute/verify attestations when OCI, or other mechanisms don't make sense or won't work. It would also be a stop gap for packaging tooling that doesn't have functionality or processes for built in distribution and ingestion of the attestations.

The goal for now would to be to reduce confusion in the community on how folks can distribute and ingest SLSA in ecosystems that don't natively support it yet.

**Comment by TomHennen** [comment]
That makes sense to me.

**Comment by joshuagl** [comment]
Apologies for the delayed response to this lively thread, I had a bit of PTO. The attestation model page is a recent addition based on some earlier work by Mark which lived outside of the site's content.

Reading through this thread, I think there's two main recommendations for improvements:
1. reference the recommended suite more throughout the docs (counter-argument, this may make the _recommended_ suite seem more like a requirement?)
1. add a diagram that shows how attestations are created throughout the process and how they move throughout the development->user pipeline?

I'm all in favour of 2 and would suggest filing a new issue for that and closing this issue, if there's agreement.

**Comment by mlieberman85** [comment]
I also support 2. I'll create the new issue
