### ISSUE TITLE
New badge icons are not propagated to the website 

### ISSUE THREAD

**Issue by godofredoc** [slsa-framework/slsa#480]
I landed a PR to add new SLSA badges for all the supported levels in https://github.com/slsa-framework/slsa/pull/479 but they don't seem to have propagated to the website. I was expecting to be able to get the icons from urls like https://slsa.dev/images/gh-badge-level2.svg in a similar fashion as https://slsa.dev/images/gh-badge-level3.svg.

Do I need to copy the badge images to a different place or is just a matter of waiting the new version of the website to be released on a predefined schedule?

**Comment by godofredoc** [comment]
\cc @laurentsimon

**Comment by inferno-chromium** [comment]
The reason it is not working is these are copied to the wrong dir. It needs to be moved under https://github.com/slsa-framework/slsa/blob/main/docs/images [site is deployed from docs/] and not https://github.com/slsa-framework/slsa/tree/main/resources/assets/badges. We should probably remove the all the badges from resources/assets/badges to avoid confusion.

**Comment by inferno-chromium** [comment]
https://slsa.dev/images/gh-badge-level2.svg works now, closing.
