### ISSUE TITLE
SLSA spec v1.0

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#497]
Tracking issue for the SLSA spec v1.0 release.

- To view the latest draft: https://slsa.dev/spec/v1.0
- To view all pending v1.0 issues, grouped and prioritized by objective, see [Specification v1.0](https://github.com/orgs/slsa-framework/projects/1/views/1) project.
- To read the original v1.0 design doc, see [SLSA v1.0 Proposal](https://github.com/slsa-framework/slsa-proposals/blob/main/0003/README.md).

Timeline:

*   [x] [Draft](https://slsa.dev/spec/v1.0): Still in development, with some things unfinished. Visible at URL above but not linked from the main site, with a warning banner saying that it is an unpublished draft version. PRs can be approved by a single reviewer to speed development. Does not yet represent broad consensus. During this phase we will address or defer all issues in the v1.0 milestone (except for process ones like this one).
*   [x] 2023-02-24: [Release Candidate 1](https://slsa.dev/spec/v1.0-rc1): Ready for broad review by the community. Linked from the main site but clearly marked as a release candidate.  The "v1.0-rc1" URL will remain static, while further development happens on the draft "v1.0" URL (which retains the banner). Announcement: https://slsa.dev/blog/2023/02/slsa-v1-rc
*   [x] 2023-03-24: End of RC1 comment period.
*   [x] 2023-03-31: Deadline to get in changes for v1.0. After this, we will freeze v1.0 to only minor fixes, no changes in meaning or significant content additions.
*   [x] 2023-04-03: Release Candidate 2 announced. This starts the mandatory two-week comment period as a "candidate for approved specification" as per our [governance](https://github.com/slsa-framework/slsa-governance).
*   [x] 2023-04-19: v1.0 marked "Approved" and announced, updated as the default version on the site.

Notes:

*   Previously we used a [milestone](https://github.com/slsa-framework/slsa/milestone/2) prior to adopting the project to track v1.0.
*   Previously we used the [maybe-1.0](https://github.com/slsa-framework/slsa/issues?q=is%3Aissue+label%3Amaybe-1.0) tag to track untriaged issues. No such issues exist any more, so we've deleted the tag.
*   [SLSA spec backlog](https://github.com/slsa-framework/slsa/milestone/4) is a milestone for any issues we decided to defer to a future v1.1 version or later.

**Comment by MarkLodato** [comment]
I propose the following guidelines for changes:

- By **Fri, March 31:** Get in all major changes before we cut RC1. Examples: schema changes, requirements changes, new pages, major layout changes

- Following two weeks (until final release): "quiet period" defer any non-urgent changes that could hamper a reader's ability to review
  - OK: trivial changes such as typo fixes or website changes
  - OK: pages outside the versioned directory (e.g. "How to SLSA")
  - OK: adding a What's New page (#592), which we likely won't finish by Friday
  - OK: high priority changes (better now than waiting for next release)
  - OK: minor clarity changes that are limited in scope and unlikely to be controversial
  - Discouraged: shuffling around content
  - Discouraged: significant changes in content that require community consensus

- After the release: go back to normal
  - Significant changes require several days to review, multiple approvals, etc.

Thoughts?

**Comment by Ajsiqosnsizidnswikw** [comment]
Ajjajajs
