### ISSUE TITLE
SLSA v1.0: reproducible builds should satisfy SLSA Build Levels

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#504]
The current wording states that a "hosted build service" is required. One way to implement this would be to have a system of reproducible builds where the original build happens anywhere and then some (hosted) rebuilders reproduce the build bit-for-bit and generate their own provenance. I want to make sure that the wording of the requirements makes it clear that this is an acceptable implementation. Right now I don't think that is clear.

**Comment by mlieberman85** [comment]
Do we also want to require or suggest that it should happen on a separate buildType? Based on some previous discussions there was potentially two things you could show via reproducible builds.

1. Build itself wasn't tampered with
2. Build service wasn't tampered with

This would mean like some build running on GHA and the same build running on Tekton running and producing the same output would be a good indicator that neither of the two services themselves have been tampered with.

**Comment by MarkLodato** [comment]
For this issue my intention was just a specification change to make it clear that reproducible builds is an acceptable implementation - i.e. that the original build need not be hosted.

I think a larger, separate issue is a set of recommendations for how to implement a secure build system and gain confidence that it's actually secure. A system of reproducible builds that log all of their actions so that people can cross-check results for a history of tampering could be a recommendation, but I vote that it's out of scope for this issue. I filed #505 for that.

Regarding buildType, my inclination is that that is out of scope for this issue?
