### ISSUE TITLE
Better define "package" and associated terminology

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#520]
Draft proposal: https://docs.google.com/document/d/1yHc3Bcq8fV5sthCcOhhQBd5UC6xfH9UV-NTry56ocD0/edit

Ideally this would be done in sync with the OpenSSF Best Practices WG, which is also defining similar terminology.

**Comment by joshuagl** [comment]
The draft proposal looks reasonable to me. I agree with the priorities of unambiguous and minimal think the proposal meets those priorities and the goal.

Further, the proposal mostly matches my mental model (from the Linux distribution world) and does not seem to contradict the [Package URL specification](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst).

The only thing which may be missing from the draft is the notion of a versioned package, which we might consider to be the human readable artifact name or package identifier. However, I can't convince myself that such a definition is necessary and thus, per the minimal priority, we should not define it. :-)

**Comment by MarkLodato** [comment]
> The only thing which may be missing from the draft is the notion of a versioned package, which we might consider to be the human readable artifact name or package identifier. However, I can't convince myself that such a definition is necessary and thus, per the minimal priority, we should not define it. :-)

My thoughts exactly. :-)

**Comment by MarkLodato** [comment]
> The only thing which may be missing from the draft is the notion of a versioned package, which we might consider to be the human readable artifact name or package identifier. However, I can't convince myself that such a definition is necessary and thus, per the minimal priority, we should not define it. :-)

My thoughts exactly. :-)

**Comment by joshuagl** [comment]
> Ideally this would be done in sync with the OpenSSF Best Practices WG, which is also defining similar terminology.

I couldn't find where this is happening, do you have any pointers? Has this draft document been shared with that WG?
