### ISSUE TITLE
ELI5: What is provenance and attestation?

### ISSUE THREAD

**Issue by wtfacoconut** [slsa-framework/slsa#521]
Appologies in advance if this is the wrong place to be asking this question, but I figured that question has the possibility in resulting in a update to the documentation for new comers to SLSA and supply chain security.

I'm pretty new to SLSA and the subject of Supply Chain Security (SCS) and there are two important key-terms that I see being used quite heavily (provenance and attestation), but I'm not sure that I understand the difference between the two.

For reference, I've been reading the docs for SLSA and [Sigstore](https://www.sigstore.dev/), which use the terms provenance and attestation, but I do not understand what they really mean and neither SLSA nor Sigstore really define what they mean. Do these terms refer to a data format, process, or something else?

If someone can provide a clear definition as to what an attestation is and what provenance is, and can explain how they relate to each other, I would greatly appreciate it. And since I feel like I'm already making an unreasonable requests, I'll also ask that you please explain it to me like I'm 5 years old, thanks!

**Comment by jspeed-meyers** [comment]
@wtfacoconut, I've had the same questions before. Using the FAQ in the Chainguard academy docs (full disclosure: I work at Chainguard):

[Attestation](https://edu.chainguard.dev/software-security/glossary/#attestation)
> An attestation allows consumers of a software artifact to verify the quality of that artifact independently from the producer of the software. It also requires software producers to provide verifiable proof of the quality of their software. You can think of an attestation as a proclamation that software artifact X was produced by Y person at Z time.

[Provenance](https://edu.chainguard.dev/software-security/glossary/#provenance)

> Provenance is the verifiable information about software artifacts describing where, when and how something was produced.

This definition comes from the SLSA definition of provenance [here](https://slsa.dev/provenance/v0.2).

Is that helpful?

**Comment by jspeed-meyers** [comment]
Perhaps attestation should be defined in the SLSA docs somewhere. I defer to @MarkLodato. Also, if someone disagrees with the above definitions, please speak up and no hurt feelings.

**Comment by wtfacoconut** [comment]
Hello @jspeed-meyers. Thank you for taking the time to provide these definitions and explain things to me.

I have a few follow up questions about these two things now.

- Right now my mental model is that an attestation is basically a cryptographically signed file that contains one or more provenance entries. There would be one provenance entry for my code/application and possibly other independent provenance entries about any other library or component that my app has a dependency on. Is my understanding correct? 
- How is attestation/provenance data tracked? By an organization? Is this when something like Sigstore gets used?

Thanks again!

**Comment by wtfacoconut** [comment]
Hello @jspeed-meyers. Thank you for taking the time to provide these definitions and explain things to me.

I have a few follow up questions about these two things now.

- Right now my mental model is that an attestation is basically a cryptographically signed file that contains one or more provenance entries. There would be one provenance entry for my code/application and possibly other independent provenance entries about any other library or component that my app has a dependency on. Is my understanding correct? 
- How is attestation/provenance data tracked? By an organization? Is this when something like Sigstore gets used?

Thanks again!

**Comment by mlieberman85** [comment]
We have been trying to focus on definitions from major standards bodies if possible. I believe our definition of provenance stems from NIST 800-53. There's been a ton of confusion in the space around definitions lately.

**Comment by jspeed-meyers** [comment]
@wtfacoconut, glad to help. This is a constant source of confusion.

On the attestation mental model: I think a more general mental model might be useful. An attestation is really just a claim by party X about software artifact Y. It doesn't have to be provenance-related. It could be that party X scanned artifact Y and a certain set of vulnerabilities was found. It's a very general notion.

And on how provenance is tracked: I think it's accurate to say that this is an open question. There's not a standard way. I suspect many individuals organizations have their own internal norms (though I suspect even this isn't widespread), but there's certainly no one practice or two that is widely agreed upon, yet. Sorry to have such a non-answer :)

**Comment by wtfacoconut** [comment]
Hey @jspeed-meyers . Thanks again for another infomative and useful response. I think I'm starting to understand things better now. It sounds like the state of Supply Chain Security is still very much in a state of flux, hence why there seems to be many people like me who get a bit confused.

I'll try my best to list off what I think I'm understanding now:
- Attestations are just a "claim" about "something". In the context of SLSA, it's _typically_ a claim by a developer on the security/quality of a piece of software. 
- SLSA has some tools to help in the creation of Attestations, like the github actions and gitlab runners.
- One aspect of SLSA that's still in flux is where generated attestations should be stored. Basically, there isn't really a standardized way of doing this yet? And it sounds like you're implying that Sigstore is one candidate and storing attestations within an app's own repo is an option as well, though it sounded like you're saying whether or not to do that is still an "open question".
- The act of appending things like signed attestations, signed SBOMs, or possibly other things/metadata, to something like a log/DB would be considered a "provenance entry" (not sure if that's the correct term).

If I'm on the right track, then awesome and thanks for openeing my eyes. 
Otherwise if I'm not even close here, then appologies in advance.

**Comment by jspeed-meyers** [comment]
> Attestations are just a "claim" about "something".

Bingo.

> In the context of SLSA, it's typically a claim by a developer on the security/quality of a piece of software.

That's roughly right. More specifically, you might say that SLSA (at least 0.1) [" protects against tampering during the software supply chain."](https://slsa.dev/use-cases)

> SLSA has some tools to help in the creation of Attestations, like the github actions and gitlab runners.

Yes!

> One aspect of SLSA that's still in flux is where generated attestations should be stored. Basically, there isn't really a standardized way of doing this yet? And it sounds like you're implying that Sigstore is one candidate and storing attestations within an app's own repo is an option as well, though it sounded like you're saying whether or not to do that is still an "open question".

That's right, but I am not the expert on the latter point (about non-sigstore options), so I defer to others.

> The act of appending things like signed attestations, signed SBOMs, or possibly other things/metadata, to something like a log/DB would be considered a "provenance entry" (not sure if that's the correct term)

I would say signed SBOMs, signed SLSA provenance documents, or other things/metadata are all forms of attestations. Provenance is just one form of attestation that focuses on where, when and how something was produced.

And on "software supply chain security" being in flux: indeed! And, in general, you're close.

FYI: For conversations like this, the SLSA slack channel in the OpenSSF slack is probably best. Feel free to move this conversation and related ones there :)

**Comment by wtfacoconut** [comment]
Roger that and thanks again!

**Comment by MarkLodato** [comment]
Reopening since we do need to define this in the Terminology section.

**Comment by lukehinds** [comment]
I have been quizzed about this a lot and have ended up summarising as:

attestation: evidence of state

provenance: source of origin

I went with 'state', as used as a noun it's deemed to be "the particular condition that someone or something is in at a specific time."

Coupled together, provenance tells me how software was constructed using its component parts (source repository, compiler,  build semantics), attestations enables me to assess its state. I then have the golden three:

* Authenticity
* Non-repudiation
* Integrity

**Comment by MarkLodato** [comment]
We currently have this page: https://slsa.dev/attestation-model

@lukehinds that does not seem to align with the in-toto and slsa definitions. Instead, I've been using:

* **Attestation:** authenticated statement (metadata) about a software artifact or collection of software artifacts. In other words, a claim by a party about software.
* **Provenance:** an attestation about how the software was produced. In other words, provenance is a subtype of attestation.

This also aligns with definition provided by @jspeed-meyers [above](https://github.com/slsa-framework/slsa/issues/521#issuecomment-1295938128).

**Comment by lukehinds** [comment]
@MarkLodato , that's fine, not expecting it to replace anything already agreed on, just throwing it in as my 2c.

**Comment by MarkLodato** [comment]
Addressed by #629.
