### ISSUE TITLE
SLSA Spec 1.0 - Fix Build L1/L2 Discrepencies

### ISSUE THREAD

**Issue by melba-lopez** [slsa-framework/slsa#523]
Some of the L2 requirements are discussed as benefits for L1.  Need to adjust language either on website or on github (depending on which is correct).

https://deploy-preview-512--slsa.netlify.app/spec/v1.0/requirements#build-track

- L1 - All build steps were fully defined in some sort of “build script”. The only manual command, if any, was to invoke the build script.
- L2 - All build steps ran using some build service, not on a developer’s workstation.

https://github.com/slsa-framework/slsa/blob/main/docs/spec/v1.0/levels.md#levels-and-tracks
- L1 Benefits: Prevents mistakes during the release process, such as building from a client with local modifications.

**Comment by melba-lopez** [comment]
"such as building from a client with local modifications."    Should be changed to...

Code cloned on a local system must match the upstream code during build.  Otherwise it is prevented.  

@lehors  @06kellyjac -- I didn't fully catch the conversation on the jenkins scenario.  I believe it was also around the jenkins server could also not have local modifications.

**Comment by melba-lopez** [comment]
Adding comments from [SLSA Specfiication notes ](https://docs.google.com/document/d/1kMP62o3KI0IqjPRSNtUqADodBqpEL_wlL1PEOsl6u20/edit# )entered by Mark:  

```
Mark: “client from local modifications” was meant more of a version control thing - did you build from an identical copy of the verison that was uploaded to version control? For example, `cargo publish` blocks this by default unless you pass `--allow-diry` (or similar).

- We’d need a requirement that, to call something Build L1, you need a roadblock somewhere in the publication step that stops someone from making a mistake of uploading an unpublished source.

- The term “local” is probably what’s confusing. It’s “local to the build”. Need better term.

Next steps: update levels.md to use more clear language and requirements.md to add a requirement where this is checked

```

**Comment by 06kellyjac** [comment]
The Jenkins point was more around having different host system libraries that can change underneath you or across separate instances. Similar to differing across developer machines.

But this wasn't too relevant once we clarified it was about ensuring the git repo wasnt dirty (and maybe had that commit in remote)

**Comment by lehors** [comment]
As for "local", the note from the meeting captures what I meant. What matters is that the code the build runs on matches the upstream code.
