### ISSUE TITLE
Provenance v1.0: consider other representation of digest

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#533]
In https://github.com/slsa-framework/slsa/pull/525#discussion_r1019186120, @kommendorkapten brought up the following question regarding the `digest` field:

> How about this:
> 
> ```protobuf
> enum HashAlgorithm {
>     HASH_ALGORITHM_UNSPECIFIED = 0;
>     SHA1 = 1;
>     SHA256 = 2;
>     SHA512 = 3;
> }
> 
> message MessageDigest {
>     HashAlgorithm algorithm = 1;
>     bytes digest = 2;
> } 
> 
> message DigestSet {
>     repeated MessageDigest digests = 1;
> }
> ```
> 
> The benefit of this is the the digests can be iterated over, and for clients who wishes to rely on the proto-JSON serialialzer don't need to think about binary marshalling as proto-JSON defines bytes to be base64 encoded strings when JSON encoded, small thing but makes the developer experience better as one failure mode (explicit base64 decoding) can be omitted.

This is a complex enough topic that warrants its own issue. I don't want the conversation to get lost in the pull request comment. I'll respond with my thoughts separately.

**Comment by MarkLodato** [comment]
First, this uses the same format as [`Statement.subject.digest`](https://github.com/in-toto/attestation/blob/main/spec/field_types.md). I'd strongly prefer keeping the two in sync, so either changing both or changing neither. For the sake of argument, let's assume we change both.

There are actually several independent issues being brought up here:

- JSON hex vs base64 for the value
- JSON map vs array, e.g. `{"sha256": "abcd"}` vs `[{"type": "sha256", "value": "abcd"}]`
- If it's a map, in the proto schema, do we use `map<string, string>` or `message`

### JSON hex vs base64

I don't feel strongly here, though without a strong justification I'd err on the side of not changing. There's also a parallel discussion in https://github.com/in-toto/attestation/pull/108 about using base64 for the go "dirhash".

I think we have three options:

- Always use lowercase hex.
- Always use base64.
- Use hex or base64 for standard algorithms but allow custom algorithms to use whatever makes sense

In my mind:

* Size: Base64 is more compact ==> base64 is winner
* Simplicity: Most tools spit out lowercase hex encoded digests. Converting to base64 requires first hex-decoding and then base64-encoding. It's easy to mess up by doing base64(hex(digest)). ==> hex is winner
* Canonical encoding: Hex has upper vs lowercase, while base64 has standard vs web-safe ==> draw (though I think hex is a bit better here)
* Alignment with other ecosystems: OCI/Docker uses hex, go uses base64, etc. ==> draw

My inclination is to keep hex, but again I don't feel strongly.

### JSON map vs array

I find the map much easier to work with. Both options allow you to iterate over all possible key/value pairs, but only the a map allows you to directly access the value you want. Most of the time, we're working with a single known algorithm (usually `sha256`). Having to iterate every time is a pain.

Consider the following SQL snippets where we know we want to access `sha256` (relative verbosity is similar in other languages):

```sql
--- JSON array
SELECT (SELECT d.value FROM UNNEST(digest) AS d WHERE d.type = "sha256") AS sha256
--- or:
WHERE EXISTS (SELECT 1 FROM UNNEST(digest) AS d WHERE d.type = "sha256" AND d.value = "abcd1234")
```

```sql
--- JSON map
SELECT digest.sha256
--- or:
WHERE digest.sha256 = "abcd1234"
```

What is the use case for iterating over all possible key/value pairs?

### Proto `map` vs `message`

If we do have a JSON map, then we could represent this in two possible ways in the proto schema:

```proto
map<string, string> digest = 1;
```

```proto
message DigestSet {
  string sha256 = 1;
  string sha512 = 2;
  ...
}
```

I don't have a strong opinion here. The former is easier to loop over, the latter is easier to access directly.

**Comment by kommendorkapten** [comment]
Good summary!

Just to throw in another format into the mix:

```protobuf
message DigestSet {
    map<string, bytes> digests = 1;
}
```

Which is very close to Statement/subject, and probably my preferred structure. I think a map is probably the best option, as it can be iterated over, and any element can be accessed directly.

The question on hex vs base64 is a bit more complex, and I think you broke down the differences in a good way. 

For the protobuf definitions in Sigstore we chose to focus on the real data we need, not how the data is encoded, and so we opted for `bytes` for all binary data. There are two benefits as I see it, which are both tied to the same principle. Namely that protojson decodes the textual representation direct into the used language's binary representation. If defining the data as a string, that burden falls on the developer. The second issue is that the developer has to know what encoding (hex or base) is used for each field (they may often differ!). 
As protobuf uses base64 when doing JSON encoding, there are some downsides, as many people are used to see hash digests as hex encoded, so that may make it a tad bit harder to guess what the data is.

**Comment by di** [comment]
Some prior art: The `Digest` HTTP header uses a base64-encoded value for the digest: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest. That said, I don't think the size of the value is a strong argument here, and for the reasons @MarkLodato mentioned, my preference would also to be to keep this hex-encoded.

Regarding map vs. array: another downside to an array representation that hasn't been mentioned is that it's possible to include values:

- `digest: [{"type": "sha256", "value": "abcd"}, {"type": "sha256", "value": "wxyz"}]` is valid JSON
- `digest: {"type": "sha256", "value": "abcd", "type": "sha256", "value": "wxyz"}` is not valid JSON

This would require extra validation of this field that using a map would make unnecessary.

Overall: I think we should keep this and the corresponding in-toto spec as is, and remove this TODO: https://github.com/slsa-framework/slsa/blame/main/docs/provenance/v1.md#L306

**Comment by MarkLodato** [comment]
OK, I'll mark this as resolved and remove the TODO.
