### ISSUE TITLE
Specification status / maturity levels definition

### ISSUE THREAD

**Issue by lehors** [slsa-framework/slsa#541]
The status of a specification ought to be clearly displayed so that the reader knows exactly what to expect: e.g., whether it is stable or not, whether comments or feedback is welcome etc.

We therefore need to define the different states a specification can be in and document it.

Trying to keep it simple, I think we should provide for the following different states:

- Working Draft - the document is actively being worked on and can be changed at any time
- Proposed Specification - the document is believed to be feature complete and stable
- Specification - the document is considered stable and suitable for reference in implementations
- Obsolete - the document is not longer to be used - it has been superseded by a new version or rescinded

If we really want to be minimalist we could do without "Proposed Specification" but I think it is a good way to communicate that the spec is up for final review.

All specifications should include on their front page a "Status of this document" section stating which state the document is in as well as any additional info the group wants to communicate to the reader such as whether comments are encouraged or not, etc.

For an example of what this can look like see any W3C specification, such as: https://www.w3.org/TR/2022/WD-html-aam-1.0-20221128/

**Comment by MarkLodato** [comment]
Are we good to close this issue, @lehors?

**Comment by lehors** [comment]
Ah, yes! thanks for the ping.
