### ISSUE TITLE
Old Chainguard logo

### ISSUE THREAD

**Issue by denhamparry** [slsa-framework/slsa#556]
The Chainguard logo used within the site is the old logo.

An example of it being used on the site can be found within the <https://slsa.dev/> page under the section _An industry collaboration_.

An example of the new Chainguard logo has been attached to the issue.

![chainguard](https://user-images.githubusercontent.com/1263813/209826271-3ab41882-5cb1-407e-9a81-4e67d39c090b.png)

**Comment by mlieberman85** [comment]
Hi @denhamparry can you or someone else from Chainguard open up a PR to change https://github.com/slsa-framework/slsa/blob/main/docs/images/logos/chainguard.png ?
