### ISSUE TITLE
Add section about how to refer to SLSA versions

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#570]
In the [SLSA 1.0 proposal](https://github.com/slsa-framework/slsa-proposals/tree/main/0003), we decided the following (bullets added for clarity):

> - The specification is versioned but we agree to never change the gist of each level ("hybrid" below). Effectively, the "SLSA 1/2/3/4" namespace is taken. It would cause too much confusion to change the meanings significantly, and requiring everyone to always specify a revision number is impractical. We can still make minor revisions to the levels, so long as we do not believe it would cause too much confusion.
> - When precision is not critical, unversioned references are OK, e.g. "SLSA 3."
> - When precision is required, references MUST include a revision number, preferably using the syntax "SLSA 3 (v1.0)," and ideally backed by [evidence of security claims].

We need to incorporate that into the v1.0 spec somewhere.

**Comment by Pierre-Gronau-ndaal** [comment]
agree 

put it in -> abstract

**Comment by MarkLodato** [comment]
See also #632: we should talk about semantic versioning and figure out a reasonable story there.
