### ISSUE TITLE
Tracking issue for draft SLSA 1.0 support in tools

### ISSUE THREAD

**Issue by mlieberman85** [slsa-framework/slsa#574]
This is just a tracking issue (of tracking issues) so we can list the tools out there that are supporting SLSA today, or planning support SLSA, and plan to support the draft 1.0 spec.

There are 2 goals:
1. Show demonstrative examples of the draft 1.0 spec or requirements conformance in action.
2. Help us test out the draft 1.0 spec and provide feedback

List (will be edited as time goes on)
- [GitHub Generator](https://github.com/slsa-framework/slsa-github-generator) - https://github.com/slsa-framework/slsa-github-generator/issues/1734
- [Verifier](https://github.com/slsa-framework/slsa-verifier) - https://github.com/slsa-framework/slsa-verifier/issues/515
- FRSCA
- Tekton - https://github.com/tektoncd/chains/issues/728
- Npm cli - https://github.com/npm/cli/issues/6268
- Buildkit - https://github.com/moby/buildkit/issues/3684
- PyPI - ??
- Sigstore Cosign - https://github.com/sigstore/cosign/issues/2860
- in-toto golang - https://github.com/in-toto/in-toto-golang/issues/197
- Witness - https://github.com/testifysec/witness/issues/217

**Comment by colek42** [comment]
We are planning to support SLSA in witness soon.  https://github.com/testifysec/witness/issues/217

**Comment by pxp928** [comment]
GUAC is being updated to support multiple versions of GUAC: https://github.com/guacsec/guac/issues/793

**Comment by bobcatfish** [comment]
I'm excited to say that are planning to add support for SLSA 1.0 to [Google Cloud Build](https://cloud.google.com/build/docs/overview) as well! 🥳  plz add us to the list 🙏

**Comment by marcelamelara** [comment]
Pinging this issue since I've been looking at buildkit provenance generation recently, they still only support v0.2. Seems like their main blockers for implementing v1 are explained in https://github.com/slsa-framework/slsa/issues/716. Might want to have a discussion on how we might approach this issue.
