### ISSUE TITLE
SLSA v1: what are are the consumer's responsibilities?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#591]
**Objective: Agree on what responsibilities the consumer has in SLSA v1.** This was forked from PR #588 to make discussion easier to follow. Once we have a general idea, we'll incorporate it into that PR. CC: @lehors

Currently we say something like:

- An artifact is not considered to meet SLSA until it is verified.
- The ecosystem is responsible for providing verification infrastructure, some combination of:
  - Enforced at publication time (blocking)
  - Enforced at install time (blocking)
  - Monitoring (non-blocking)
- Enforcement MAY require opt-in from the publisher (for publication-time enforcement) or consumer (for install-time enforcement). [Not sure we actually say this yet.]

That last bullet is unclear. What is the actual requirement for the consumer? Does it depend on what mode the ecosystem supports? Is it like special relativity where the SLSA level depends on the observer, and if so, how do we capture this concept?

**Comment by abacchi** [comment]
_If I never dip my chips in salsa - would you consider me to be a salsa consumer?_
In my opinion:
In order to be considered a consumer in the SLSA ecosystem - you must validate the artifact.
@MarkLodato I like the bullet above that says - 

> An artifact is not considered to meet SLSA until it is verified.
The SLSA consumer might not be first hand verifying the artifact- but as a proxy putting their trust in the monitor (which then they trust)
Maybe the bottom line I am trying to get to is that the consumer should make decisions on the verification of the artifact- be it first hand or through a trusted monitor.

**Comment by lehors** [comment]
I'm not sure I fully understand the monitoring use case yet, is there anything written about it I can read?

With that (pretty big! :) caveat, it doesn't seem to me that this should be the driving factor here.

What's important is that security can only be achieved if every actor in the chain from producer to consumer does its part. This is how I read the table in the requirements section which defines everyone's responsibility.

From that point of view, as I said on the call, we ought to make it a MUST for the consumer to opt-in if it's not on by default.

Of course this doesn't mean everybody must actually do so. This is only applicable to consumers who want to benefit from SLSA. If people choose not to enforce validation at their end that's fine but in doing so they are putting themselves outside of the SLSA ecosystem and cannot expect to benefit from it.

**Comment by joshuagl** [comment]
Yes. I think that a consumer must "opt-in", though oftentimes that opt-in is implicit through actions such as choosing a package ecosystem that does SLSA verification.

**Comment by MarkLodato** [comment]
> I'm not sure I fully understand the monitoring use case yet, is there anything written about it I can read?

Good point. The only thing written so far is [here](https://slsa.dev/spec/v1.0/requirements#verifying-expectations-for-artifacts):

> Package ecosystem participants and/or the ecosystem operators perform continuous monitoring of packages to detect any changes to packages which do not match the known expectations. TODO: do we need to emphasize that the value of monitoring without enforcement is lower?

Here's my thinking: Suppose an organization wants to adopt SLSA. They set up a secure build service, get their teams to adopt it, figure out provenance propagation/storage, and set up expectations for all their packages. All the pieces are there. But they are hesitant to build and enable enforcement until they have confidence that there is sufficient demand and that it's safe to do so. So they build a monitoring solution that notifies teams when they publish non-compliant packages, e.g. ones not built using the official build system. This doesn't stop badness from happening, but it starts to change the culture and habits. They might run this for months or years until enforcement is ready.

I suspect most large organizations will operate this way. In fact, this is precisely how Google did [Binary Authorization for Borg](https://cloud.google.com/docs/security/binary-authorization-for-borg).

So, what we call this, and how do you differentiate it from enforcement? We can't not give it a name, because they basically are doing almost all of SLSA, just not the prevention bit. We still want levels.

Two main options immediately come to my mind, though there are likely other solutions:

- The term "SLSA Build Lx" implies enforcement unless there is some qualifier explaining that it is monitoring-only, e.g. "SLSA Build L3 (monitoring only)".
- The term "SLSA Build Lx" does not imply enforcement, and you can add a qualifier to explain that it is enforced, e.g. "SLSA Build L3 (enforced)" or "L3E".

Between these, I prefer the first one. But maybe there are better options.

What do you think?

**Comment by joshuagl** [comment]
I agree that it's important to call out the monitoring use-case. I prefer the first option (SLSA Build Lx implies enforcement) — we should default to the preferred mode of operation, while supporting a gradual adoption as implied by a monitoring mode.

**Comment by abacchi** [comment]
Agreed on the implication of enforcement -with needing to specifically call out monitoring only. 
I think an organization or individual can still be considered a consumer if they are observing the monitoring component (this monitoring would essentially be BOOL SLSA compliance)
They wouldn't be a consumer if they are not observing monitoring and instead just trusting the producer's attestation of SLSA level only.

**Comment by lehors** [comment]
Thanks for the explanation @MarkLodato And I too agree that the first one is better for the reasons @joshuagl and @abacchi stated.

**Comment by lehors** [comment]
Getting back to this, do we then agree that when it comes to the responsibilities of the consumer, we can say that they MUST enable verification if the package-ecosystem doesn't do so by default?

I note that PR #598 added that:
`The consumer MUST ensure that the artifacts they consume are built on
SLSA-conformant build systems. Consumers MUST either audit the build systems
themselves using the prompts in [verifying systems](verifying-systems.md) or
rely on the [SLSA certification program](certification.md).`

I think the second MUST is to strong and needs to be changed to a SHOULD. There may be other ways to evaluate a build system and there is no reason to limit how people will do so.

**Comment by MarkLodato** [comment]
PR #619 attempts to remedy this situation by moving the verification piece out of "requirements". @lehors I believe this is in line with what you have been thinking? Your thoughts there would be appreciated.

**Comment by lehors** [comment]
Thanks @MarkLodato for pointing it out. I took a first pass, I think it is going in the right direction.

**Comment by kpk47** [comment]
#675 is relevant to this discussion. I'm implicitly giving the consumer responsibility for setting and testing expectations by giving those responsibilities to the "verifier" and listing the consumer as a possible verifier. Does that seem about right? @lehors

**Comment by MarkLodato** [comment]
As the original poster, I think this is resolved enough that we can close this issue. If there are remaining issues, they will come up during the RC2 review.

**Comment by lehors** [comment]
I agree.
