### ISSUE TITLE
Provenance v1: Add `builder` to the SLSA Provenance model

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#593]
In the [provenance v1 spec](https://slsa.dev/provenance/v1), it would be nice to clarify how the diagram and particularly the "Build Process" relate to the `builder`. The description talks about `builder` but is not shown in the diagram. *(Originally posted by @rbehjati in https://github.com/slsa-framework/slsa/issues/582#issuecomment-1406680513.)*

I'm not sure how best to do this so I'm creating this issue to track ideas.

First, what exactly is the builder in the diagram? Is it a collection of multiple boxes (e.g. platform, build type, build cache, build process)? Is it just the platform? Does it not really map to the diagram?

Once we decide that, we can figure out how to represent it. For example, I tried adding dashed lines around a collection of boxes but that added too much clutter.

**Comment by MarkLodato** [comment]
Also add a legend:

- Green = trusted, does not require verification
- Orange = external
- Grey = logical, doesn't really exist
- Red = the build process itself, red because it's under the tenant's control

Probably need to update the intro text to better explain and account for this.

![SLSA Build Model v1 0](https://user-images.githubusercontent.com/58860/215149291-71b69db7-fd1f-40f3-9510-8c9b8cfff19c.svg)

**Comment by MarkLodato** [comment]
I don't have any good idea on how to add it. I'm inclined to close as "won't fix". Any opinions?

**Comment by rbehjati** [comment]
> First, what exactly is the builder in the diagram? Is it a collection of multiple boxes (e.g. platform, build type, build cache, build process)? Is it just the platform? Does it not really map to the diagram?

Yes. Indeed. From the description, it is not clear to me if there is a difference between the `builder` and the `platform`.  The description says that `builder.id` identifies the `platform`. From this, is it correct to conclude that `builder` and the `platform` are essentially the same thing? 

If so, perhaps we just need to clarify in the description that `builder` is short for `build platform`. Also we often talk about a `trusted builder`. Is it the same as the `platform`?

@asraa Any ideas?

**Comment by asraa** [comment]
> If so, perhaps we just need to clarify in the description that builder is short for build platform. Also we often talk about a trusted builder. Is it the same as the platform?

I think it seems like this.

Doesn't the builder/platform provides the `System Parameters`? so it might be worth putting a dotted arrow saying `-- provides -->`.

**Comment by rbehjati** [comment]
That makes sense. 

@MarkLodato I think clarifying what the builder is in "Provenance is an attestation that the builder produced the subject software artifacts through execution of the buildDefinition." will fix this problem. Since the sentence says that the attestation is partly about the builder it is important to be clear what the builder is.
