### ISSUE TITLE
SLSA v1: how to represent what capabilities a builder has w.r.t. provenance values

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#594]
_Originally posted by @laurentsimon in https://github.com/slsa-framework/slsa/pull/582#discussion_r1087222031_

> A bit of a tangent question: is it correct that the builderType will indicate whether the builder is capable (or not) of reporting these values? (similar question for `env` and `vars`). 
>
> Example: the default npm CLI cannot capture this in an unforgeable way (since it's under the control of the project maintainer), unless the registry is able to verify it by querying the runner at package upload time.
>
> Hence, then do we need to define different builder types: one for the "runner" builder and one for the "reusable workflow" builder... and maybe a hybrid one if only certain fields can be reported?
>
> /cc @asraa @feelepxyz

I suspect we want to say that the `builder.id` indicates how complete and accurate the provenance is, independent of `buildType`, but I'm forking this conversation to get #582 submitted.

**Comment by laurentsimon** [comment]
> I suspect we want to say that the builder.id indicates how complete and accurate the provenance is, independent of buildType, but I'm forking this conversation to get https://github.com/slsa-framework/slsa/pull/582 submitted.

I'm also curious how this fits in the compliance program effort. The compliance gives a builder a SLSA level as a whole, iiuc. 

So maybe it will work as:
1. `builder.id=npm-cli` is level 1 and can report any fields it wants. Nonce of these fields are trusted
2. `builder.id=gitub-runner/npm` can predent to level 3 and only reports fields that are non-forgeable. What if a builder accidentally adds fields they are not supposed to? Does compliance catch that?
3. `builder-id=path/to/github-reusable-workflow` can pretend to level 3 and report all fields it wants.

The situation is a bit more complex if builders want to support multiple buildTypes and they cannot populate some fields for *some* buildTypes yet can for others.
