### ISSUE TITLE
Clarify that "build service" does not require SaaS

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#599]
From @lukehinds:

> The [build service](https://slsa.dev/spec/v1.0/requirements#build-service) section of lvl 3 is creating some ambiguity (someone just pinged me as they were confused). Its (even if mistakenly) being interpreted as it has to be a SaaS (rather then include on-prem). Maybe adding a solution such as tekton or jenkins might make it look less like it has to be a service provided by someone else?

Agreed. For v1.0, we should be more precise on what "build service" means and what the purpose is of this requirement. In my mind, the main purpose is something like (1) concentrate trust into a smaller number of systems, (2) provide a central point that can be hardened, and (3) remove superuser powers from an individual developer.

**Comment by mlieberman85** [comment]
We don't call it build service in the CNCF Secure Software Factory or Supply Chain Security Best Practices guide, but I do think there's some useful info, much of which I think is beyond scope.

https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/CNCF_SSCP_v1.pdf
https://github.com/cncf/tag-security/blob/main/supply-chain-security/secure-software-factory/Secure_Software_Factory_Whitepaper.pdf

The way we defined the core elements of a "secure" build service in the Secure Software Factory Ref Arch is pretty much as follows:
- Secure orchestration of the build pipeline. i.e. only approved pipelines that follow established policy and rules should be allowed to run.
- Secure orchestration of the build workload. i.e. only approved build workloads are allowed to be run, and if someone tampers with the orchestration of a workload it should be detected or prevented. An example here is using SPIFFE or other workload identities.
- Secure the actions in the build workload itself. i.e. a build that tries to perform malicious actions should be prevented and the build workload should be isolated enough to limit blast radius.

There are a handful of high level things beyond what you've stated which should also be part of that definition:

- Clear security delineation between build orchestration and the build workload. e.g. running a Jenkins worker in the same "server" as the Jenkins controller is a no no.
- For level 3 I think the requirements create the need to make sure there is a clear preventive or detective control for admin abuse. e.g. An administrator of a k8s cluster that runs FRSCA can't tamper with running builds without it being prevented or detected.
- Even though we have stuff like builds should be isolated/ephemeral/potentially hermetic it might be worthwhile to make it clear that a goal of a secure build system should be that even if a build itself is compromised, that build should not be allowed to compromise the build system.

**Comment by MarkLodato** [comment]
Since we're running up to the v1.0 deadline, I'm bumping this to post-1.0. I don't think this will be a problem to clarify after the 1.0 release.

**Comment by MarkLodato** [comment]
Marking as a duplicate of #369.
