### ISSUE TITLE
"Identifies artifact" requirement no longer explicit

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#601]
The 1.0 requirements and provenance format no longer explicitly state that provenance "provenance MUST identify the output artifact via at least one cryptographic hash" per the 0.1 [Identified artifact](https://slsa.dev/spec/v0.1/requirements#identifies-artifact) requirement.

This is implicit if you're following the specifications recommendation to use the SLSA provenance format and the in-toto attestation suite, but what about for those who are not? Should we make this an explicit requirement again?

**Comment by MarkLodato** [comment]
Hey @joshuagl what do you consider the priority of this? Is it a blocker for v1, can we address it later without a version bump, or is it just lower enough priority to close?

**Comment by joshuagl** [comment]
I think we can address this later without a version bump. This is covered in the spec today. In fact, we could probably even close this and add the clarification if requested, because:
* In #602 we added additional text to state that "The build process MUST generate provenance that *unambiguously identifies* the output package" (emphasis added)
* We refer to the provenance's subject in the spec, i.e, in step 2 of [How to verify](https://slsa.dev/spec/v1.0/verifying-artifacts#step-1-check-slsa-build-level).
* _possibly other places we talk about `subject`_

**Comment by MarkLodato** [comment]
Thanks. That's helpful. Re-reading the text, I still think "unambiguously identifies" is too ambiguous 😝  so I sent out #768 to add "by cryptographic digest". With that I think this issue is closed.

**Comment by joshuagl** [comment]
That changes removes ambiguity, thanks Mark!
