### ISSUE TITLE
Provenance: canonicalize trailing slashes

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#609]
Previously, the `predicateType` and `buildType` URIs omitted the trailing slash in the JSON file, and this matched the URL in the browser because we used files like `v0.1.md`. Now that we have moved to directories, the server redirects to a URL containing a trailing slash, which disagrees with the URI in the JSON. We need to resolve this somehow.

A few ideas (not exhaustive):

- Do something with our server (either in Jekyll or by switching host) so that the URL always omits the trailing slash, redirecting slash to no-slash.
- Use a slash in the URI.
- Have some documentation explaining which to use. (Right now https://slsa.dev/github-actions-workflow/v0.1 does not explicitly document the `buildType` string, though it should.)
- Instruct that either must be accepted (seems brittle).

Example: The spec says `predicateType: "https://slsa.dev/provenance/v1"` (no slash), but if you go to that URL, it redirects to https://slsa.dev/provenance/v1/ (with slash).

**Comment by di** [comment]
Is there any reason we need URLs like https://slsa.dev/provenance/v1/index.html or with the slash to continue resolving? We can set permalinks for these pages in the frontmatter, but that means that there will only be one link that resolves to that page.

**Comment by MarkLodato** [comment]
I don't think we need /index.html to resolve, but I do think with or without the slash should redirect to the canonical page.

After thinking some more, we should probably have the no-slash be canonical, since that is nicer to look at and less likely to be messed up in the JSON. To do that, we should move `.../<version>/index.md` to `.../<version>.md` so that relative links work correctly. The alternative, having `.../<version>/index.md` be served at `.../<version>` would break any relative links.

By the way, https://github.com/slorber/trailing-slash-guide is super useful here.

**Comment by di** [comment]
Right now that's not the case for files, e.g. https://slsa.dev/provenance/v0.2/ is 404. I think this is due to permalinks being configured here: https://github.com/slsa-framework/slsa/blob/b3aa55f4819d8dfb6315dd112235bfa309101768/docs/_config.yml#L20 which was added in https://github.com/slsa-framework/slsa/commit/8a6939d9aff81f5d5e9d360d12abd14fb4c67dad. Are you OK with unsetting that?

**Comment by MarkLodato** [comment]
Ah, good point. No, I think that's fine. I think users expect that omitting a slash is OK but adding one is not. That's how most websites work.

My main concern is just that the URL bar should match the string in the JSON, to avoid mistakes.
