### ISSUE TITLE
Clarify "parameterless" build

### ISSUE THREAD

**Issue by denhamparry** [slsa-framework/slsa#613]
# Source

https://slsa.dev/spec/v0.1/requirements#parameterless

# Understanding

I understand that parameterless builds are in place to have the best posture available when looking to create reproducible builds for our artifacts. This also looks to prevent human interaction/intervention during the build process post-initiation for the same reason.

# Clarification

If a step were to fail during a later stage within the build process for an external reason (for example, timeout when transporting an artifact from A to B), and there was a solution of human intervention to retry this step would this be considered breaking the parameterless requirement? If the artifact was previously built and we have provenance in place to confirm that the steps have completed, a parameter being sent could indicate to retry the final step that would not affect the artifact that has been built with provenance that can clarify that.

# Opinion

I believe that as long as we have provenance to show that the build has completed the previous stages, then this artifact could be used and the step retried without breaking this requirement. I'd also include the failure as provenance with reason for the failure (e.g. network timeout), and look to have an identity associated with who/what initiated the retry of the failed step.

**Comment by jspeed-meyers** [comment]
cc @MarkLodato, @joshuagl 

When @denhamparry raised this with me, I though it fell in spec grey territory and suggested he raise it here. I also realized that v1.0 changes might render some of this moot. TY!

**Comment by MarkLodato** [comment]
Thanks, agreed that this needs clarification. Related: #278 and #454. For v1.0 we are temporarily undefining SLSA 4 because this and other L4 requirements need more clarification.

Haven't fully thought it out, for [v1.0](https://slsa.dev/spec/v1.0/requirements) I think we say that the build system just needs to **list** all external parameters at SLSA Build L3 **and** users must have a way to know what is expected. So in your example, either that parameter doesn't affect the build (so it shouldn't be listed) or consumers have a way to know whether or not to allow it. Does that help?

**Comment by denhamparry** [comment]
Thanks @MarkLodato, that answers the question for me.

**Comment by di** [comment]
> for [v1.0](https://slsa.dev/spec/v1.0/requirements) I think we say that the build system just needs to list all external parameters at SLSA Build L3 and users must have a way to know what is expected

Should we leave this open to document this in the 1.0 spec?

**Comment by denhamparry** [comment]
If the issue is of value for the 1.0 spec please feel free to reopen, I closed as my question has been answered.

**Comment by MarkLodato** [comment]
I think it's sufficiently documented (see [quote](https://slsa.dev/spec/v1.0/requirements#provenance-non-forgeable) below) but if you disagree let me know and I'll reopen.

> Completeness: MUST be complete. In particular, the external parameters MUST be fully enumerated in the provenance.

**Comment by di** [comment]
Ah, I read that as "I think we should say...", agreed that it's fine as-is, sorry for the noise!
