### ISSUE TITLE
Provenance v1.1+: remove `builder.id`?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#622]
### Summary

**Proposal:** Remove the `builder.id` field.

The envelope _mostly_ identifies the builder (through the public key, x.509 SAN, or similar). The question is, why do we need the `builder.id`? It generates a lot of confusion. Can we get rid of it?

### Background

The purpose of the `builder.id` is twofold:

1. If a build system has multiple modes, only some of which satisfy a particular SLSA Build level, and they are all signed by the same identity, then the `builder.id` can be used to differentiate between these modes.
2. Similarly, if an external provenance generator can support multiple build systems (say by reading logs or by the build service calling it) and it signs everything with the same key, the `builder.id` can be used to differentiate between these build systems / callers.

However, this has a few problems:

- This is confusing and not well documented. Several implementers have misunderstood this.
- It makes verification more complex. Instead of just checking the signer, you *also* have to check the `builder.id` and make sure they are consistent. If you forget, it's a security hole.
- If implemented poorly, it can be a security vulnerability.

Relatedly, v1.0 is moving towards having the builder's identity be the sole indicator of SLSA build level; see #618. Prior versions required checking various fields (particularly the "parameterless" requirement of SLSA 4) but v1.0 simplifies this by (a) shifting the burden to make a claim about the SLSA Build level and (b) replacing the "parameterless" with expectations on parameters. This we now have more clear footing to say explicitly that the signer identity is a claim by the builder that the build meets a certain level.

### Proposal

Remove the `builder.id` field entirely and instruct implementers to use different signer identities to represent different builder modes or build levels. This simplifies the spec and avoids a common point of confusion.

### Open questions

Are there any remaining use cases where `builder.id` would still be needed, i.e. where the signer identity is not sufficient?

### Alternatives considered

- Keep the `builder.id` field.
  - Pro: Flexible.
  - Con: Confusing and error prone.
- Replace `builder.id` with a more narrow "mode of operation" or similar, to differentiate between modes that have fundamentally different security properties. The verifier would use this the same as they use `builder.id` today.
  - Pro: Flexible.
  - Pro: Somewhat less confusing and error prone.
  - Con: Still confusing and error prone.
- Replace `builder.id` with an explicit "Claimed SLSA Build level" field that the builder populates.
  - Pro: Explicit, clear.
  - Con: Too easy for verifiers to blindly accept this without "roots of trust" (#618).
  - Con: Confusing if the claim is X but the roots of trust say Y (< X).
  - Con: Cannot differentiate between different modes that have the same SLSA Build level.
- Replace `builder.id` with a list of SLSA requirements that are met.
  - Pro: Explicit, clear.
  - Pro: More flexible.
  - Con: Much more complex for verifiers. The roots of trust now list not just level but also properties that are believed.
  - Con: Confusing if claims disagree with roots of trust.

### Next steps

If you have an opinion one way or the other, please comment here.

I'll send out a pull request that implements this, to see how it looks.

**Comment by MarkLodato** [comment]
Here's one open question: let's consider the case where a build system has two modes of operation, represented by two different `buildType`s:

- One mode reads all build configuration from a file in version control. In this mode, there is a single parameter: the file location (repo + ref + path). This **is** practical to set expectations for because the file reference stays the same between builds (plus it is easy for a human to inspect and make a decision on).
- Another mode reads build configuration passed in over RPC. In this mode, there are many parameters (the full build configuration!). This is likely **not** practical to set expectations for because the parameters change on every build (and a human cannot reasonably read it to know whether it's "expected" or not).

Both modes satisfy SLSA Build L3 isolation and provenance generation requirements, so using one mode will not compromise the other.

Questions:

1. Does the second mode still count as SLSA Build L3, even though expectation setting is impractical? (How does this map to the requirements?)
2. Should the builder use a different "builder identity" (signing key) for the two modes, or is it sufficient to use different `buildType`s?

**Comment by TomHennen** [comment]
I'll just drop a comment here to indicate that I'd be somewhat sad if we dropped builder.id.  We're already using it for a couple of different purposes.  I'm sure we could adapt to something else, but it would be painful.

**Comment by MarkLodato** [comment]
Just chatted with @TomHennen. Most of the existing use cases of `builder.id` can be replaced with a lookup by signing key. (The verifier already has a map `{signing_key, builder_id} -> slsa_level`, which can easily be changed to `signing_key -> {builder_id, slsa_level}`.)

The remaining use case is (2) above, namely a single service that signs with one key "on behalf of" other callers. In this case, there is currently no other place to stick this in DSSE or Statement.

I can see an argument for adding an "on behalf of" to either DSSE or Statement:

- In DSSE:
  - Pro: logically makes sense (it is about authentication, after all)
  - Note:  I suspect we can make it backwards compatible when this new field is not present (i.e. the PAE is unchanged if the new field is empty.)
- In Statement:
  - Pro: Likely fewer code changes.
  - Pro: Governance and timelines align better, since attestation v1 is happening now (https://github.com/in-toto/attestation/issues/130)
  - Con: May result in similar issues as `builder.id` in terms of confusion and misuse, though clearer guidance could mitigate this.

**Comment by AdamZWu** [comment]
I feel that adding the "on behalf of" field into DSSE would make the verification behavior at the DSSE layer more complex, which runs against its mission, i.e. "Simple, foolproof standard for signing arbitrary data." To keep the DSSE really "dead simple", maybe putting the attestor validation behavior in the in-toto statement layer is a better option.

**Comment by laurentsimon** [comment]
> Most of the existing use cases of builder.id can be replaced with a lookup by signing key. 

I'm not sure this is true. In the Sigstore world, there is no such mapping. There is a root cert that is common to all CI systems. The identity of the "builder" is a combination of certificate fields (OIDC provider) and other parameters. For example, on GitHub, it could be a workflow that is self-hosted or GitHub-hosted; or it could be a reusable workflow.

**Comment by MarkLodato** [comment]
Sorry, I was using "signing key" as shorthand for "authenticated identity derived from the envelope layer". Regarding slsa-verifier, it seems like a mistake to peek into the payload to see how to authenticate the envelope. Isn't that what `keyid` is for?

That said, given the impending deadline combined with the pushback both here and on https://github.com/in-toto/attestation/issues/137, let's keep `builder.id` for v1.0 (at least). Instead, I'll try to clarify wording that in many (most?) cases, it is not needed and instead the envelope layer should identify the builder identity.

**Comment by laurentsimon** [comment]
> Sorry, I was using "signing key" as shorthand for "authenticated identity derived from the envelope layer". Regarding slsa-verifier, it seems like a mistake to peek into the payload to see how to authenticate the envelope. 

ah, we don't peek into the builder.id, it's provided by users as a CLI option and it's human readable which is nice. keyid is not present in sigstore bundles, but the cert can provide enough information to determine the builder if we want.

**Comment by mlieberman85** [comment]
I could be wrong, but I had assumed that builder.id was going to be a URI which might resolve to some schema or additional metadata that could be used to further verify elements within the SLSA provenance.

**Comment by laurentsimon** [comment]
I think what you're describing is the `buildType`, but I may also be wrong.

**Comment by TomHennen** [comment]
Well, the buildType might say something like "Jenkins Build" but the builder.id would indicate "Tom's Hosted Jenkin's Service" and the document at that URI could serve evidence that we've passed our SLSA L3 audit according to <some authority>.

**Comment by mlieberman85** [comment]
> Well, the buildType might say something like "Jenkins Build" but the builder.id would indicate "Tom's Hosted Jenkin's Service" and the document at that URI could serve evidence that we've passed our SLSA L3 audit according to .

Yes this is what I was talking about.

**Comment by di** [comment]
There is some related discussion about what the `builder.id` should be in the npm provenance beta here: https://github.com/gh-community/npm-provenance-private-beta-community/issues/9

**Comment by MarkLodato** [comment]
After discussion with @ianlewis and @laurentsimon, I suggest we keep `builder.id` required, just like in v0.2. Having it be optional is just two hard to describe. It's a bit of a foot gun for implementations because they can forget to check, but the alternative of confusion seems worse. It's nice to have a URI to represent the builder once the envelope is thrown away (which is why we added it in the first place).
