### ISSUE TITLE
Separate hosting for community-maintained buildTypes?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#662]
In https://github.com/slsa-framework/slsa/pull/623#issuecomment-1456240866, @lehors brings up the point that slsa.dev should not be the home for buildType definitions for proprietary or commercial build systems. I still think it's valuable to have a central repository for community-developed definitions, even for commercial build systems, since no build system maintains an official one yet. My thinking:

1. For community-maintained definitions, there is no natural place to put it.
2. Even for official definitions, hosting can be difficult, especially coming up with a good short URL.
3. Having multiple definitions adjacent to one another brings consistency and ease of comparison.

What do you think about creating a new domain for this, e.g. `https://buildtype.slsa.dev`? This could use a different theme and clearly state that these are community maintained and not owned by the OpenSSF. The top-level page (`/`) could serve as the index, even for ones that are not hosted there.

**Comment by lehors** [comment]
To summarize my point: I think there is value in having an index. I don't think we should host the definitions.
I would also add that there are examples of such registries we could look at. One I have in mind is the W3C DID registry, although I would keep each entry even simpler: https://github.com/w3c/did-spec-registries

**Comment by MarkLodato** [comment]
But we are writing some of these build types and we need a place to host them. What should we use for those?

You suggested slsa-github-generator but that's not right either - it's not specific to that project.

**Comment by TomHennen** [comment]
FWIW for in-toto attestations we provide [a common location](https://github.com/in-toto/attestation/tree/main/spec/predicates) for folks to define these definitions.  When reviewing PRs we provide some feedback to the specifiers to see if what they're proposing makes sense.

A similar structure for buildType definitions would seem to make sense?

**Comment by MarkLodato** [comment]
Discussed at today's [spec meeting](https://slsa.dev/notes/spec) but didn't come to any decision.

**Comment by Nikokrock** [comment]
Maybe an idea would be that SLSA maintains an index of index instead of directly the proper index. This way the only burden would be to register **only once** a community (a default one could be created) or a "company/provider".

Additional checks could be provided (such as relation between a given index url and the built type urls, ...)

**Comment by joshuagl** [comment]
I strongly agree with the sentiment that we should have an index. 

I also like the idea of hosting definitions in a community maintained repository in the slsa-framework GitHub organisation. I think this will facilitate easier discovery, editing and review (even post-publication review) of buildType definitions and hope this will provide both pedagogical value and opportunity for buildType definers to collaborate, share knowledge and develop best practices.

**Comment by MarkLodato** [comment]
To be clear, we are trying to bootstrap SLSA by defining buildTypes for popular CI/CD systems before proper SLSA support is implemented in those systems. We have already written [GitHub Actions](https://slsa.dev/github-actions-workflow/v1) and [Google Cloud Build](https://deploy-preview-623--slsa.netlify.app/gcb-triggered-build/v1), and I expect more in the future. We need some place to stick these definitions, with a stable (and preferably short) URL.

Our choices for these existing definitions seem to be:

- `https://slsa.dev/<type>` (status quo)
- `https://buildtype.slsa.dev/<type>` (central repo)
- Separate repo for each build type (probably under slsa-framework org), no standard URL scheme, maybe just link to github
- Ask each CI/CD vendor to host

Are there other options I missed?

Given these, I think the `buildtype` repo seems like a decent compromise. What do you think?

**Comment by lehors** [comment]
We all agree on having an index. Where we diverge seems to be on whether to have a central repository for the definitions.

I don't understand the point about having a central repository to make it easier to find, study, review them, etc. If we have an index that provides links to all the definitions how is that not fulfilling the need?

I fear that having a central repository is not a viable option long term and if we start having some in the repository now I don't know where/when we stop without arbitrarily creating a 2 class system where some types are seen as more important than others.

**Comment by joshuagl** [comment]
> I don't understand the point about having a central repository to make it easier to find, study, review them, etc. If we have an index that provides links to all the definitions how is that not fulfilling the need?

My thesis here is that discussion/review and change history that's recorded in the central GitHub project will be of value. Those things may exist in separate places for open source build systems, but are less likely to exist in a reviewable form for non-open build systems.

**Comment by lehors** [comment]
So you're saying we are going to host build type definitions for non-open build systems? Is it even possible to review those? How would anyone test them? What will be the criteria to decide whether they are correct and warrant being included? I'm sorry if I'm missing something here. I just don't understand how this would work.

**Comment by joshuagl** [comment]
There are two aspects of authoring/reviewing buildType definitions: 

1. does the buildType accurately reflect the build system?
1. does the buildType align with SLSA principles and requirements?

Inclusion in a buildtype repo would rely on the submitters for accuracy wrt the build system, any review performed by the SLSA community would be focused on whether the submitted buildType is well-aligned with SLSA (we might want to see a completed [builder evaluation document](https://slsa.dev/spec/v1.0/verifying-systems)?) and the provenance format. My desire for this to be an open, community managed, repository is in part so that we can provide examples, develop guidance and generate recommendations for future buildType authors.

**Comment by MarkLodato** [comment]
@lehors, I personally wrote the [GitHub Actions](https://slsa.dev/github-actions-workflow/v1) and [Google Cloud Build](https://deploy-preview-623--slsa.netlify.app/gcb-triggered-build/v1) build types purely from public documentation. I have no insider knowledge of either system. It is irrelevant whether the system is open or closed. Our goal is to define the security boundary around the system and we can do black-box testing to validate our claims. In fact, such security testing is valuable because often documentation or intent does not match reality. Really it takes security expertise to design and validate the type definition.

Does that help explain? If so, does it change your position on having a community maintained repository?

**Comment by lehors** [comment]
Thanks for the additional info but I still don't see why any of this requires OpenSSF to host the buildtype definitions. Having an index provides the opportunity to do all of the above (document, review, etc) without having to host and maintain information that is vendor specific (beyond hosting a link from the index).

If buildtype authors want to have their definition reviewed they can certainly do that in many different ways including while submitting the PR to get their type added to the index, right? We could even make that clear in our documentation.

I still think we should try to keep the OpenSSF SLSA space (website, repos, etc) as vendor neutral as possible. This is how all the open communities I'm familiar with function.

For that matter if we project ourselves a bit into the future and think about a day where we might want to have the SLSA specs submitted to ISO/IEC JTC1 this will become essential.

**Comment by TomHennen** [comment]
[Here's some prior art](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) where the various types are defined within the spec's repo.

**Comment by lehors** [comment]
> [Here's some prior art](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) where the various types are defined within the spec's repo.

Oh, I'm sure there are others. Whether this is the right thing to do or not is another matter. :-)
I've said my piece, I'll leave at that.

**Comment by MarkLodato** [comment]
@lehors and I chatted. His main concern was the centralization. The build types we happen to define ourselves should be on the same footing as other build types defined by other organizations. So for example calling something `slsa.dev/<whatever>` makes it more prominent than `somethingelse.example.com/<whatever>`. Then it invites others to want to get in on the `slsa.dev` namespace. The `slsa-framework` github org doesn't have the same level of prominence.

My main concern was where to stick it. I don't want to put it under my name because what if I get hit by a bus or laid off or similar? It shouldn't be tied to me personally. It's useful to be owned by an organization.

Compromise we agreed to:

- Move each build type to a separate repo under the slsa-framework org.
- Use the buildType URI as the GitHub pages URI, e.g. `https://slsa-framework.github.io/<type>`

**Comment by MarkLodato** [comment]
Proposal renames:

- `https://slsa-framework.github.io/buildtype-github-actions-workflow/v1`
- `https://slsa-framework.github.io/buildtype-gcb-triggered-build/v1`

Rationale: prefix each with `buildtype-` so that it's clear what the repo is for. (I'm also open to a suffix.) Without including "buildtype" somewhere, we risk misunderstanding that this is something else about those build systems.

**Comment by TomHennen** [comment]
> Proposed renames:
> 
> * `https://slsa-framework.github.io/buildtype-github-actions-workflow/v1`
> * `https://slsa-framework.github.io/buildtype-gcb-triggered-build/v1`

Optional: 'buildtype/...' ?

**Comment by TomHennen** [comment]
> > Proposed renames:
> > 
> > * `https://slsa-framework.github.io/buildtype-github-actions-workflow/v1`
> > * `https://slsa-framework.github.io/buildtype-gcb-triggered-build/v1`
> 
> Optional: 'buildtype/...' ?

Please disregard, @MarkLodato explained why this wouldn't meet the requirements.

**Comment by MarkLodato** [comment]
Feedback from @mrutkows confirms @lehors's worry. Matt was confused by the example `buildType` having a `slsa.dev` URL, inferring (incorrectly) that there is some registration process.

So in addition to moving the repos, we should also very explicitly call out that there is no registration and the URI can be anything.

**Comment by lehors** [comment]
@MarkLodato Thank you for working with me on this. I think we can close this issue on this.

**Comment by MarkLodato** [comment]
Thanks. I'll send out a PR to point to the new URL then, and move the GCB PR to a new repo.

**Comment by lehors** [comment]
Sounds good.
