### ISSUE TITLE
Update VSA with v1?

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#663]
Has any thought been given to updating the vsa to v1 with SLSA v1?

I think my biggest area of concern might be the [SlsaResult](https://slsa.dev/verification_summary/v0.2#slsaresult) type, it includes SLSA L4 (removed in SLSA v1) and says it "Must be one of these values".

We have an internal implementation of SLSA that still meets the spirit of the old SLSA L4.  It would be nice if it were allowed to include additional values here.  "SHOULD be one of these values" would be good enough for us.

Additionally it could probably be updated to use @marcelamelara's [ResourceDescriptor](https://github.com/in-toto/attestation/pull/143) in a couple places.

Any thoughts?

**Comment by TomHennen** [comment]
WDYT @AdamZWu ?

**Comment by AdamZWu** [comment]
Do we want to version the SLSA levels? e.g. 
SLSA_02_L4
SLSA_10_L3

Maybe that's too much? :P

**Comment by TomHennen** [comment]
From an accounting & accumulation perspective (as the VSA does) I think that would get too confusing.  You'd have 5 things at SLSA_02_L3 and 10 things at SLSA_10_L3.

**Comment by AdamZWu** [comment]
Agreed. Weakening the [SlsaResult](https://slsa.dev/verification_summary/v0.2#slsaresult) type requirement SGTM.
