### ISSUE TITLE
provenance/v1-rc1: Where do we store build spec without `build-as-code` requirement?

### ISSUE THREAD

**Issue by chitrangpatel** [slsa-framework/slsa#669]
In version 0.2 of SLSA Provenance, the unstructured nature of buildConfig allowed build systems to store the entire spec that the build was generated with. This was useful if the spec was not fetched from a remote location (eg. OCI/version control). [Tekton Chains](https://github.com/tektoncd/chains/) leverages this when generating SLSA Provenance v0.2 for builds generated by a [Tekton Pipeline](https://tekton.dev/docs/pipelines/). 

Given that `build-as-code` is no longer a requirement in `v1-rc1` (correct me if I'm wrong), the need to store the complete spec in the provenance is important.

Is there a good location where this can be stored?

**Comment by bobcatfish** [comment]
There are some recommendations in [the provenance requirements](https://slsa.dev/provenance/v1-rc1#migrating-from-02) around how to handle the buildConfig in 1.0:

* buildConfig: No longer inlined into the provenance. Instead, either:
  * If the configuration is a top-level input, record its digest in externalParameters["config"].
  * Else if there is a known use case for knowing the exact resolved build configuration, record its digest in byproducts. An example use case might be someone who wishes to parse the configuration to look for bad patterns, such as curl | bash.
  * Else omit it.

> Given that build-as-code is no longer a requirement in v1-rc1 (correct me if I'm wrong)

While it isn't required, I would assume this is still a recommended best practice (and could be part of the [producer expectations](https://slsa.dev/spec/v1.0-rc1/requirements#producer) depending on the producer?). It would be useful to still have best practices like this documented somewhere but I'm guessing this might be coming back in future iterations? (e.g. 'the source track'?) (The ['consistent build process' requirement](https://slsa.dev/spec/v1.0-rc1/requirements#follow-a-consistent-build-process) seems to be hinting at build as code?)

**Comment by chitrangpatel** [comment]
Thanks for that reference @bobcatfish! It makes things quite clear.

If we need to store the build spec, it seems like a way forward is to store it as a `byproduct artifact` and store its `ArtifactReference`. Otherwise, simply omit it.

**Comment by chitrangpatel** [comment]
I think we have clarity on this issue so closing it.
