### ISSUE TITLE
Restructure documentation and improve content

### ISSUE THREAD

**Issue by olivekl** [slsa-framework/slsa#672]
I’m planning to restructure and rewrite the docs on slsa.dev over the course several PRs before the v1.0 launch.

The goal end state is:

- Overview (slsa.dev landing page)
- Understanding SLSA
  - What's new in v1.0
  - About SLSA
  - Threats overview
  - Use cases
  - Guiding principles
  - Future directions
- Core specification
  - Security levels
  - Producing
  - Verifying
  - Threats in detail
- Attestations
  - General model
  - Provenance
  - VSA
- How to SLSA
  - For developers
  - For organizations
  - For implementers
- Specification stages
- Community
- Blog

I’m planning these PRs to keep reviews manageable:

PR 1: [DONE](https://github.com/slsa-framework/slsa/pull/683) Move / divide existing content, create new structure, but no content changes

- Change Spec index page to have multiple tables reflecting new structure
- Create Understanding–Concepts page (rename Guiding Principles to Concepts, move What is SLSA, etc into that page)
- Create Understanding–Threats Overview page (split and move 1st half of current threats info there)
- Move Use Cases under Understanding heading

PR 2:[DONE](https://github.com/slsa-framework/slsa/pull/705): Update content, focusing on Understanding SLSA section

- Edit, rewrite, and and add new content to make SLSA more understandable to newcomers

PR 3: [DONE](https://github.com/slsa-framework/slsa/pull/739) Standardize and reduce terms across all pages 

- I.e., developer vs. creator vs. maintainer; build vs. release vs. publish)

PR 4: Add new pages How to SLSA (for implementers and organizations)

- Basic instructions for three main user journeys (developers, organizations, implementers)

PR 5: [DONE](https://github.com/slsa-framework/slsa/pull/743)Add General Model under Attestations 
- Anything else lost in the shuffle

PR 6: Final nav bar reorganization, banner link to v1.0

Happy for feedback and discussion!  @di @MarkLodato @joshuagl @lehors @kpk47 @mlieberman85

**Comment by MarkLodato** [comment]
To clarify thinking here: It seems valuable to have a "SLSA v1.0" header in the menu even if technically attestation formats are versioned independently. The goal is to make it easy for a reader to find the information they are looking for. The organization of the menu might not reflect the URL scheme in all cases.

**Comment by arewm** [comment]
@olivekl, as you take another look at the pages, can you also keep in mind the `description` frontmatter to enable better link unfurling? I created #693 for this bug and committed an initial fix in #695.

**Comment by olivekl** [comment]
> @olivekl, as you take another look at the pages, can you also keep in mind the description frontmatter to enable better link unfurling?

Sure thing. I assume #695 will merge before my next PR so if needed I'll update any descriptions on pages I work on. Thanks!
