### ISSUE TITLE
Should we version all the specs together?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#680]
Right now we independently version /spec, /provenance, and /verification_summary separately to give us flexibility to have a breaking change in one (requiring a version bump) without version bumping the others. Examples:

- If we decide to do a breaking change to provenance but the level definitions have not changes, right now we can have /spec/v1.0 and /provenance/v2.
- Similarly, if we do a SLSA v2 around the levels but the v1 provenance is perfectly fine, we can keep backwards compatibility for the format.

However:

1. This causes tons of confusion, and we bend over backwards to write the spec so that they're independent. It would be much simpler if v1 always maps to v1, v2 to v2, etc.
2. It's unclear how likely this scenario actually is (YAGNI). We probably could just bundle breaking changes together and live with over-version-bumping.

So, what do you think about bundling them all together? We could keep the URLs the same, but just always keep the version numbers consistent.

/cc @olivekl

**Comment by olivekl** [comment]
I feel strongly that spec and provenance need to be versioned together for ease of user adoption. We may see the distinction between the two, but users likely do not. It'll be even more confusing to differentiate given the v1.0 addition of tracks (achieving "SLSA v1.0 Build Track L3 using Provenance v2.0" is a lot to take it, never mind down the line when there are more tracks to include). 

I can see the argument for versioning them separately, but think it's worth the trouble of delaying provenance changes until the next major SLSA spec release for the purpose of keeping them aligned.

**Comment by inferno-chromium** [comment]
+1 to versioning them together and use minor revisions for updates/changes in various parts.

**Comment by MarkLodato** [comment]
Sounds like the consensus is single version number.

Assuming we agree on this, I recommend simplifying our URL scheme to put the version as the first directory component, e.g. `/v1.0/requirements` or `/v1.0/provenance`. We can still use `https://slsa.dev/provenance/v1` as the `predicateType` URI and have it redirect to the other form (`/v<major>.<minor>/provenance`).

**Comment by MarkLodato** [comment]
We have this as a plan of record. Future refactorings can clean up the implementation, but from the user-visible perspective, the versions are all tied together now.
