### ISSUE TITLE
Change terminology to focus on software distribution ("release", "package", etc.)

### ISSUE THREAD

**Issue by david-a-wheeler** [slsa-framework/slsa#7]
I suggest changing "Deploy" to "Release" (where it produces a resource). You might also want add *another* step that involves the user "acquiring" the resource.

I think typically the word "deploy" means "install & operate in the production environment". It makes sense why Google would use the word "deploy" and "release" synonymously, since they're often the same for Google.

But for many situations, a release is *NOT* the same as deployment. E.g., if someone releases a package on PyPI or npm, that does *NOT* mean it's deployed, that just means it is now available for users to download & possibly deploy.

**Comment by MarkLodato** [comment]
The intention was to have the same term mean both cases:

* A "release" to some sort of package manager.
* A "deployment" to some sort of execution environment.

Both the package manager and the environment are "resources." Each could have its own SLSA level.

For example, consider the case where you have source code in GitHub repo X, built into a Docker image released to DockerHub repo Y, and deployed to Kubernetes cluster Z. You could have two separate policies, one on Y (whose policy requires X) and one on Z (whose policy requires Y), or you could have a single policy on Z (requiring X -> Y).

That said, I don't think this is super clear and think it could be improved.

**Comment by david-a-wheeler** [comment]
I don't think most people think that "releases" and "deployments" are the same. Conflating them seems confusing. If you want to cover both processes, I think it'd be better to model them as two different processes.

**Comment by MarkLodato** [comment]
Repurposing this bug to capture the overall goal of changing the terminology to reflect the scenario of "releasing" a "package" so that others can use it.

**Comment by MarkLodato** [comment]
From @dlorenc in #38:

> Given this is centered on artifacts, I think the term "publish" is more commonly used. In my mental model:
>
> Deployment == fetching an artifact and running it.
> Publish == building an artifact and making it available.

**Comment by dlorenc** [comment]
Big +1 to publish or release here. I understand the desire to try to keep things consistent between deploying to prod environments and publishing a release, but I worry that in practice they're treated too differently for this make sense.

**Comment by MarkLodato** [comment]
To summarize all of the duplicated threads:

* [ ] Rename "deployment" to "publish" (or "release")
* [ ] Rename "resource" to "package" (or "artifact", or something else) - see #21 for discussion
* [ ] Add an explicit "Use" box in the diagram
* [ ] Better explain the terms - see also #8

**Comment by MarkLodato** [comment]
See #53. I'll mark this as resolved but we'll continue to iterate on the message, and please reopen if you have some more comments.
