### ISSUE TITLE
SLSA v1: Define tenant, admin, control plane, and untrusted build as it relates to a build model

### ISSUE THREAD

**Issue by arewm** [slsa-framework/slsa#717]
Can we provide additional clarity around what it means for provenance completeness to be best effort? Is this just best effort because we are assuming that up to L3 there are just well-intentioned users? Is this best-effort of completeness the driving force behind other requirements as well (i.e. isolation) and the specific absence of additional requirements to around checking/enforcing against tampering in the build system?

I started to include statement around best effort completeness in #700 but I ended up pulling them out as the conversation was distracting from the specific improvement made around isolation. 

@Nikokrock also touched on this bit in #699.

**Comment by MarkLodato** [comment]
I think "well-intentioned" is not the right term. It's misleading.

Rather, I wanted to say that the any sort of external influence on the build that violates the Isolated principles MUST NOT be the fault of the build system. In other words, a build that does not do anything "wrong" MUST be isolated, but that a "wrong thing" MAY exist and a producer need not protect against it.

**Comment by arewm** [comment]
That makes sense, we can iterate on wordings around violations in the isolation principles MUST NOT be the fault of the build system.

What does this require of the build system? Would it require that the build system to perform some form of self-validation of its integrity before being able to claim a build L3? For example, in a build system leveraging Tekton, would the build system need to ensure that producers do not modify the Pipeline/task definitions?

**Comment by MarkLodato** [comment]
> What does this require of the build system? Would it require that the build system to perform some form of self-validation of its integrity before being able to claim a build L3? For example, in a build system leveraging Tekton, would the build system need to ensure that producers do not modify the Pipeline/task definitions?

Sorry, I don't understand the question. Is this with respect to how much effort the build system must go through to prevent a user from violating the spirit of the requirement? I don't know what you mean by "self-validation of its integrity". As for Tekton, I'm not very familiar with it, but if they are akin to GitHub Actions workflows or actions, it seems like we'd need to support custom ones?

**Comment by MarkLodato** [comment]
> Are there other requirements imposed on the build system (other than isolation) that are "okay" to be violated as long as they MUST NOT be the fault of the build system?

Good question. No. The only other requirement is that the [provenance is non-forgeable](https://slsa.dev/spec/v1.0/requirements#provenance-non-forgeable), and that MUST NOT be violated by builds.

> If a build system can be customized by users, would it be the responsibility of the build system to only allow certain modifications?

Sorry, I'm not sure what this means. We [model](https://slsa.dev/spec/v1.0/terminology#build-model) a build as having two distinct sets of users:

- Privileged admins who are considered part of the trust base (represented by `builder.id`)
- Regular users (tenants) who can write build definitions

In Isolated we are only defending against regular users. The privileged admins are expected to have some means to access the provenance, and the [verifying systems](https://slsa.dev/spec/v1.0/verifying-systems) is a framework for deciding if that admin access is acceptable. (For example, you might say, "No person should have direct unilateral access; they must need to get approval from at least N other people first.")

By "customized by users" do you mean admins who run the service or regular users of the service?

**Comment by MarkLodato** [comment]
> > Sorry, I'm not sure what this means. We [model](https://slsa.dev/spec/v1.0/terminology#build-model) a build as having two distinct sets of users:
> 
> Is that being added? I cannot see it on the page right now.

It's not on there but should be. Let's use this issue for that.

> I feel like this might come down to ensuring a correct representation of what is included in a trusted build system. For example, only known and trusted system-defined tasks are included in the trust model. Therefore, in order to achieve build L3, would the system have to verify that only those known and trusted tasks/steps were used? Or would that likely fall further to L4?

Yes, I think it comes down to defining a clear trust boundary (#706) between "trusted control plane" and "untrusted build process". The provenance generation MUST happen in the trusted control plane at L3, and it MUST NOT be possible for a regular user to access or tamper with the trusted control plane. It sounds like the pipeline config is part of the "untrusted build process", so the service's obligations are to:

1. Record the fact that it started that pipeline, listing all external parameters (github repo + ref + config file path, plus any other parameters.)
2. Ensure that a pipeline cannot, by default, be influenced by other pipelines. For example, running two different pipelines on the same machine without a sufficiently strong sandbox would NOT be OK at L3.

Does that help?

**Comment by MarkLodato** [comment]
> We [model](https://slsa.dev/spec/v1.0/terminology#build-model) a build as having two distinct sets of users:

To expand, this is currently implicit. The "tenant" is the regular user and the "admin" is the privileged user. We defined "admin" in [v0.1](https://slsa.dev/spec/v0.1/terminology#build-model) but removed it in v1.0 since we don't use that term anywhere else. But it sounds like we should re-add it and explain this more thoroughly.

**Comment by arewm** [comment]
Thanks for that, it is clearer now. 

In addition to expanding on the differences between a tenant and an admin, I think it would be beneficial to include specific differentiation between the control plane and an untrusted build process (and their relationship to the tenant/admin).

**Comment by arewm** [comment]
In order to help address some of the concerns raised in #653, I think that the specification requirements also need to be worded to indicate that provenance should be created from the trusted control plane to ensure accuracy.
