### ISSUE TITLE
SLSA V1.0 Spec wording - "Higher SLSA build levels provide increased confidence that a package truly came from the correct sources", is 'correct' accurate?

### ISSUE THREAD

**Issue by khalkie** [slsa-framework/slsa#729]
A nit about the wording on https://slsa.dev/spec/v1.0-rc1/levels#build-track

"Higher SLSA build levels provide increased confidence that a package truly came from the **correct** sources, without unauthorized modification or influence."

My question is around the accuracy of the word 'correct', I don't think this makes any claims or improvements as to the 'correctness' of the sources, rather just that the provenance is an accurate representation of the sources. I.e. you can still be importing the wrong thing, SLSA won't help with that but it will accurately describe the wrong thing you're importing

**Comment by MarkLodato** [comment]
You are right. A simple fix is to replace "correct" should have been "expected", but the actual underlying issue is that we have not yet removed the concept of expectations from the build track. That is something we need to fix for RC2.
