### ISSUE TITLE
Need "How to SLSA" for organizations and infrastructure providers

### ISSUE THREAD

**Issue by olivekl** [slsa-framework/slsa#730]
The v1.0 heading How To SLSA has content for developers, but only placeholders for the content for organizations and implementers (=infrastructure providers, pending PR to standardize terms). 

For ease of adoption, I think it'd be great to fill in the missing sections before RC2. Even if it's just a few paragraphs each, it would be really helpful to include some instructions that tell orgs and infrastructure providers how to get started and navigate to the information most pertinent to them. 

@kpk47 has some ideas to get started; would anyone be able to work with him to get these two sections added?

**Comment by kpk47** [comment]
I don't think we need too much here. A few thoughts, not in any particular order:
- We should emphasize that CI/CD systems should be producing provenance, not individual compilers. I think this can go on the infrastructure provider's page.
- Package ecosystems should be verifying provenance, with individual consumers verification as a fallback. Also on the infrastructure provider's page?
- Organizations need to decide which SLSA level they want to meet and then choose appropriate tooling.
- We might also want to give the individuals page another pass to emphasize the point that most of their job is picking the correct tools.

**Comment by olivekl** [comment]
> * We might also want to give the individuals page another pass to emphasize the point that most of their job is picking the correct tools.

I think that's a good idea, and could be combined with adding the table suggested in Issue #697.

**Comment by olivekl** [comment]
Closing -- these pages were added for the v1.0 launch.
