### ISSUE TITLE
Who sets expectations?

### ISSUE THREAD

**Issue by kpk47** [slsa-framework/slsa#736]
Following up on the discussion from #675 , I think we can still improve the language around setting expectations. We currently have

>During package upload, a package ecosystem can ensure that the artifact’s provenance matches the known expectations for that package name before accepting it into the registry

and

> Consumers can set their own expectations for artifacts or use default expectations provided by the package producer and/or package ecosystem.

@olivekl pointed out that these sentences imply that "expectations" can have two meanings: the expected values publicized by the producer and the expected values the consumer uses for verification. https://github.com/slsa-framework/slsa/pull/675#discussion_r1140712387

I propose that we use "expected values" or "expected <provenance field>" for the former (publicized by producer) and "verification policy" for the latter (enforced by party performing verification).

**Comment by kpk47** [comment]
@lehors @MarkLodato @olivekl - Do any of you have thoughts here?

**Comment by kpk47** [comment]
I've also filed a draft PR if it's easier to discuss a straw proposal: https://github.com/slsa-framework/slsa/pull/737.

**Comment by di** [comment]
> Is "set of constraints" the right description for expectations set by producers? Are they actually acting as constraints, or is only the verification policy acting as constraints?

I think you're right, they aren't really "constraints" until they're applied during some verification process.

I'm not sure "guidance" is accurate, perhaps the producer's expectations are "potential constraints"?

**Comment by kpk47** [comment]
I like Kara's definition. So that would leave us with 

> Expectations: A set of expected values for the purpose of verifying the package's provenance metadata. The package producer sets expectations for a package, whether explicitly or implicitly. 
and 

> Verification policy: A set of constraints on the package's provenance metadata. The provenance consumer sets the verification policy based on the expectations.

@MarkLodato @lehors any thoughts here? I'd like to make this change by the 3/31 cutoff for inclusion in RC2.

**Comment by MarkLodato** [comment]
I'm ok with that.

I need to do a whole pass across the site to check for consistency with how we use terms, but that'll have to wait to the RC2 review period.

**Comment by kpk47** [comment]
Great. I'll send a PR this afternoon updating the terminology page and making the change across the site. I think most of the changes will be on the 'verifying artifacts' page.

**Comment by lehors** [comment]
Of course, as discussed before, the consumer always has the last say on what their policy is so the expectations set by the producer only become constraints to the extent that the consumer sets their policy to treat them as such.
That's implied in what I said earlier but I just want to be clear about it.

**Comment by MarkLodato** [comment]
Is this now resolved by #795, or is further work needed?

**Comment by kpk47** [comment]
We've resolved my concerns. Any new ones can be in a new issue.
