### ISSUE TITLE
v1 VSA dependency_levels should be optional

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa#738]
The dependency_level is a required field even though the resolvedDependencies is "best effort" for level 1-3. I think it's unclear how this field should be generated for level <= 3, since dependencies are not all listed.

I think more details on how to populate this field would be useful, especially for cases where `completeness:false`, which is the majority of cases today.

I may even be optional for level <= 3.

**Comment by MarkLodato** [comment]
I also suggest that it is optional.

**Comment by AdamZWu** [comment]
Ah yeah I think marking it optional is fine.

My original thinking is that, since it is a map, it can just be left as empty. But not having it would imply the same, and is less verbose, so SGTM. :)

WDYT, @TomHennen ?

**Comment by TomHennen** [comment]
Sounds good. :)
