### ISSUE TITLE
"Verifying artifacts" is unclear how it relates to levels

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#786]
It is currently unclear how [verifying artifacts](https://slsa.dev/spec/v1.0/verifying-artifacts) relates to the levels and requirements.

- It uses the term "MUST" without indicating what it is required for. Is this for the build track? For anything SLSA? Or is this just guidelines
- It uses "L1", "L2", and "L3" without any reference to tracks. If this is the build track, why is it not listed in the requirements? (Also I thought we decided verification is *not* a requirement for the build track?) If it is not, what is it?

I suggest removing the term "MUST" and references to levels from the doc, and turning it into guidelines or recommendations instead.

**Comment by joshuagl** [comment]
We also agreed to update "distributing provenance" to match, that is replace "MUST" with "SHOULD" and convert it into recommendations for v1.
