### ISSUE TITLE
v1: Clarify differentiation between build system and build service

### ISSUE THREAD

**Issue by arewm** [slsa-framework/slsa#787]
In https://github.com/slsa-framework/slsa/pull/779#discussion_r1154764715, it was raised that both build system and build service are used without a clear distinction. This distinction should be clarified and the specification should be reviewed to ensure that the distinction is consistently used.

My comments on the distinction from the thread:

> There isn't clear consistency across the requirements page. I see the build system as a generic term for the trusted boundary producing an artifact. It may be a service (GitHub Actions, etc.) or it may be a non-service (individual's machine).
> 
> Since the isolation requirements for L2 are a build service, it is consistent to start talking about a build service at L2 requirements in provenance.

**Comment by MarkLodato** [comment]
Let's consider this as part of #714.
