### ISSUE TITLE
Ephemeral vs. persistent artifacts

### ISSUE THREAD

**Issue by AdamZWu** [slsa-framework/slsa#80]
The definition of Build describes the inputs "may be sources, dependencies, or ephemeral build outputs."

To my understanding, "dependencies" are persistent build output artifacts. Is that correct?
If so, I wonder what is the significance of differentiating the persistent vs. ephemeral artifacts?
Could we unify them and just define build input as "may be sources and output artifacts of prior builds."?

**Comment by kpk47** [comment]
This issue is obsolete.
