### ISSUE TITLE
VSA: can we be more consistent with SLSA fields and VSA fields

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa#809]
#### builder and verifier id.
The builder.id is:
```json
"builder": {
                "id": string,
                "builderDependencies": [ ...#ResourceDescriptor ],
                "version": { ...string },
            },
```

but in VSA, the verifier.id is:
```json
"verifier": {
    "id": "<URI>"
  },
```

Those fields should be aligned in their definition. Right now, there's no way to version the verifier. At least, can we add a version field?

#### resource_uri

The provenance uses ResourceDescriptor, but VSA uses a string `resourceUri` only. Can we use ResourceDescriptor for the resource in the VSA?

**Comment by TomHennen** [comment]
I'm fine to add a `verifier.version` field.

However, I don't think ResourceDescriptor is a good fit for resource_uri because it's not trying to describe a specific instance of a resource.

**Comment by laurentsimon** [comment]
what do you mean by "specific instance"?

**Comment by TomHennen** [comment]
In the VSA the resource URI is being used to identify the scope of the thing that was verified.  (e.g. acorn://foo in [this example](https://security.googleblog.com/2022/04/how-to-slsa-part-2-details.html#:~:text=be%20SLSA%204.-,scope%3A%20%27acorn%3A//foo%27,-target_level%3A%20SLSA_L4)).

By specific instance I guess I mean version 1.2.3 of acorn://foo with hash abc123.  So I guess I'm not sure what all those other fields in ResourceDescriptor would refer to.  Do you have a use case in mind?

(It does occur to me that `resource` is overloaded in these cases)

**Comment by laurentsimon** [comment]
re: resourceDescriptor: I think I see what you mean.
Once there is agreement on adding (or not) the version field, I'll close the issue and we can discuss the resource_uri in https://github.com/slsa-framework/slsa/issues/808. I think I just need to understand better how the resource_uri needs to be populated, in particular the version part.

**Comment by kpk47** [comment]
I sent #905 to add the verifier.version field.
