### ISSUE TITLE
Provenance: Should we rename `systemParameters` to `internalParameters`?

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#815]
In #810, we are converging on "build platform" instead of "build system " or "build service". But we currently have `systemParameters` in the provenance schema, and we cannot rename that without a breaking change.

Should we rename `systemParameters` to `internalParameters` (to mirror `externalParameters`) or perhaps `trustedParameters` (to denote trust)? Either of those two alternates are probably better names than the current one.

Is this high enough priority to warrant a change before v1.0? After v1.0, I'm guessing it's not worth breaking backwards compatibility.

**Comment by TomHennen** [comment]
FWIW I think 'internal' or 'trusted' parameters are _much_ easier to understand.

**Comment by arewm** [comment]
+1 I am preferring `internal` to `trusted` to mirror `external`.

**Comment by kpk47** [comment]
I like both options, but if we choose "trustedParameters" then we should switch externalParameters to "untrustedParameters".

**Comment by MarkLodato** [comment]
Discussed at today's Specification meeting. Consensus was:

- Make this change ASAP.
- Very clearly highlight this is a difference from RC2, to avoid surprises for early implementers.
- Use `internalParameters` to mirror `externalParameters`. ("Trusted" vs "untrusted" is too ambiguous.)

Volunteers welcome! If you start, please comment here to avoid multiple people working on it simultaneously.
