### ISSUE TITLE
Trustlessness of provenance using Public DLTs (Blockchains)

### ISSUE THREAD

**Issue by joshbenaron** [slsa-framework/slsa#865]
Hey - has there been any discussion around using public blockchains for trustless provenance creation and verification? i.e. not having to trust a central third part for provisioning or verifying provenance

**Comment by mlieberman85** [comment]
Can you elaborate a bit more here? In the context of public blockchains what would be performing the builds and how could those builds be validated and verified in a trustless way?

**Comment by joshbenaron** [comment]
Blockchains are able to provide builtin content integrity and trustless attribution of time and metadata. i.e. knowing when a build was created etc, and also attaching immutable attributes.

This would surely be a level of resiliency for supply chains

**Comment by mlieberman85** [comment]
I'm not following. You still need to have a builder that records the provenance for a build. How does that happen on the blockchain?

If we're talking purely about the immutable recording of attributes we already have that via the signed provenance metadata. Someone would be unable to manipulate or forge the data unless they had the signing key. Either way you still need to verify that a build came from a party you trust to have performed that build.

If you are worried about someone lying about the time they signed it there are transparency logs for this. Someone could record this data on a public blockchain, but it doesn't really fit into the core of SLSA unless I'm misunderstanding.
