### ISSUE TITLE
Add new field externalParameters.source to provenance spec.

### ISSUE THREAD

**Issue by kpk47** [slsa-framework/slsa#869]
We removed `invocation.configSource` from the provenance spec in v1.0, but the SLSA GitHub generator maintainers think we need the `uri` and `digest` fields for verification. They propose is specifying a `source` entry for `externalParameters` with type `resourceDescriptor`. It would look something like

```
"buildDefinition": {
  "externalParameters": {
    "source": {
      "uri": old.invocation.configSource.uri,
      "digest": old.invocation.configSource.digest,
    },
  },
}
```

I support this change but don't know whether this field should be RECOMMENDED or REQUIRED.

The discussion is at https://github.com/slsa-framework/slsa-github-generator/issues/2186.

**Comment by laurentsimon** [comment]
In the specs, the source field already exists:
```json
"source": old.invocation.configSource.uri,
```

iiuc, this is considered a string then? We should not consider it a ResourceDescriptor?

**Comment by MarkLodato** [comment]
That is just an example showing how one might convert. It is not canonical.
