### ISSUE TITLE
Use better definition for "readable", based on legal terminology

### ISSUE THREAD

**Issue by david-a-wheeler** [slsa-framework/slsa#9]
The "readable" criterion has a loophole: Would a JPEG of the source code be acceptable as source code? Presumably not, but that's not clear.

I suggest adding a related criterion 'editable': The source artifact for a work means the preferred form of the work for making modifications to it.

This could also be added as part of readable.

**Comment by MarkLodato** [comment]
Thanks David. As you explained to me, "preferred form of the work for making modifications to it" is a legal definition of "source code". We should use that.

I would make it part of "readable".
