### ISSUE TITLE
Automate merging of PRs once they meet the approval and waiting criteria

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#917]
Our [CONTRIBUTING](https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md) policy is now a bit complicated, requiring mandatory waiting periods and different number of approvals for different PRs. This is a fair amount of manual work for the approver to do, and likely leads to PRs hanging around for a long time waiting to be merged.

I think GitHub's [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) feature could automate this for us:
- Create a workflow on `pull_request` and `merge_group` that verifies that all PRs have the requisite number of approvers and waiting time. Then it would get the green check when it's ready to merge.
- Set up the merge queue to automatically merge things that are ready.

We probably also want some sort of convention to indicate that the author is ready for it to be merged. Often a PR is approved but the author still plans more changes. Or maybe just the minimum waiting period is OK, with a way to say "don't merge yet"?

**Comment by joshuagl** [comment]
Maintainers and PR authors could convert a PR which isn't ready to merge to draft status: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by kpk47** [comment]
Discussed in the community meeting on 2023-07-24. We will not pick address this issue. If the waiting period is a problem in the future, we will revisit the process and/or automation then.
