### ISSUE TITLE
Broken GitHub link in slsa.dev footer

### ISSUE THREAD

**Issue by rsamborski** [slsa-framework/slsa#922]
The following link in the footer of slsa.dev page is broken:
 https://github.com/slsa-framework/slsa/blob/a977927131e2ec18557f7acb444dfa1d02536610/docs/_includes/footer.html#L14

I am not providing a fix, because I am not sure where it should lead based on team's intention.

**Comment by joshuagl** [comment]
Great find, thanks @rsamborski ! We recently switched from using GitHub Pages to Netlify for hosting slsa.dev (see, i.e., #898).  I wonder if this was accidentally broken in the transition.

AFAICT those links _should_ point to the raw markdown source of a page in the GitHub repo, but:
* `site.github.source.branch` is pointing to the `gh-pages` publish branch, but our repo doesn't have that branch --> should be `main`
* `site.github.source.path` is just `/` --> should be `/docs`

We may also want to append the `?plain=1` parameter to show readers the raw markdown, not the rendered preview version.

**Comment by MarkLodato** [comment]
Yes, it's definitely the switch to Netlify. I'll send out a fix. Thanks for reporting.
