### ISSUE TITLE
Update or remove motivating example

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#943]
The [motivating example](https://slsa.dev/example) page isn't included in the site's navigation and has fallen out of date with the v1.0 changes to the specification (switch to tracks and removal of SLSA Build L4).

Should we remove the page, or update it? We have [overview](https://slsa.dev/spec/v1.0/threats-overview) and [detailed](https://slsa.dev/spec/v1.0/threats) documentation of threats and mitigations that form part of the spec, so the example is perhaps not as useful as it was in the past.

Any objection to just removoing it?

**Comment by MarkLodato** [comment]
Removing SGTM. It's still in version history if we need it.
