### ISSUE TITLE
Allow alternative digest algorithms

### ISSUE THREAD

**Issue by jchestershopify** [slsa-framework/slsa#96]
Currently ([as of](https://github.com/slsa-framework/slsa/commit/7fafe1e81e080497d8f1fa761567062be9768a24#diff-5bea49bc6a4a5effcab01d13dbb5e4e544153ed39ad567b9fad7671c1b568c0eR355-R363)), the requirements doc says of identifying artifacts that:

> The provenance identifies the output artifact via a cryptographic hash. The RECOMMENDED algorithm is SHA-256 for cross-system compatibility. If another algorithm is used, it SHOULD be resistant to collisions and second preimages.

It would be useful if provenance tooling could calculate multiple digests, so that if one digest algorithm is rendered untrustworthy, there is still a redundant way to assure integrity.

1. Recommending an algo+digest format, eg JWT's `alg` field or W3C [Subresource Integrity](https://w3c.github.io/webappsec-subresource-integrity/#hash-functions). 
2. Allow provenance systems to attach multiple digests to a single resource.

**Comment by TomHennen** [comment]
Hey Jacques,

The recommended provenance format _does_ allow multiple digest algorithms: https://github.com/in-toto/attestation/tree/main/spec#statement

The subject field could look like:

```
  "subject": [
    {
      "name": "foo",
      "digest": {"sha256": "abcd", "sha512": "1234"}
    }
  ]
```

**Comment by jchestershopify** [comment]
Ah, I missed that! But could we at least get a "... MAY allow multiple digest algorithms to be applied" or similar in the requirements itself? That would help prevent future passers-by like yours truly from making the same request.

**Comment by inferno-chromium** [comment]
> Ah, I missed that! But could we at least get a "... MAY allow multiple digest algorithms to be applied" or similar in the requirements itself? That would help prevent future passers-by like yours truly from making the same request.

Can you submit a PR for the wording change that makes it more clear ?

**Comment by jchestershopify** [comment]
> Can you submit a PR for the wording change that makes it more clear ?

Let me see what I can come up with.

**Comment by jchestershopify** [comment]
@inferno-chromium see #98 for my suggested rewording.

**Comment by jchestershopify** [comment]
Closing as #98 was merged.
