### ISSUE TITLE
website bug: latest blog post not showing

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa#962]
The latest blog post is not showing. The file `blog/2023/08/bring-your-own-builder-github.html` appeared during the deploy preview and appears when I build locally, but the netlify build doesn't include that page. See zip file below.

https://slsa.dev/blog
https://github.com/slsa-framework/slsa/blob/main/docs/_posts/2023-08-28-bring-your-own-builder-github.md?plain=1
https://github.com/slsa-framework/slsa/commit/d932416efaa0013e64b78243a44d8a5617c7a9c2

### Local build

```bash
$ git log --oneline -2
df9b442 (HEAD -> main, origin/main, origin/HEAD) impl: Update actions/checkout action to v3.6.0 (#960)
d932416 blog: post for Build-Your-Own-Builder on GHA (#929)
$ bundle exec jekyll build
[...]
$ ls _site/blog/2023/08
bring-your-own-builder-github.html
```

### Netlify build

https://app.netlify.com/teams/slsa/builds/64e911a82c205e00082f4842
Production: main@[d932416](https://github.com/slsa-framework/slsa/commit/d932416efaa0013e64b78243a44d8a5617c7a9c2)
`$ bundle exec jekyll build`
Download the zip

```bash
$  unzip -l ~/download/deploy-64e911a82c205e00082f4842.zip| grep blog/2023 | sort -k4
        0  2023-08-29 11:37   blog/2023/
        0  2023-08-29 11:37   blog/2023/02/
    30916  2023-08-29 11:37   blog/2023/02/slsa-github-workflows-container-ga.html
    24502  2023-08-29 11:37   blog/2023/02/slsa-v1-rc.html
        0  2023-08-29 11:37   blog/2023/04/
    17537  2023-08-29 11:37   blog/2023/04/slsa-v1-final.html
    17871  2023-08-29 11:37   blog/2023/04/slsa-v1-rc2.html
    19567  2023-08-29 11:37   blog/2023/04/the-breadth-and-depth-of-slsa.html
        0  2023-08-29 11:37   blog/2023/05/
    25097  2023-08-29 11:37   blog/2023/05/bringing-improved-supply-chain-security-to-the-nodejs-ecosystem.html
    47930  2023-08-29 11:37   blog/2023/05/in-toto-and-slsa.html
        0  2023-08-29 11:37   blog/2023/06/
    24869  2023-08-29 11:37   blog/2023/06/slsa-github-worfklows-container-based.html
```

**Comment by kpk47** [comment]
Clearing the netlify cache and re-deploying the website fixed the issue. The blog post is now live: https://slsa.dev/blog/2023/08/bring-your-own-builder-github
