### ISSUE TITLE
Threat overview uses wrong terminology

### ISSUE THREAD

**Issue by eruvanos** [slsa-framework/slsa#982]
Like mentioned under "Terminology" the term repository should exclusively be used to mean “source repository”.
The image included within "Supply chain threats" lists "G: Compromised package repo".
In my understanding this should be changed to: "G: Compromised package registry"

> Ambiguous terms to avoid
> Package repository: Could mean either package registry or package name, depending on the ecosystem. To avoid confusion, we > always use “repository” exclusively to mean “source repository”, where there is no ambiguity.

**Comment by joshuagl** [comment]
Well spotted, thanks. Would you like to submit a PR to fix that?
