### ISSUE TITLE
Publish list of maintainers

### ISSUE THREAD

**Issue by kpk47** [slsa-framework/slsa#997]
SLSA doesn't explicitly publish its list of maintainers. You can infer who the maintainers are from .github/CODEOWNERS, but the information should be easier to find. Additionally, several people have write access to the repo despite not (theoretically) being maintainers due to the repo's permissions setup.

We should publish a maintainers list and clean up the write ACLs so it's clear who has which privileges and responsibilities.

**Comment by kpk47** [comment]
Here is the current state of the slsa-framework/slsa's permissions:
- slsa-framework/slsa grants "SLSA" organization Admin permission 
- slsa-framework/slsa grants "SLSA Steering Committee" Write permission                                  
- slsa/framework/slsa grants additional permissons to two people. It is unclear whether they should have this permission or whether they still want it.

Here is the current state of the slsa-framework organization's  membership: 
- SLSA organization gives all members Admin permission                                                   
- SLSA organization has 25 members. It isn't clear if or how that list is maintained.                    
- SLSA organization has one team: "SLSA Steering Committee". This team appears to be up-to-date.

Eventually, we should grant no default permissions to members of the SLSA organization, but we can't make that change right away because other repos in the project might depend on contributors having Write access without explicit permissions. For now, we can make the following changes:
- Create a new team "Specification Maintainers" and add the current maintainers to it.
- Grant Maintain permission on slsa-framework/slsa to "Specification Maintainers".
- Publish the membership of "Specification Maintainers" in slsa-framework/slsa/MAINTAINERS.md. We will have to keep this file up-to-date manually.

I'm not sure how best to remove permissions from the SLSA org, but I think this is the right end state:
- "SLSA Steering Committee" and @thelinuxfoundation have Owner permission on all repos under slsa-framework. I could also see an argument for only granting Owner to @thelinuxfoundation and granting Admin to "SLSA Steering Committee" instead.
- Each active repo has a maintainers group that gets Maintain permission.

**Comment by MarkLodato** [comment]
Sounds good to me!

One note: we still probably want to allow anyone to join the slsa-framework org, even with no special permissions, because it's the only way to configure GitHub to route emails to an alternate address. This is valuable if you use the same GitHub account for work and personal use. (I do, which is why I know about this.)
